# SPDX-License-Identifier: MIT
webserver:
   sechub:
      ## Setup integration test sechub user (currently admin, later other role)
      userid: int-test_superadmin
      apitoken: int-test_superadmin-pwd