# SPDX-License-Identifier: MIT
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: db_user
    password: db_password
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    locations:
    - classpath:db/migration
    - classpath:db/migration/h2