# SPDX-License-Identifier: MIT
server:
  ssl:
    keyStoreType:
      ${SECHUB_WEBSERVER_SSL_KEYSTORE_TYPE}
    key-store:
       ${SECHUB_WEBSERVER_SSL_KEYSTORE_LOCATION}
    key-store-password:
       ${SECHUB_WEBSERVER_SSL_KEYSTORE_PASSWORD}
    key-alias:
       ${SECHUB_WEBSERVER_SSL_KEYSTORE_ALIAS}
