# SPDX-License-Identifier: MIT
spring:
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration/common
  jpa:
    database:
    database-platform: org.hibernate.dialect.PostgreSQLDialect