# SPDX-License-Identifier: MIT

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web-ui-policy
spec:
  ingress:
  - ports:
    - port: 4443
      protocol: TCP
  podSelector:
    matchLabels:
      name: web-ui
