// SPDX-License-Identifier: MIT

:toc:
:numbered:

= FindSecurityBugs + PDS

https://find-sec-bugs.github.io/[FindSecurityBugs] is a free and open source static application security testing tool. FindSecurityBugs is a command line interface (CLI) tool. By combining FindSecurityBugs with the SecHub https://mercedes-benz.github.io/sechub/latest/sechub-product-delegation-server.html[Product Delegation Server (PDS)] in a container, FindSecurityBugs can be used with SecHub. Another scenario is to use PDS + FindSecurityBugs standalone.

Furthermore, the combination of FindSecurityBugs and PDS makes it possible to run both inside a Kubernetes cluser or virtual machines.

This folder contains the necessary scripts to run FindSecurityBugs+PDS inside a container locally. Additionally, it contains scripts to build and push the PDS + FindSecurityBugs container to your container registry and a Helm chart to install and run FindSecurityBugs+PDS in a Kubernetes cluster.

== Run Locally

This is the easiest way to get started.

=== Requirements

Docker and Docker-Compose need to be installed:

. https://docs.docker.com/engine/install/[Install Docker]

. Linux: https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user[Use Docker as non Root user]

. https://docs.docker.com/compose/install/[Install Docker-Compose]

=== Single Instance

Start a single instance by using the Bash wrapper script.

The folder contains a start script:

----
./01-start-single-docker-compose.sh
----

==== Together with SecHub

The container will be started and attached to the `sechub` Network.

WARNING: Make sure the SecHub container is running.

. Start FindSecurityBugs+PDS container:
+
----
./05-start-single-sechub-network-docker-compose.sh
----

[[scan]]
=== Scan

The steps required to scan with the PDS.

==== Scan Script

. Set the environment variables
+
----
export PDS_SERVER=https://<pds-host>:<port>
export PDS_USERID=admin
export PDS_APITOKEN="<pds-admin-apitoken>"
export PDS_PRODUCT_IDENTFIER=PDS_FINDSECURITYBUGS
----
+
For example:
+
----
export PDS_SERVER=https://localhost:8444
export PDS_USERID=admin
export PDS_APITOKEN="pds-apitoken"
export PDS_PRODUCT_IDENTFIER=PDS_FINDSECURITYBUGS
----
+
[NOTE]
Those values are the default values from `env-initial` and `env-cluster-initial` files. In case you run FindSecurityBugs+PDS in Kubernetes or other environments those values will be different.

. Scan by providing a `TAR` folder with JVM bytecode (JAR, WAR, `.class`).
+
----
../shared/01-test.sh <path-to-tar-file>
----
+
For example:
+
----
../shared/01-test.sh ~/myproject.tar
----

=== Cluster

The cluster is created locally via `docker-compose`.

==== Shared Volume

The cluster uses a shared volume defined in `docker-compose`. Docker allows to create volumes which can be used by multiple instances to upload files to. Reading, extracting and analysing the files is done in the FindSecurityBugs+PDS container.

The cluster consists of a PostgreSQL database, a Nginx loadbalancer and one or more PDS server.

image::../shared/media/cluster_shared_volume.svg[Components of cluster with shared volume]

===== Scan Using Shared Volume

Starting several FindSecurityBugs+PDS instances:

----
./50-start-multiple-docker-compose.sh <replicas>
----

Example of starting 3 FindSecurityBugs+PDS instances:

----
./50-start-multiple-docker-compose.sh 3
----

==== Object Storage

The cluster uses an object storage to store files. The cluster uses https://github.com/chrislusf/seaweedfs[SeaweedFS] (S3 compatible) to store files. The PDS instance(s) use the object storage to upload files to. Reading, extracting and analysing the files is done in the FindSecurityBugs+PDS container.

The cluster consists of a PostgreSQL database, a Nginx loadbalancer, a SeaweedFS object storage and one or more PDS server.

image::../shared/media/cluster_object_storage.svg[Components of cluster with object storage]

===== Scan Using Object Storage

Starting several FindSecurityBugs+PDS instances

----
./51-start-multiple-object-storage-docker-compose.sh <replicas>
----

Example of starting 3 FindSecurityBugs+PDS instances

----
./51-start-multiple-object-storage-docker-compose.sh 3
----

=== Change the Configuration

There are several configuration options available for the FindSecurityBugs+PDS `docker-compose` files. Have a look at `env-example` for more details.

=== Troubleshooting

This section contains information about how to troubleshoot FindSecurityBugs+PDS if something goes wrong.

==== Access the container

----
docker exec -it pds-findsecuritybugs bash
----

==== Java Application Remote Debugging of PDS

. Set `JAVA_ENABLE_DEBUG=true` in the `.env` file

. Connect via remote debugging to the `pds`
+
connect via CLI
(see: )
+
----
jdb -attach localhost:15024
----
+
TIP: https://www.baeldung.com/java-application-remote-debugging[Java Application Remote Debugging] and https://www.tutorialspoint.com/jdb/jdb_basic_commands.htm[JDB - Basic Commands]
+
or connect via IDE (e. g. Eclipse IDE, VSCodium, Eclipse Theia, IntelliJ etc.).
+
TIP: https://www.eclipse.org/community/eclipse_newsletter/2017/june/article1.php[Debugging the Eclipse IDE for Java Developers]

== Build Image and Push to Registry

Build container images and push them to registry to run FindSecurityBugs+PDS on virtual machines, Kubernetes or any other distributed system.

=== Build Image

Build the container image.

==== Debian

. Using the default image:
+
----
./10-create-image.sh my.registry.example.org/sechub/pds_findsecuritybugs v0.1
----

. Using your own base image:
+
----
./10-create-image.sh my.registry.example.org/sechub/pds_findsecuritybugs v0.1 "my.registry.example.org/debian:12-slim"
----

=== Push Image to Registry

Push the container image to a registry.

* Push the version tag only
+
----
./20-push-image.sh my.registry.example.org/sechub/pds_findsecuritybugs v0.1
----

* Push the version and `latest` tags
+
----
./20-push-image.sh my.registry.example.org/sechub/pds_findsecuritybugs v0.1 yes
----

== Kubernetes

https://kubernetes.io/[Kubernetes] is an open-source container-orchestration system. This sections explains how to deploy and run FindSecurityBugs+PDS in Kubernetes.

=== Helm

https://helm.sh/[Helm] is a package manager for Kubernetes.

==== Requierments

* https://helm.sh/docs/intro/install/[Helm] installed
* `pds_findsecuritybugs` image pushed to registry

==== Installation

. Create a `myvalues.yaml` configuration file
+
A minimal example configuration file with one instance:
+
[source,yaml]
----
replicaCount: 1

image:
   registry: my.registry.example.org/sechub/pds_findsecuritybugs
   tag: latest

pds:
   startMode: localserver

users:
   admin:
      id: "admin"
      apiToken: "{noop}<my-admin-password>"
   technical:
      id: "techuser"
      apiToken: "{noop}<my-technical-password>"

storage:
    local:
        enabled: true

networkPolicy:
    enabled: true
    ingress:
    - from:
        - podSelector:
            matchLabels:
                name: sechub-server
        - podSelector:
            matchLabels:
                name: sechub-adminserver
----
+
An example configuration file with 3 replicas, postgresql and object storage:
+
[source,yaml]
----
replicaCount: 3

image:
   registry: my.registry.example.org/sechub/pds_findsecuritybugs
   tag: latest

pds:
   startMode: localserver
   keepContainerAliveAfterPDSCrashed: true

users:
   admin:
      id: "admin"
      apiToken: "{noop}<my-admin-password>"
   technical:
      id: "techuser"
      apiToken: "{noop}<my-technical-password>"


database:
    postgres:
        enabled: true
        connection: "jdbc:postgresql://<my-database-host>:<port>/<my-database>"
        username: "<username-for-my-database>"
        password: "<password-for-my-database>"

storage:
    local:
        enabled: false
    s3:
        enabled: true
        endpoint: "https://<my-s3-object-storage>:443"
        bucketname: "<my-bucket>"
        accesskey: "<my-accesskey>"
        secretkey: "<my-secretkey>"

networkPolicy:
    enabled: true
    ingress:
    - from:
        - podSelector:
            matchLabels:
                name: sechub-server
        - podSelector:
            matchLabels:
                name: sechub-adminserver
----
+
[TIP]
To generate passwords use `tr -dc A-Za-z0-9 </dev/urandom | head -c 18 ; echo ''`, `openssl rand -base64 15`, `apg -MSNCL -m 15 -x 20` or `shuf -zer -n20  {A..Z} {a..z} {0..9}`.

. Install helm package from file system
+
----
helm install --values myvalues.yaml pds-findsecuritybugs helm/pds-findsecuritybugs/
----
+
[TIP]
Use `helm --namespace <my-namespace> install…` to install the helm chart into another namespace in the Kubernetes cluster.

. List pods
+
----
kubectl get pods
NAME                             READY   STATUS    RESTARTS   AGE
pds-findsecuritybugs-57bdc89cd7-cvvfw         1/1     Running   0          1m43s
pds-findsecuritybugs-57bdc89cd7-cvvfw         1/1     Running   0          1m43s
pds-findsecuritybugs-57bdc89cd7-cvvfw         1/1     Running   0          3m
----

. Forward port of one of the pods to own machine
+
----
kubectl port-forward pds-findsecuritybugs-57bdc89cd7-cvvfw  8444:8444
----

. Scan as explained in <<scan>>.

==== Upgrade

In case, `my-values.yaml` was changed. Simply, use `helm upgrade` to update the deployment. `helm` will handle scaling up and down as well as changing the configuration.

----
helm upgrade --values my-values.yaml pds-findsecuritybugs helm/pds-findsecuritybugs/
----

==== Uninstall

. Helm list
+
----
helm list
NAME                	NAMESPACE     	REVISION	UPDATED                                 	STATUS  	CHART                          	APP VERSION
pds-findsecuritybugs	my-namespace	1       	2022-07-15 19:08:13.379212987 +0200 CEST	deployed	pds-findsecuritybugs-0.1.0     	0.30.0
----

. Helm uninstall
+
----
helm uninstall pds-gosec
----

=== Troubleshooting

* Access deployment events.
+
----
kubectl describe pod pds-findsecuritybugs-57bdc89cd7-cvvfw
…
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  1m    default-scheduler  Successfully assigned sechub-dev/pds-gosec-749fcb8d7f-jjqwn to kube-node01
  Normal  Pulling    54s   kubelet            Pulling image "my.registry.example.org/sechub/pds_gosec:v0.1"
  Normal  Pulled     40s   kubelet            Successfully pulled image "my.registry.example.org/sechub/pds_gosec:v0.1" in 13.815348799s
  Normal  Created    15s   kubelet            Created container pds-findsecuritybugs
  Normal  Started    10s   kubelet            Started container pds-findsecuritybugs
----

* Access container logs.
+
----
kubectl logs pds-findsecuritybugs-57bdc89cd7-cvvfw

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.7)

2022-07-15 17:08:18.883  INFO 6 --- [           main] m.s.p.ProductDelegationServerApplication : Starting ProductDelegationServerApplication using Java 17.0.3 on pds-findsecuritybugs-57bdc89cd7-cvvfw with PID 6 (/pds/sechub-pds-0.30.0.jar started by pds in /workspace)
2022-07-15 17:08:18.887  INFO 6 --- [           main] m.s.p.ProductDelegationServerApplication : The following 2 profiles are active: "pds_localserver", "pds_postgres"
2022-07-15 17:08:20.870  WARN 6 --- [           main] o.apache.tomcat.util.net.SSLHostConfig   : The protocol [TLSv1.3] was added to the list of protocols on the SSLHostConfig named [_default_]. Check if a +/- prefix is missing.
2022-07-15 17:08:20.943  INFO 6 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-07-15 17:08:20.944  INFO 6 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.62]
2022-07-15 17:08:21.041  INFO 6 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-07-15 17:08:21.229  INFO 6 --- [           main] c.m.sechub.pds.PDSFlywayFactory          : Start flyway repair
2022-07-15 17:08:21.237  INFO 6 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2022-07-15 17:08:21.409  INFO 6 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2022-07-15 17:08:21.500  INFO 6 --- [           main] c.m.sechub.pds.PDSFlywayFactory          : Flyway repair done for flyway version:8.0.5
2022-07-15 17:08:24.127  INFO 6 --- [           main] c.m.s.p.storage.PDSMultiStorageService   : Created storage factory: AwsS3JobStorageFactory
2022-07-15 17:08:24.140  INFO 6 --- [           main] c.m.s.pds.batch.PDSBatchTriggerService   : Scheduler service created with 100 millisecondss initial delay and 500 millisecondss as fixed delay
2022-07-15 17:08:24.386  INFO 6 --- [           main] c.m.s.p.m.PDSHeartBeatTriggerService     : Heartbeat service created with 1000 millisecondss initial delay and 60000 millisecondss as fixed delay
2022-07-15 17:08:25.212  INFO 6 --- [           main] m.s.p.ProductDelegationServerApplication : Started ProductDelegationServerApplication in 7.204 seconds (JVM running for 8.049)
2022-07-15 17:08:25.488  INFO 6 --- [0.0-8444-exec-4] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-07-15 17:08:26.246  INFO 6 --- [   scheduling-1] c.m.s.p.m.PDSHeartBeatTriggerService     : Heartbeat will be initialized
2022-07-15 17:08:26.246  INFO 6 --- [   scheduling-1] c.m.s.p.m.PDSHeartBeatTriggerService     : Create new server hearbeat
2022-07-15 17:08:26.296  INFO 6 --- [   scheduling-1] c.m.s.p.m.PDSHeartBeatTriggerService     : heartbeat update - serverid:FIND_SECURITY_BUGS_CLUSTER, heartbeatuuid:abb79881-3788-40dd-afe0-3882aea336fb, cluster-member-data:{"hostname":"pds-findsecuritybugs-57bdc89cd7-cvvfw","ip":"192.168.130.236","port":8444,"heartBeatTimestamp":"2022-07-15T17:08:26.247698145","executionState":{"queueMax":50,"jobsInQueue":0,"entries":[]}}
2022-07-15 17:08:30.238  INFO 6 --- [   scheduling-1] p.a.DefaultPDSAutoCleanupResultInspector : Auto cleanup, variant 'pds-job' deleted 0 entries older than 2 days. Used timestamp '2022-07-13T17:08:30.235382833' inside:PDSAutoCleanupService
----
