# SPDX-License-Identifier: MIT

version: "3"
services:
    pds-scancode:
        build:
            args:
                - BASE_IMAGE=debian:11-slim
            context: docker/
            dockerfile: ScanCode-Debian.dockerfile
        container_name: pds-scancode
        hostname: pds-scancode
        volumes:
            - ./docker/scripts:/scripts
        env_file:
            - .env
        networks:
            - "sechub"

networks:
    sechub:
        external: true
        name: "sechub"
