# SPDX-License-Identifier: MIT

version: "3"
services:
    pds-scancode:
        build:
            args:
                - BASE_IMAGE=${BASE_IMAGE}
                - SCANCODE_VERSION=${SCANCODE_VERSION}
                - SPDX_TOOL_VERSION=${SPDX_TOOL_VERSION}
            context: docker/
            dockerfile: Scancode-Debian.dockerfile
        container_name: pds-scancode
        hostname: pds-scancode
        volumes:
            - ./docker/scripts:/pds/scripts
        env_file:
            - .env
            - .env-single
        networks:
            - "sechub"

networks:
    sechub:
        external: true
        name: "sechub"
