# SPDX-License-Identifier: MIT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 49%
  selector:
    matchLabels:
      name: {{ .Values.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
{{- if .Values.templateMetadataAnnotations }}
      annotations:
        {{ .Values.templateMetadataAnnotations | indent 8 | trim }}
{{- end }}
    spec:
      securityContext:
        runAsUser: 4242  # uid of the application user. (should be same as in the Dockerfile)
        runAsGroup: 4242 # gid of the application group. (should be same as in the Dockerfile)
        fsGroup: 4242    # This gid has write access to the mounted volumes.
      volumes:
{{- if ne .Values.webserver.ssl.keystoreAlias "undefined" }}
        - name: secret-webserver-ssl-volume
          secret:
            secretName: secret-webserver-ssl
{{- end }}
{{- if .Values.go_mmproxy.enabled }}
      initContainers:
      - name: setup
        image: "{{ .Values.go_mmproxy.image }}"
        command:
        - "/bin/sh"
        - "-cx"
        args:
        - |
          /sbin/ip rule add from 127.0.0.1/8 iif lo table 123
          /sbin/ip route add local 0.0.0.0/0 dev lo table 123
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
{{- end }}
      containers:
{{- if .Values.go_mmproxy.enabled }}
      # go-mmproxy sidecar container
      - name: go-mmproxy
        image: "{{ .Values.go_mmproxy.image }}"
        ports:
        - containerPort: 8080
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        args:
        - "-v=0"           # loglevel 0 - no logging ; 1 - log errors ; 2 - log all state changes
        - "-l"             # listen
        - "0.0.0.0:8080"   # on port 8080
        - "-4"             # tcp v4
        - "127.0.0.1:4443" # forward to SecHub Web Server container (localhost port 4443)
{{- end }}
      # SecHub webserver container
      - name: sechub-web-server
        image: {{ .Values.image }}
        resources:
          # min container memory
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
          # max container memory
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
        ports:
        - name: sechub-web-server
          containerPort: 4443
        # startupProbe:
        #   httpGet:
        #     scheme: HTTPS
        #     path: /api/anonymous/check/alive
        #     port: sechub-web-server
        #   failureThreshold: 24
        #   periodSeconds: 5
        #   successThreshold: 1
        #   timeoutSeconds: 1
        #   initialDelaySeconds: 5
        # livenessProbe:
        #   httpGet:
        #     scheme: HTTPS
        #     path: /api/anonymous/check/alive
        #     port: sechub-web-server
        #   failureThreshold: 3
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 3
        volumeMounts:
{{- if ne .Values.webserver.ssl.keystoreAlias "undefined" }}
          - mountPath: /sechub-web-server/secrets/secret-ssl
            name: secret-webserver-ssl-volume
{{- end }}
        env:
        # Server start mode
        - name: WEB_SERVER_START_MODE
          value: "{{ .Values.webserver.startMode }}"
        # Spring profiles definition
        - name: SPRING_PROFILES_ACTIVE
          value: "{{ .Values.webserver.spring.profiles }}"
{{- if .Values.env }}
        # ------------------------------------------------------------------------#
        # Scope: Additional environment variables for the SecHub web-ui container
        # ----------------------------------------------------------------------- #
        {{ .Values.env | indent 8 | trim }}
{{- end }}
{{- if .Values.deploymentComment }}
        # Setting DEPLOYMENT_COMMENT to a different value every time forces k8s to spin up a new container.
        # This way, you can force deployments e.g. when secrets have changed.
        - name: DEPLOYMENT_COMMENT
          value: "{{ .Values.deploymentComment }}"
{{- end }}
{{- if .Values.webserver.loggingType }}
        - name: LOGGING_TYPE
          value: "{{ .Values.webserver.loggingType }}"
{{- end }}
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# + Connection to SecHub server
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        - name: SECHUB_SERVER_URL
          value: "{{ .Values.webserver.sechubConnection.url }}"
        - name: WEBSERVER_SECHUB_TRUST_ALL_CERTIFICATES
{{- if .Values.webserver.sechubConnection.trustAllCertificates }}
          value: "true"
{{- else }}
          value: "false"
{{- end }}
        - name: SECHUB_USERID
          valueFrom:
            secretKeyRef:
               name: secret-webserver-connect
               key: sechub_userid
        - name: SECHUB_APITOKEN
          valueFrom:
            secretKeyRef:
               name: secret-webserver-connect
               key: sechub_apitoken
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# + SSL certificate
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        - name: SECHUB_WEBSERVER_SSL_KEYSTORE_TYPE
          value: "PKCS12"
        - name: SECHUB_WEBSERVER_SSL_KEYSTORE_LOCATION
          value: "/sechub-web-server/{{ .Values.webserver.ssl.keystoreAlias }}.p12"
        - name: SECHUB_WEBSERVER_SSL_KEYSTORE_ALIAS
          value: "{{ .Values.webserver.ssl.keystoreAlias }}"
        - name: SECHUB_WEBSERVER_SSL_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
               name: secret-webserver-ssl
               key: keystore_password
{{- if .Values.webserver.spring.embeddedTomcat.logging.enabled }}
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# + Scope: embedded Tomcat
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        # Logging to stdout:
        - name: SERVER_TOMCAT_ACCESSLOG_ENABLED
          value: "{{ .Values.webserver.spring.embeddedTomcat.logging.enabled }}"
        - name: SERVER_TOMCAT_ACCESSLOG_DIRECTORY
          value: "/dev"
        - name: SERVER_TOMCAT_ACCESSLOG_PREFIX
          value: "stdout"
        - name: SERVER_TOMCAT_ACCESSLOG_BUFFERED
          value: "false"
        - name: SERVER_TOMCAT_ACCESSLOG_SUFFIX
          value: ""
        - name: SERVER_TOMCAT_ACCESSLOG_FILE_DATE_FORMAT
          value: ""
        - name: SERVER_TOMCAT_ACCESSLOG_PATTERN
          value: "{{ .Values.webserver.spring.embeddedTomcat.logging.accessLogFormat }}"
{{- end }}
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# + Scope: development
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        - name: JAVA_ENABLE_DEBUG
          value: "{{ .Values.webserver.development.javaDebug | toString }}"
        - name: KEEP_CONTAINER_ALIVE_AFTER_CRASH
          value: "{{ .Values.webserver.development.keepContainerAliveAfterApplicationCrash | toString }}"
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# + end of environment variables section
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ .Values.imagePullSecrets | indent 8 | trim }}
{{- end }}
