==== Product delegation server

===== General
There are many open source clients available having no server component inside so lacking:

- REST access
- queing
- status requests
- scalable
- … more 

So when we want to adapt them in SecHub style (the product does the work and we ask for result) we 
need to provide a `ProductDelegationServer` (in short form `PDS`).

`PDS` is

- a spring boot application with using network DB (like done in SecHub itself, so we have t his
  as a shared kernel and so have synchronization base to do clustering very easy)
- provides REST access
- a very simple auth mechanism at the beginning (just one user, basic auth via TLS, credentials by ENV entries on startup)
- provides jobs, queing
- can execute single files (e.g. a bash script) 
- has got a common simple way for configuration 

===== Big picture
plantuml::diagrams/diagram_concept_product_delgation_server_bigpicture.puml[]

===== Executors and Adapters
====== Executors
With PDS there is a default REST API wavailable, for different scanTypyes there will
be dedicated PDSExecutors (eg. PDSWebScanExecutor, PDSInfraScanExecutor, etc., etc.)

====== Adapters
The Adapter will always be the same, but filled with other necessary parameters.

NOTE: So there will be no need to write any adapter or executor when using PDS! 


===== Howto integrate a CLI product in future

====== Security Product Server
Having new security product XYZ but being a command line tool, we 

- create a config file and fill with necessary data
- start wanted amount of `ProductDelegationServer` instances with dedicated configuration setup to have a clustered, server ready execution of CLI security products.

====== SecHub Server Development
Nothing special to do, will be provided by default implementation

====== SecHub Server Configuration
With #148 we will provide possibility to add/remove dedicated executors (with dedicated verions)
- doing this a PDS executor can be choosen and configured.

====== Environment entries for keys


==== Future concepts
At configuration phase/wizard, there will be a interchange with PDS server

Every executor will have possibility to "say" what the optional and mandatory keys are.
( see https://github.com/Daimler/sechub/issues/278 ) 
Also there should be a test option inside (developer) admin UI to check if current configuration for 
PDS is still valid - just check all parameters are defined, maybe later a real test could be implemented
for PDS servers - so products could check if they are configured correctly? 
