==== Product delegation server

===== General
There are many open source clients available having no server component inside which can do
- REST access
- queing
- status requests
- scalable
- … more 

So when we want to adapt them in SecHub style (the product does the work and we ask for result) we need provide a `ProductDelegationServer`
- a spring boot application with network DB (same to SecHub itself, so we can do easily clustering)
- provides REST access
- a very simple auth mechanism at the beginning (just one user, basic auth via TLS, credentials by ENV entries on startup)
- provides jobs, queing
- can execute single files (e.g. a bash script) 
- has got a common simple way for configuration

We will also provide a `AbstractProductDelegationServerAdapter` which does only not know the PRODUCT_ID but know how to communicate with `ProductDelegationServer` instances.

===== Big picture
plantuml::diagrams/diagram_concept_product_delgation_server_bigpicture.puml[]

===== REST API 
====== Create JOB
[source,bash]
----
https://${baseURL}/api/job/create [POST]
----
Does contain configuration data for job execution as JSON in a very simple key value style:

[source,json]
----
include::product_delegation_job_config_example1.json[]
----
<1> Represents the key, will be provided as argument `${sechub.test.key.1}` but also as `SECHUB_TEST_KEY_1` environment entry on process startup
    so its up to the implementers if this is something that should not be shown in process tree... +
    Only `[a-z\.0-9]` is allowed. `.` will be converted always to `_` for the environment variables (spirng boot style)
<2> Just the value. Must be always a string


====== Upload data
[source,bash]
----
https://${baseURL}/api/job/${jobUUID}/upload [POST]
----

Uploaded data must be automatically destroyed after job has been done.
This avoids file system freezes...

====== Mark JOB ready to start
[source,bash]
----
https://${baseURL}/api/job/${jobUUID}/mark-ready-to-start [POST]
----


====== Fetch JOB status
[source,bash]
----
https://${baseURL}/api/job/${jobUUID}/status [GET]
----


====== Fetch JOB result
[source,bash]
----
https://${baseURL}/api/job/${jobUUID}/result [GET]
----

====== Cancel JOB
[source,bash]
----
https://${baseURL}/api/job/${jobUUID}/cancel [POST]
----

TIP: This should kill the process hard!

===== Configuration

====== Server
Server configuration will be done by a JSON file.

We will provide different target execution scripts for dedicated execution types:
[source,json]
----
include::product_delegation_server_config_example1.json[]
----
<1> identifier, which will be used at job configuration time. Defines what will be executed
<2> command what will be executed. Supports variables
<3> user id of an administrator
<4> encrypted password (spring boot style - e.g. `{noop}unencrypted`, `{bcrypt}crypted` ...)

====== Job
JOB configuration is done by REST API call (create JOB)  

===== Howto integrate a CLI product in future

====== Security Product Server
Having new security product XYZ but being a command line tool, we 
- create a config file and fill with necessary data
- start wanted amount of `ProductDelegationServer` instances with dedicated configuration setup to have a clustered, server ready execution of CLI security products.

====== SecHub Server Development
Write a {sechub} adapter class which extends `AbstractProductDelegationServerAdapter`. Provide necessary config data on start time

====== SecHub Server Operations
Configure to use the adapter on startup, which will be supported by #148


===== TODO

- What about environment entry injection e.g. all with `SECHUB_.*` could be available inside the jobs
- What about 3rd-party authentication ?