# SPDX-License-Identifier: MIT

name: sechub falsePositives
description: 'a GitHub actions wrapper for SecHub security falsePositives actions.'
inputs:
  config-path:
    description: |
      Path to sechub.json for manual configuration.
      If no value is set the input parameters will be used to create it.
    required: false
  url:
    description: 'SecHub server URL'
    required: false
  api-token:
    description: 'SecHub API Token'
    required: false
  user:
    description: 'SecHub userid'
    required: false
  project-name:
    description: 'SecHub project name'
    required: false
  version:
    description: 'Which version of the SecHub'
    required: false
    default: '1.4.0'
  debug:
    description: 'SecHub debug output on/off'
    required: false
  file:
    description: 'The file from where to read the false positives'
    required: false
  action:
    description: |
      The type of the false positives action to be performed.
      Possible values are:
      - 'DEFINE' - will execute the defineFalsePositives action
      - 'MARK' - will execute the markFalsePositives action
      - 'UNMARK' - will execute the unmarkFalsePositives action
    required: true

runs:
  using: 'node16'
  main: './dist/index.js'
