// SPDX-License-Identifier: MIT
[[section-system-scope-and-context]]
== System Scope and Context
=== About
// for details see https://docs.arc42.org/section-3/
==== Content

System scope and context - as the name suggests - delimits your system (i.e. your scope)
from all its communication partners (neighboring systems and users, i.e. the context of
your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs)
from the technical context (channels, protocols, hardware).

==== Motivation
The domain interfaces and technical interfaces to communication partners
are among your system’s most critical aspects. Make sure that you completely understand them.

=== Business Context

==== Overview
plantuml::diagrams/diagram_business_context_overview.plantuml[format=svg, title="Overview business context"]

=== Technical Context

==== Initial concept
The initial design of SecHub was to directly communicate with any product by a product adapter:

plantuml::diagrams/diagram_technical_context_overview.plantuml[format=svg, title="Overview technical context (general)"]


==== PDS (Product delgation server)
This approach had some cave eats: For every product it was necessary to write java code (adapter, executor etc.).
Also it was only possible to integrate 3rd party products having a REST or SOAP API. But it was 
not possible to integrate tools which did only provide a command line interface.
 
To tackle this, the PDS (product delegation server) was introduced but keeping the design as before:

plantuml::diagrams/diagram_technical_context_overview_with_pds.plantuml[format=svg, title="Overview technical context (with PDS)"]

The PDS product executors are specialized for different scan types. But they use all the same
PDS adapter (PDS is here the product).

[TIP]
====
At https://mercedes-benz.github.io/sechub/latest/sechub-product-delegation-server.html you can
find more details about PDS.
====

==== Product executors
A product executor executes a product and knows information about SecHub details and the scan type
which is provided by the product.

==== Product adapter
A product adapter is only a technical vehicle to communicate with a 3rd party product.
The adapter does not know about SecHub infrastructure but only knows how to start, stop and cancel
a product and how to retrieve the output.

==== Scan types

We provide following scan types

- `codeScan` (SAST) +
  Does scan code from binaries or source code - depending on used product 

- `iacScan` (IaC) +
  Scans infrastructure as code, similar to `codeScan` but specialized and
  can only scan sources

- `infraScan` (Infrastructure scan) +
  Penetrates and tests infrastructure at runtime

- `licenseScan` (License scan) +
  Checks for license issues in binaries or source code  - depending on used product

- `secretScan` (Secret scan) +
  Checks or secrets inside source code or binaries - depending on used product
 
- Web scan (DAST) +
  Penetrates and tests a web application at runtime

The different solutions can be found at
https://github.com/mercedes-benz/sechub/tree/develop/sechub-pds-solutions

