// SPDX-License-Identifier: MIT
[[section-system-scope-and-context]]
== System Scope and Context
=== About
// for details see https://docs.arc42.org/section-3/
==== Content

System scope and context - as the name suggests - delimits your system (i.e. your scope)
from all its communication partners (neighboring systems and users, i.e. the context of
your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs)
from the technical context (channels, protocols, hardware).

==== Motivation
The domain interfaces and technical interfaces to communication partners
are among your system’s most critical aspects. Make sure that you completely understand them.

=== Business Context

==== Overview
plantuml::diagrams/diagram_business_context_overview.plantuml[format=svg, title="Overview business context"]

=== Technical Context
plantuml::diagrams/diagram_technical_context_overview.plantuml[format=svg, title="Overview business context"]

==== Web scanner
A scanner used for automated penetration testing on given sites

We support currently:

- Netsparker

==== Code scanner
A scanner used for automated static code analysis

We support currently:

- Checkmarx

==== Infrastructure scanner
A scanner used for automated penetration testing on given infrastructure

We support currently:

- Nessus

WARNING: We got the problem that Nessus has terminated their REST API and only supports a REST API when ordering
         another product. So currently it's difficulat to support NESSUS directly.


