// SPDX-License-Identifier: MIT
[[section-glossary]]
== Glossary

[options="header"]
|===
| Term           | Definition
| Adapter        | In scope of {sechub} the term "adapter" is used for product adapters. They represent +
                 a communication object which does know how to start/restart a security product and 
                 fetch the result. SecHub and also some wrapper applications in {pds}-solutions do use 
                 the adapters for communication and to mock products. The adapter does not 
| Executor       | An executor (or product executor) handles the complete communication with a product via an adapter.
                 The executor is repsonsible for resilience and writes the results from adapter into SecHub database.
| K8s            |  https://kubernetes.io/[Kubernetes], also known as K8s, is an open-source system for automating deployment, 
                 scaling, and management of containerized applications.
| Helm           | "...https://helm.sh/[Helm] is the best way to find, share, and use software built for Kubernetes. ..."
| Mapping        | The mapping feature inside {sechub} is a generic pattern replacement approach. Via a REST API
                 administrators can define the mappings with regular expression patterns and dedicate values/
                 replacements. +
                 + 
                 Inside {sechub} or {pds} the mappings can be used - e.g. to configure a security 
                 product dependently on a project name.
| {pds}          | Is an acronym for "Product delegation server". This kind of server represents a 
                 very easy way to integrate any security product into {sechub} - no matter if it is 
                 a command line tool or has REST API or anything else. +
                 +
                 It has a standard
                 REST API which is wellknown by {sechub} and can be used in clusters or as standalone
                 server. 
                 +
                 This server is also maintained by {sechub} maintainers.
| {pds}-Solution | {pds} is a very generic server which can execute anything. The `PDS-Solutions` are
                 full working `integrations which run "out-of-the-box". Every solution can 
                 be run a preconfigured PDS either as a single Docker instance, as a Docker compose 
                 cluster or even by https://kubernetes.io/[K8s] via existing https://helm.sh/[Helm] scripts.
                 The PDS solutions are also maintained by {sechub} maintainers. +
                 + 
                 You can find the solutions at {projectSite}/tree/develop/sechub-pds-solutions
| {sechub}       | {sechub} itself - it is an acronym for "Security Hub" and represents a security 
                 orchestration tool.  +
                 +
                 It is free and open source and can be found at {projectSite}.
                 The documentation is available at {webPage}. 
| {sechub} configuration file     
                 | Is the JSON configuration file used by a user to start a new {sechub} job.
| Wrapper        | A wrapper or "wrapper application" is a standalone application used inside a {pds}-solution
                 when it comes to a more sophisticated way of product communication.
                 Normally such an application is written in Java and uses some common {sechub}
                 libraries and has more logic inside. Example are the Checkmarx wrapper and 
                 the OWASP Zap wrapper.                                      
                   
|===
