# SPDX-License-Identifier: MIT

version: "3"
services:
  pds-owaspzap:
    build:
      args:
        - BASE_IMAGE=${BASE_IMAGE}
        - INFRALIGHT_WRAPPER_VERSION=${INFRALIGHT_WRAPPER_VERSION}
        - INFRALIGHT_VERSION=${INFRALIGHT_VERSION}
      context: docker/
      dockerfile: Owasp-Zap-Debian.dockerfile
    container_name: pds-owaspzap
    env_file:
      - .env
    ports:
      - "127.0.0.1:8444:8444"
      - "127.0.0.1:15024:15024"
    networks:
      - "sechub"
    volumes:
      - ./docker/scripts:/pds/scripts

networks:
  sechub:
    name: "sechub"
