#!/bin/bash 

# This script build full documentation and also creates all precondition parts
# So users can checkout from github and call this.
# 
# You can either call this script directly or use gradle : "./gradlew buildDoc" from
# repository root folder. 
# 

echo "********************************************************************"
echo "* Build software artifacts - necessary as precondition" 
echo "********************************************************************"
./gradlew ensureLocalhostCertificate build buildGo -x :sechub-integrationtest:test
 
echo "********************************************************************"
echo "* Collect runtime information about some started artefacts" 
echo "********************************************************************"
./gradlew integrationtest

echo "********************************************************************"
echo "* Build documents + pages by using static and former collected info" 
echo "********************************************************************"
./gradlew documentation-with-pages
