// SPDX-License-Identifier: MIT
[[section-infrastructure-setup-localdevelopment]]
=== Local development

This section describes the start on local machine _(development/presentation)_.

Only SecHub itself is described. The products must be either running and well
configured, or profile `mocked_products` must be active.

See product infrastructure sections for details.

==== Java launch configuration setup
Because it takes too much time - even when security products are configured with
test profiles (for testing persistence, transaction rollback etc.) a
`mocked_products` profile was  introduced which can be used.
ifdef::techdoc[]
See <<section-sechub-spring-profiles,Spring Profiles>>.
endif::[]


It does use normal product executors but injects mocked adapters
(e.g. `MockedNessusAdapter`, `MockedNetsparkerAdapter`, ..)
which do not really communicate with the real security products but return
instead preconfigured values (which where recorded from real communications).

Startup is done by using active spring profile `mocked_products`.
Some mocks have special options to change their behaviour at runtime.

ifdef::techdoc[]
Please refer to <<sechub-mock-options,Mock options>> for details.
endif::[]

===== Launch configuration for development
====== Custom configuration files
If you want to have your own custom configuration do following steps:

. Create a file `sechub-server/src/main/resources/application-local.${user}.yml`.
  `${user}` is the value of your system user name (e.g. `application-local.johndoe.yml`)

. Use the spring profile `local` inside your launch configuration (it delegates to the file)

TIP: All `application-local.${user}.yml` files are ignored by git. So developers don't have to 
     be aware about committing accidently changes.

====== DEV profile
With activated `DEV` spring profile it is possible to define an api-token programmatically
and it will not be generated by {sechub} server on startup.

It also enables debug logging and includes the `localserver` profile which 
automatically uses the generated local server certificates.

====== Example for DEV profile combined with custom configuration file
include::./../../shared/launchconfig/launchconfig_start_dev_server.adoc[]



===== Launch configuration for integration tests
include::./../../shared/launchconfig/launchconfig_start_integrationtest_server.adoc[]

===== Launch configurationfor production
ifdef::techdoc[]
TIP: To run a local server like in production please refer <<section-howto-start-localserver-like-in-production,How to start localserver like in production>>
endif::[]

include::./../../shared/launchconfig/launchconfig_start_prod_server.adoc[]
