# SPDX-License-Identifier: MIT

{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: {{ .Chart.Name }}-policy
spec:
    podSelector:
        matchLabels:
            app: {{ .Chart.Name }}

{{- if .Values.networkPolicy.ingress }}
    ingress:
{{ .Values.networkPolicy.ingress | toYaml | indent 4 }}
{{- end }}

{{- end }}
