// SPDX-License-Identifier: MIT
=== Deployment

==== Database

{sechub} requires a PostgreSQL DB, Version > 10.x

===== Plain server
In this scenario you would configure a database server available from {sechub}.

_For example: Just install PostgreSQL DB server on same machine as your server._

===== Kubernetes
Here you must provide a PostgreSQL DB server deployment *(one POD only)*,
define a network policy, services, endpoints etc. etc.

[IMPORTANT]
====
Be aware to mount *only ONE pod* - the database is *shared by all {sechub} server
PODs* _(means this is a shared kernel / bottle neck but necessary)_
====

[TIP]
====
Think about an automated database backup - no matter which is your choosen
installation variant...
====

==== File upload storage

{sechub} requires a file system folder where source scan uploads can be transferred to.

[IMPORTANT]
====
In a clustered environment like kubernetes the storage must be accessible by
every cluster member!
====

===== Plain server
In this scenario you would just either reuse {sechub} server file system or
define a network share available form server.

===== Kubernetes
Here you must provide a PostgreSQL DB server deployment *(one POD only)*,
define a network policy, services, endpoints etc.

[IMPORTANT]
====
Be aware to mount *only ONE pod* - the database is *shared by all {sechub} server
PODs* _(means this is a shared kernel / bottle neck but necessary)_
====

==== Server Application

{sechub} server is a written in `Java` and needs at least `{required_JDK}`.

You can configure {sechub} server by system properties or also by  environment
variables.

Next blocks describe necessary system properties and their ENV pendants.

===== Mandatory configuration

include::../../gen/gen_javalaunchexample.adoc[]

include::../../shared/hint_admin_access_profile.adoc[]

====== Storage configuration
include::../../shared/storage_configuration.adoc[]

===== Plain server

To start the server by executing

`java ${systemProperties} -jar sechub-server-x.y.z.jar`

Where `${systemProperties}` is a place holder for Java system properties or
you use environment entries (configuration is explained in common chapter before)

====== Logging

{sechub} uses per default logging to stdout. So you have to change this behaviour
for your server when you want to change log output format, location etc.

Please refer spring boot documentation for logging:
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html

===== Docker
The public Docker image can be found at https://github.com/mercedes-benz/sechub/pkgs/container/sechub%2Fsechub-server

The {sechub} server can be simply run like this
[source,bash]
----
docker run ghcr.io/mercedes-benz/sechub/sechub-server
----


===== Kubernetes
We provide a Helm chart for the container image above: https://github.com/mercedes-benz/sechub/pkgs/container/sechub%2Fhelm-charts%2Fsechub-server

Same as before described for plain server, but you should use a copy of the `values.yaml` and adapt it to your needs.

[source,bash]
----
helm pull oci://ghcr.io/mercedes-benz/sechub/helm-charts/sechub-server
tar zxf sechub-server-*.tgz
cp sechub-server/values.yaml sechub-server.yaml
# edit "sechub-server.yaml" file and adapt settings

# Deploy SecHub server to your Kubernetes:
helm install sechub-server sechub-server/ -f ./sechub-server.yaml
----
