// SPDX-License-Identifier: MIT
[[section-pds-configuration]]
=== Configuration

include::../shared/pds_options.adoc[]

=== Tech user credentials

Either use system properties

----
sechub.pds.techuser.userid
sechub.pds.techuser.apitoken
----
or env entries
----
SECHUB_PDS_TECHUSER_USERID
SECHUB_PDS_TECHUSER_APITOKEN
----
to define user credentisals. For apitoken please define encrypted password in spring boot
style - e.g. `{noop}unencrypted`, `{bcrypt}crypted` ...

=== Admin credentials

Either use system properties

----
sechub.pds.admin.userid
sechub.pds.admin.apitoken
----
or env entries
----
SECHUB_PDS_ADMIN_USERID
SECHUB_PDS_ADMIN_APITOKEN
----
to define admin credentisals. For apitoken please define encrypted password in spring boot
style - e.g. `{noop}unencrypted`, `{bcrypt}crypted` ...


=== Workspace parent folder
With `-Dsechub.pds.workspace.rootfolder` or using environment variable `SECHUB_PDS_WORKSPACE_ROOTFOLDER`
workspace location can be defined

[[section-pds-server-config-file]]
=== Server configuration file
PDS reads configuration JSON file on startup.

*Location*

With `-Dsechub.pds.config.file=...` or using environment variable `SECHUB_PDS_CONFIG_FILE`
its is possible to set config file path ( when not defined fallback is `./pds-config.json`)

     
* `product-id` +
     Must be *unique* for this product. Allowed characters are [a-zA-Z0-9_]. Maximum length:30. If it's not inside SERECO listed it must provide general sereco report format from #283.
     

[source,json]
[[section-pds-server-example-config-file]]
----
include::product_delegation_server_config_example1.json[]
----
[[section-pds-server-describe-config-file]]
<1> `serverId` is a *unique* identifier, which will be used determine a cluster /server. will be used inside logs and
    also to share common database and divide different pds states etc. +
    Allowed characters are [a-zA-Z0-9_]. Maximum length:30  +
    (e.g `FIND_SECURITY_BUGS_CLUSTER` when providing a PDS server for find-security-bugs). 
    This is *important* ! Do NOT mix up different PDS clusters with same ID. 

<2> product `id` is a unique identifier, which will be used at job configuration time. 
    Defines what will be executed and is also the identifier for SERECO to check for dedicated
    report handling +
    Allowed characters are [a-zA-Z0-9_]. Maximum length:30

<3> `path` defines what command / script will be executed.

<4> `scanType` can be either
 - codeScan
 - infraScan
 - webScan

<5> `description` is a free text description

<6> `parameters` area, here we can define optional and mandatory parameters. Those parameters will be available
    in executed processes by environment variables. +
    All other given job parameters will be IGNORED by server - reason: avoid unwanted changes on system environment variables from caller side 

<7> `mandatory` parameters - server will not accept jobs without these parameters

<8> a `key`, will be transformed to ENV variable. In the given example `product1.qualititycheck.enabled` will be available in execution process 
    as environment variable `PRODUCT1_QUALITYCHECK_ENABLED`.
    the `value`, will be set by {sechub} job call and available in former described ENV entry at execution time.
    {sechub} will 
<9> a 'description' of the 'key'. Should contain information 

<10> optional parameters

<11> defines if `PDS` will automatically extract archive files - default is `true`. When `true` the content
   of `zip` source files will be available inside `$PDS_JOB_EXTRACTED_SOURCES_FOLDER`, `tar` files containing binaries can be found at `$PDS_JOB_EXTRACTED_BINARIES_FOLDER`.
   The extraction will automatically filter and transform archive content as described at <<data-structure-tar-and-zip-files,data structure definition>>.
   Also the environment variables `$PDS_JOB_HAS_EXTRACTED_SOURCES` and `$PDS_JOB_HAS_EXTRACTED_BINARIES` are automatically defined. 
   
NOTE: When no {sechub} configuration model is defined for the `PDS` job, the transformation and filtering described at <11> will accept all binaries and all sources which are uploaded.
      But this can happen only when PDS is used without SecHub - normally only for testing PDS solutions.  
   
   
=== Launcher scripts

==== Generated variables

[options="header",cols="1,2"]
|===
|Variable name                      |Description   
//-------------------------------------------------------------------------------------------------
|PDS_JOB_WORKSPACE_LOCATION         | The workspace job root location 
|PDS_JOB_RESULT_FILE                | The absolute path to the result file _(this file contains security findings)_.
|PDS_JOB_UUID                       | The UUID of the current running PDS job.
[[table-link-pds-launcher-script-variable-messages]]
|PDS_JOB_USER_MESSAGES_FOLDER       a| The absolute path to the user <<section-config-messaging,messages folder>>.

Every text file which is found inside this folder will be returned to user inside reports and status.

There is a <<example-shared-messaging,snippet for bash>> to create unique names.

 
When a file starts with
 
- `ERROR_` the user message will be of type `error`.
- `WARNING_` the user message will be of type `warning`.
- None of the former ones, the corresponding SecHubMessage will be of type `info`.

The files must be simple text files and can contain multiple lines.

[TIP]
====
It is necessary to use always unique names for new user messages - because otherwise you
would overwrite the old ones. The <<section-shared-concepts-product-message-pds-dataflow,PDS message data flow>> describes
how the data is gathered.
====


|PDS_JOB_SOURCECODE_ZIP_FILE        | The absolute path to the uploaded "sourcecode.zip" file 
|PDS_JOB_EXTRACTED_SOURCES_FOLDER   | When auto extracting is enabled (default) the uploaded source code is extracted to this folder 
|PDS_JOB_EXTRACTED_BINARIES_FOLDER  | When auto extracting is enabled (default) the uploaded binaries are extracted to this folder 
|PDS_SCAN_TARGET_URL                | Target URL for current scan (e.g webscan). Will not be set in all scan types. E.g. for a code scan this environemnt variable will not be available  
|PDS_SCAN_CONFIGURATION             | Contains the SecHub configuration as JSON _(but reduced to current scan type, so e.g. a web scan will have no code scan configuration data available)_ +
                                      + 
                                      For details about the exact format please look into https://mercedes-benz.github.io/sechub/latest/sechub-client.html[SecHub client documentation] . If you are using 
                                      a Java wrapper application inside your PDS scripts, those can use the `sechub-commons-model` java library which contains `SecHubScanConfiguration.java` 
                                      _(Usage is described in JavaDoc)_.
|SECHUB_JOB_UUID                    | The corresponding {sechub} job UUID 
|PDS_SCAN_TARGET_TYPE 				| The network target type of the target URL. Possible values are: INTERNET, INTRANET. The network target type is injected by SecHub automatically. 
									  It does not need to be specified explicitly in the PDS Configuration file.
|===

==== Parameter variables
The parameters described inside the <<section-pds-server-example-config-file,example configuration>> are defined at {sechub} side in
Product executor configurations or automatically generated. +
At execution time these parameters are sent by {sechub} to {pds}. Some are also available inside launcher scripts as environment variables.


It is possible define custom parameters for {pds} solutions in the <<section-pds-server-example-config-file, configuration>> file.
Mandatory parts are always present, optional ones can be empty.

We have following standard parameters:

include::../gen/gen_pds_executor_config_parameters.adoc[]



==== File locations

===== Upload
`$PDS_JOB_WORKSPACE_LOCATION/upload/`

Automatically unzipped content is available inside +
`$PDS_JOB_WORKSPACE_LOCATION/upload/unzipped`

===== Output

Following files are reserved

- system-err.log _(created automatically by PDS)_ +
  `$PDS_JOB_WORKSPACE_LOCATION/output/system-err.log`

- `system-out.log _(created automatically by PDS)_+
   $PDS_JOB_WORKSPACE_LOCATION/output/system-out.log`
   
- *result.txt* - this is the result file which *must be created by the executed script* +
  `$PDS_JOB_WORKSPACE_LOCATION/output/result.txt`.
  The path is represented by the variable `PDS_JOB_RESULT_FILE`

[[section-config-messaging]]
==== Messaging
We can write text files into the folder defined in <<table-link-pds-launcher-script-variable-messages,PDS_JOB_USER_MESSAGES_FOLDER>> 
to send product messages back to users.

Info, error and warnings will be available inside the {sechub} report and also inside the job status for the user.
    
===== Snippets
[[example-shared-messaging]]
====== Bash messaging
Here a working solution for creating unique message files from bash scripts:
[source, bash]
----
include::../../../../../..//sechub-integrationtest/pds/product-scripts/shared/shared-messaging-referenced-in-documentation-as-example.sh[]
----
Usage:

[source, bash]
----
include::../../../../../..//sechub-integrationtest/pds/product-scripts/shared/shared-messaging-referenced-in-documentation-as-example-usage.sh[]
----
 

The former call did create following message files which contain the given text parts: 
----
include::../../../../../..//sechub-integrationtest/pds/product-scripts/shared/shared-messaging-referenced-in-documentation-as-example-output.txt[]
----   