=== Configuration

=== Tech user credentials

Either use system properties

----
sechub.pds.techuser.userid
sechub.pds.techuser.apitoken
----
or env entries
----
SECHUB_PDS_TECHUSER_USERID
SECHUB_PDS_TECHUSER_APITOKEN
----
to define user credentisals. For apitoken please define encrypted password in spring boot
style - e.g. `{noop}unencrypted`, `{bcrypt}crypted` ...

=== Admin credentials

Either use system properties

----
sechub.pds.admin.userid
sechub.pds.admin.apitoken
----
or env entries
----
SECHUB_PDS_ADMIN_USERID
SECHUB_PDS_ADMIN_APITOKEN
----
to define admin credentisals. For apitoken please define encrypted password in spring boot
style - e.g. `{noop}unencrypted`, `{bcrypt}crypted` ...


=== Workspace parent folder
With `-Dsechub.pds.workspace.rootfolder` or using environment variable `SECHUB_PDS_WORKSPACE_ROOTFOLDER`
workspace location can be defined

=== Server configuration file
PDS reads configuration JSON file on startup.

*Location*

With `-Dsechub.pds.config.file=...` or using environment variable `SECHUB_PDS_CONFIG_FILE`
its is possible to set config file path ( when not defined fallback is `./pds-config.json`)
 
[source,json]
----
include::product_delegation_server_config_example1.json[]
----
<1> identifier, which will be used at job configuration time. Defines what will be executed
<2> path to command what will be executed.

<3> scanType can be either
 - codeScan
 - infraScan
 - webScan
<4> description
<5> defines if PDS will automatically unzip zip files. default is `true`. When `true` the content
   of the unzipped files will be available inside `${pdsWorkspaceLocation}/${jobUUID}/uploads/unzipped/${nameOfUploadFileWithoutZipExt}`
