// SPDX-License-Identifier: MIT

:toc:
:numbered:

= Checkmarx Wrapper + PDS


The Checkmarx Wrapper + PDS solution combines SecHub https://mercedes-benz.github.io/sechub/latest/sechub-product-delegation-server.html[Product Delegation Server (PDS)] 
and the https://github.com/mercedes-benz/sechub/tree/develop/sechub-wrapper-checkmarx[SecHub Checkmarx Wrapper] inside a container.

The Checkmarx Wrapper communicates with https://checkmarx.com/product/cxsast-source-code-scanning/[Checkmarx SAST] using the REST API.
Checkmarx SAST is a commercial security tool for Static Application Security Testing (SAST).

This folder contains only the scripts necessary to run the SecHub Checkmarx Wrapper and the PDS. It does not contain any scripts to set up Checkmarx SAST.

NOTE: A separate Checkmarx SAST installation is neccessary to make full use of this PDS Solution. 

== Run Locally

This is the easiest way to get started.

=== Requirements

Docker and Docker-Compose need to be installed:

. https://docs.docker.com/engine/install/[Install Docker]

. Linux: https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user[Use Docker as non Root user]

. https://docs.docker.com/compose/install/[Install Docker-Compose]

=== Single Instance

Start a single instance by using the Bash wrapper script which does setup everything automatically for you.

==== Scan script

The folder contains a start Bash start script:

----
./01-start-single-docker-compose.sh
----

==== Together with SecHub

The container will be started and attached to the `sechub` Network.

WARNING: Make sure the SecHub container is running.

. Start container:
+
----
./05-start-single-sechub-network-docker-compose.sh
----

[[scan]]
=== Scan

The steps required to scan with the PDS.

==== Scan Script 

. Set the environment variables
+
----
export PDS_SERVER=https://<pds-host>:<port>
export PDS_USERID=admin
export PDS_APITOKEN="<pds-admin-apitoken>"
export PDS_PRODUCT_IDENTFIER=PDS_CHECKMARX
----
+
For example:
+
----
export PDS_SERVER=https://localhost:8444
export PDS_USERID=admin
export PDS_APITOKEN="pds-apitoken"
export PDS_PRODUCT_IDENTFIER=PDS_CHECKMARX
----
+
[NOTE]
Those values are the default values from `env-initial` and `env-cluster-initial` files. In case you run PDS+Checkmarx in Kubernetes or other environments those values will be different.

. Scan by providing a `ZIP` folder with Go source code.
+
----
cd ../shared/
./01-test.sh <path-to-zip-file>
----
+
For example:
+
----
cd ../shared/
./01-test.sh ~/myproject.zip
----

=== Cluster

The cluster is created locally via `docker-compose`.

==== Shared Volume

The cluster uses a shared volume defined in `docker-compose`. Docker allows to create volumes which can be used by multiple instances to upload files to. Reading, extracting and analysing the files is done in the Checkmarx+PDS container.

The cluster consists of a PostgreSQL database, a Nginx loadbalancer and one or more PDS server.

image::../shared/media/cluster_shared_volume.svg[Components of cluster with shared volume]

===== Start Script

Starting several Checkmarx+PDS instances:

----
./50-start-multiple-docker-compose.sh <replicas>
----

Example of starting 3 Checkmarx+PDS instances:

----
./50-start-multiple-docker-compose.sh 3
----

==== Object Storage

The cluster uses an object storage to store files. The cluster uses https://github.com/chrislusf/seaweedfs[SeaweedFS] (S3 compatible) to store files. The PDS instance(s) use the object storage to upload files to. Reading, extracting and analysing the files is done in the Checkmarx+PDS container.

The cluster consists of a PostgreSQL database, a Nginx loadbalancer, a SeaweedFS object storage and one or more PDS server.

image::../shared/media/cluster_object_storage.svg[Components of cluster with object storage]

===== Start Script

Starting several Checkmarx+PDS instances

----
./51-start-multiple-object-storage-docker-compose.sh <replicas>
----

Example of starting 3 Checkmarx+PDS instances

----
./51-start-multiple-object-storage-docker-compose.sh 3
----

=== Change the Configuration

There are several configuration options available for the Checkmarx+PDS `docker-compose` files. Have a look at `env` and `../shared/environment` for more details.

=== Troubleshooting

This section contains information about how to troubleshoot Checkmarx+PDS if something goes wrong.

==== Access the container

----
docker exec -it pds-checkmarx bash
----

==== Java Application Remote Debugging of PDS

. Set `JAVA_ENABLE_DEBUG=true` in the `.env-*` file

. Connect via remote debugging to the `pds`
+
connect via CLI
+
----
jdb -attach localhost:15024
----
+
TIP: https://www.baeldung.com/java-application-remote-debugging[Java Application Remote Debugging] and https://www.tutorialspoint.com/jdb/jdb_basic_commands.htm[JDB - Basic Commands]
+
or connect via IDE (e. g. Eclipse IDE, VSCodium, Eclipse Theia, IntelliJ etc.).
+
TIP: https://www.eclipse.org/community/eclipse_newsletter/2017/june/article1.php[Debugging the Eclipse IDE for Java Developers]

== Build Image and Push to Registry

Build container images and push them to registry to run Checkmarx+PDS on virtual machines, Kubernetes or any other distributed system.

=== Build Image

Build the container image.

==== Build

. Using a base image:
+
----
./10-create-image.sh my.registry.example.org/sechub/pds_checkmarx v0.1 "ghcr.io/mercedes-benz/sechub/pds-base:latest"
----
+
NOTE: By changing the third parameter, you can provide your own base image as well.

=== Push Image to Registry

Push the container image to a registry.

* Push the version tag only
+
----
./20-push-image.sh my.registry.example.org/sechub/pds_checkmarx v0.1
----

* Push the version and `latest` tags
+
----
./20-push-image.sh my.registry.example.org/sechub/pds_checkmarx v0.1 yes
----

== Kubernetes

https://kubernetes.io/[Kubernetes] is an open-source container-orchestration system. This sections explains how to deploy and run PDS+Checkmarx in Kubernetes.

=== Helm

https://helm.sh/[Helm] is a package manager for Kubernetes.

==== Requierments

* https://helm.sh/docs/intro/install/[Helm] installed
* `pds_checkmarx` image pushed to registry

==== Installation

. Create a `myvalues.yaml` configuration file
+
A minimal example configuration file with one instance:
+
[source,yaml]
----
replicaCount: 1

pds:
   startMode: localserver

users:
   admin:
      id: "admin"
      apiToken: "{noop}<my-admin-password>"
   technical:
      id: "techuser"
      apiToken: "{noop}<my-technical-password>"

storage:
    local:
        enabled: true

networkPolicy:
    enabled: true
    ingress:
    - from:
        - podSelector:
            matchLabels:
                name: sechub-server
        - podSelector:
            matchLabels:
                name: sechub-adminserver
----
+
An example configuration file with 3 replicas, postgresql and object storage:
+
[source,yaml]
----
replicaCount: 3

pds:
   startMode: localserver
   keepContainerAliveAfterPDSCrashed: true

users:
   admin:
      id: "admin"
      apiToken: "{noop}<my-admin-password>"
   technical:
      id: "techuser"
      apiToken: "{noop}<my-technical-password>"
      

database:
    postgres:
        enabled: true
        connection: "jdbc:postgresql://<my-database-host>:<port>/<my-database>"
        username: "<username-for-my-database>"
        password: "<password-for-my-database>"

storage:
    local:
        enabled: false
    s3:
        enabled: true
        endpoint: "https://<my-s3-object-storage>:443"
        bucketname: "<my-bucket>"
        accesskey: "<my-accesskey>"
        secretkey: "<my-secretkey>"

networkPolicy:
    enabled: true
    ingress:
    - from:
        - podSelector:
            matchLabels:
                name: sechub-server
        - podSelector:
            matchLabels:
                name: sechub-adminserver
----
+
[TIP]
To generate passwords use `tr -dc A-Za-z0-9 </dev/urandom | head -c 18 ; echo ''`, `openssl rand -base64 15`, `apg -MSNCL -m 15 -x 20` or `shuf -zer -n20  {A..Z} {a..z} {0..9}`.

. Install helm package from file system
+
----
helm install --values myvalues.yaml pds-checkmarx helm/pds-checkmarx/
----
+
[TIP]
Use `helm --namespace <my-namespace> install…` to install the helm chart into another namespace in the Kubernetes cluster.

. List pods
+
----
kubectl get pods
NAME                             READY   STATUS    RESTARTS   AGE
pds-checkmarx-545f5bc8-7s6rh         1/1     Running   0          1m43s
pds-checkmarx-545f5bc8-px9cs         1/1     Running   0          1m43s
pds-checkmarx-545f5bc8-t52p6         1/1     Running   0          3m

----

. Forward port of one of the pods to own machine
+
----
kubectl port-forward pds-checkmarx-545f5bc8-7s6rh  8444:8444
----

. Scan as explained in <<scan>>.

==== Upgrade

In case, `my-values.yaml` was changed. Simply, use `helm upgrade` to update the deployment. `helm` will handle scaling up and down as well as changing the configuration.

----
helm upgrade --values my-values.yaml pds-checkmarx helm/pds-checkmarx/
----

==== Uninstall 

. Helm list
+
----
helm list
NAME     	NAMESPACE 	REVISION	UPDATED                                 	STATUS  	CHART                          	APP VERSION
pds-checkmarx	my-namespace	1       	2021-06-24 21:54:37.668489822 +0200 CEST	deployed	pds-checkmarx-0.1.0                	0.21.0 
----

. Helm uninstall
+
----
helm uninstall pds-checkmarx
----

=== Troubleshooting

* Access deployment events.
+
----
kubectl describe pod pds-checkmarx-545f5bc8-7s6rh
…
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  1m    default-scheduler  Successfully assigned sechub-dev/pds-checkmarx-749fcb8d7f-jjqwn to kube-node01
  Normal  Pulling    54s   kubelet            Pulling image "my.registry.example.org/sechub/pds_checkmarx:v0.1"
  Normal  Pulled     40s   kubelet            Successfully pulled image "my.registry.example.org/sechub/pds_checkmarx:v0.1" in 13.815348799s
  Normal  Created    15s   kubelet            Created container pds-checkmarx
  Normal  Started    10s   kubelet            Started container pds-checkmarx
----

* Access container logs.
+
----
kubectl logs pds-checkmarx-545f5bc8-7s6rh

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.7.3)

{"@timestamp":"2022-10-11T16:49:51.925Z","@version":"1","message":"Starting SecHubServerApplication using Java 11.0.12 on sechub-server-7d549cfcf5-7r9rb with PID 7 (/home/javarun/app.jar started by javarun in /home/javarun)","logger_name":"com.mercedesbenz.sechub.SecHubServerApplication","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2022-10-11T16:49:51.939Z","@version":"1","message":"Running with Spring Boot v2.7.3, Spring v5.3.22","logger_name":"com.mercedesbenz.sechub.SecHubServerApplication","thread_name":"main","level":"DEBUG","level_value":10000}
{"@timestamp":"2022-10-11T16:49:51.94Z","@version":"1","message":"The following 6 profiles are active: \"dev\", \"localserver\", \"initial_admin_predefined\", \"admin_access\", \"postgres\", \"real_products\"","logger_name":"com.mercedesbenz.sechub.SecHubServerApplication","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2022-10-11T16:49:56.897Z","@version":"1","message":"The protocol [TLSv1.3] was added to the list of protocols on the SSLHostConfig named [_default_]. Check if a +/- prefix is missing.","logger_name":"org.apache.tomcat.util.net.SSLHostConfig","thread_name":"main","level":"WARN","level_value":30000}
{"@timestamp":"2022-10-11T16:49:56.899Z","@version":"1","message":"Set max swallow size to 22020096","logger_name":"com.mercedesbenz.sechub.server.core.SecHubTomcatServletWebserverFactory","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2022-10-11T16:49:56.982Z","@version":"1","message":"Starting service [Tomcat]","logger_name":"org.apache.catalina.core.StandardService","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2022-10-11T16:49:56.983Z","@version":"1","message":"Starting Servlet engine: [Apache Tomcat/9.0.65]","logger_name":"org.apache.catalina.core.StandardEngine","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2022-10-11T16:49:57.083Z","@version":"1","message":"Initializing Spring embedded WebApplicationContext","logger_name":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/]","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2022-10-11T16:49:57.523Z","@version":"1","message":"Start flyway repair","logger_name":"com.mercedesbenz.sechub.server.SecHubServerFlywayFactory","thread_name":"main","level":"INFO","level_value":20000}
{"@timestamp":"2022-10-11T16:49:57.909Z","@version":"1","message":"Flyway repair done for flyway version:8.5.13","logger_name":"com.mercedesbenz.sechub.server.SecHubServerFlywayFactory","thread_name":"main","level":"INFO","level_value":20000}
----