# SPDX-License-Identifier: MIT

version: "3"
services:
    pds-gitleaks:
        build:
            args:
                - BASE_IMAGE=${BASE_IMAGE}
                - GITLEAKS_VERSION=${GITLEAKS_VERSION}
            context: docker/
            dockerfile: Gitleaks.dockerfile
        container_name: pds-gitleaks
        env_file:
            - .env
            - .env-single
        ports:
            - "127.0.0.1:${PORT}:8444"
            - "127.0.0.1:${DEBUG_PORT}:15024"
        networks:
            - "internal"
        volumes:
          - ./docker/scripts:/pds/scripts
          - ./docker/mocks:/pds/mocks
networks:
    internal:
