# SPDX-License-Identifier: MIT

version: "3"
services:
    gitleaks:
        build:
            args:
                - BASE_IMAGE=${BASE_IMAGE}
            context: docker/
            dockerfile: Gitleaks.dockerfile
        container_name: gitleaks
        env_file:
            - .env
            - .env-single
        ports:
            - "127.0.0.1:8444:8444"
            - "127.0.0.1:15024:15024"
        networks:
            - "internal"
        volumes:
          - ./docker/scripts:/scripts
          - ./docker/mocks:/mocks
networks:
    internal:
