# SPDX-License-Identifier: MIT

# This is just a sample values file.

replicaCount: 1

image:
    registry: "my.registry.example.org/pds_findsecuritybugs"
    tag: "latest"

resources:
    requests:
        memory: 256Mi
    limits:
        memory: 1Gi

pds:
    # 100 MiB by default
    # 1024**2 * 100 = 104857600
    uploadBinariesMaximumBytes: "104857600"
    volumes:
      workspace:
        size: "1Gi"
    startMode: localserver
    javaDebug:
        enabled: false
    keepContainerAliveAfterPDSCrashed: false
    maxFileUploadSize: 20MB
    logging:
        type:
            enabled: false
            appenderName: "LOGSTASH_JSON"

users:
    technical:
        id: "techuser"
    admin:
        id: "admin"

storage:
    local:
        enabled: true
    s3:
        enabled: false
        endpoint: "https://<minio-or-s3-server>:<port>"
        bucketname: "<my-bucketname>"
        accesskey: "<my-accesskey>"
        secretkey: "<my-secretkey>"
    sharedVolume:
        enabled: false
        upload:
            dir: "/mount/nfs/shares/<sharename>"

database:
    postgres:
        enabled: false
        connection: "jdbc:postgresql://database:5432/pds"
        username: "gosec"
        password: "<password-of-db-user>"

networkPolicy:
    enabled: false
    ingress:
    - from:
        - podSelector:
            matchLabels:
                name: sechub-server
        - podSelector:
            matchLabels:
                name: sechub-adminserver