// SPDX-License-Identifier: MIT
/*
 * SecHub API
 * SecHub API description
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.mercedesbenz.sechub.systemtest.pdsclient.internal;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mercedesbenz.sechub.api.internal.gen.invoker.ApiClient;
import com.mercedesbenz.sechub.api.internal.gen.invoker.ApiException;
import com.mercedesbenz.sechub.api.internal.gen.invoker.ApiResponse;

/**
 * This class was originally adopted from
 * com.mercedesbenz.sechub.api.internal.gen.AnonymousApi which is generated. It
 * uses same invoker classes as used in AnonymousApi to reduce boilerplate code.
 *
 * @author Albert Tregnaghi
 *
 */
public class PDSCommonApi {
    private final HttpClient memberVarHttpClient;
    private final ObjectMapper memberVarObjectMapper;
    private final String memberVarBaseUri;
    private final Consumer<HttpRequest.Builder> memberVarInterceptor;
    private final Duration memberVarReadTimeout;
    private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
    private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

    public PDSCommonApi(ApiClient apiClient) {
        memberVarHttpClient = apiClient.getHttpClient();
        memberVarObjectMapper = apiClient.getObjectMapper();
        memberVarBaseUri = apiClient.getBaseUri();
        memberVarInterceptor = apiClient.getRequestInterceptor();
        memberVarReadTimeout = apiClient.getReadTimeout();
        memberVarResponseInterceptor = apiClient.getResponseInterceptor();
        memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
    }

    protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
        String body = response.body() == null ? null : new String(response.body().readAllBytes());
        String message = formatExceptionMessage(operationId, response.statusCode(), body);
        return new ApiException(response.statusCode(), message, response.headers(), body);
    }

    private String formatExceptionMessage(String operationId, int statusCode, String body) {
        if (body == null || body.isEmpty()) {
            body = "[no body]";
        }
        return operationId + " call failed with: " + statusCode + " - " + body;
    }

    /**
     * Check if the server is alive and running. An anonymous user or system wants
     * to know if the server is alive and running.
     *
     * @throws ApiException if fails to make API call
     */
    public void anonymousCheckAliveGet() throws ApiException {
        anonymousCheckAliveGetWithHttpInfo();
    }

    /**
     * Check if the server is alive and running. An anonymous user or system wants
     * to know if the server is alive and running.
     *
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException if fails to make API call
     */
    public ApiResponse<Void> anonymousCheckAliveGetWithHttpInfo() throws ApiException {
        HttpRequest.Builder localVarRequestBuilder = anonymousCheckAliveGetRequestBuilder();
        try {
            HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(localVarRequestBuilder.build(), HttpResponse.BodyHandlers.ofInputStream());
            if (memberVarResponseInterceptor != null) {
                memberVarResponseInterceptor.accept(localVarResponse);
            }
            try {
                if (localVarResponse.statusCode() / 100 != 2) {
                    throw getApiException("anonymousCheckAliveGet", localVarResponse);
                }
                return new ApiResponse<Void>(localVarResponse.statusCode(), localVarResponse.headers().map(), null);
            } finally {
                // Drain the InputStream
                while (localVarResponse.body().read() != -1) {
                    // Ignore
                }
                localVarResponse.body().close();
            }
        } catch (IOException e) {
            throw new ApiException(e);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new ApiException(e);
        }
    }

    private HttpRequest.Builder anonymousCheckAliveGetRequestBuilder() throws ApiException {

        HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

        String localVarPath = "/api/anonymous/check/alive";

        localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

        localVarRequestBuilder.header("Accept", "application/json");

        localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
        if (memberVarReadTimeout != null) {
            localVarRequestBuilder.timeout(memberVarReadTimeout);
        }
        if (memberVarInterceptor != null) {
            memberVarInterceptor.accept(localVarRequestBuilder);
        }
        return localVarRequestBuilder;
    }

    /**
     * Check if the server is alive and running. An anonymous user or system wants
     * to know if the server is alive and running.
     *
     * @throws ApiException if fails to make API call
     */
    public void anonymousCheckAliveHead() throws ApiException {
        anonymousCheckAliveHeadWithHttpInfo();
    }

    /**
     * Check if the server is alive and running. An anonymous user or system wants
     * to know if the server is alive and running.
     *
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException if fails to make API call
     */
    public ApiResponse<Void> anonymousCheckAliveHeadWithHttpInfo() throws ApiException {
        HttpRequest.Builder localVarRequestBuilder = anonymousCheckAliveHeadRequestBuilder();
        try {
            HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(localVarRequestBuilder.build(), HttpResponse.BodyHandlers.ofInputStream());
            if (memberVarResponseInterceptor != null) {
                memberVarResponseInterceptor.accept(localVarResponse);
            }
            try {
                if (localVarResponse.statusCode() / 100 != 2) {
                    throw getApiException("anonymousCheckAliveHead", localVarResponse);
                }
                return new ApiResponse<Void>(localVarResponse.statusCode(), localVarResponse.headers().map(), null);
            } finally {
                // Drain the InputStream
                while (localVarResponse.body().read() != -1) {
                    // Ignore
                }
                localVarResponse.body().close();
            }
        } catch (IOException e) {
            throw new ApiException(e);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new ApiException(e);
        }
    }

    private HttpRequest.Builder anonymousCheckAliveHeadRequestBuilder() throws ApiException {

        HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

        String localVarPath = "/api/anonymous/check/alive";

        localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

        localVarRequestBuilder.header("Accept", "application/json");

        localVarRequestBuilder.method("HEAD", HttpRequest.BodyPublishers.noBody());
        if (memberVarReadTimeout != null) {
            localVarRequestBuilder.timeout(memberVarReadTimeout);
        }
        if (memberVarInterceptor != null) {
            memberVarInterceptor.accept(localVarRequestBuilder);
        }
        return localVarRequestBuilder;
    }

    private HttpRequest.Builder authorizedRequestBuilder(String url, String accept, String httpMethod) throws ApiException {
        HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

        String localVarPath = url;

        localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

        if (accept != null) {
            localVarRequestBuilder.header("Accept", accept);
        }

        localVarRequestBuilder.method(httpMethod, HttpRequest.BodyPublishers.noBody());
        if (memberVarReadTimeout != null) {
            localVarRequestBuilder.timeout(memberVarReadTimeout);
        }
        if (memberVarInterceptor != null) {
            memberVarInterceptor.accept(localVarRequestBuilder);
        }
        return localVarRequestBuilder;
    }

    public <T> ApiResponse<T> getAuthorized(String localPath, Class<T> clazz) throws ApiException {
        return getAuthorized(localPath, clazz, null);
    }

    @SuppressWarnings("unchecked")
    public <T> ApiResponse<T> getAuthorized(String localPath, Class<T> clazz, String accept) throws ApiException {
        HttpRequest.Builder localVarRequestBuilder = authorizedRequestBuilder(localPath, accept, "GET");
        try {
            HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(localVarRequestBuilder.build(), HttpResponse.BodyHandlers.ofInputStream());
            if (memberVarResponseInterceptor != null) {
                memberVarResponseInterceptor.accept(localVarResponse);
            }
            try {
                int statusCode = localVarResponse.statusCode();
                if (statusCode / 100 != 2) {
                    throw getApiException("getAuthorized:" + localPath, localVarResponse);
                }
                InputStream body = localVarResponse.body();
                Map<String, List<String>> map = localVarResponse.headers().map();

                T data = null;
                if (clazz.isAssignableFrom(String.class)) {
                    String text = new String(body.readAllBytes(), StandardCharsets.UTF_8);
                    data = (T) text;
                } else {
                    if (body != null) {
                        data = memberVarObjectMapper.readValue(body, new TypeReference<T>() {
                        });
                    }
                }

                return new ApiResponse<T>(statusCode, map, data // closes the InputStream
                );
            } finally {
            }
        } catch (IOException e) {
            throw new ApiException(e);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new ApiException(e);
        }
    }
}
