# SPDX-License-Identifier: MIT

version: "1"
services:
    pds-xray:
        build:
            args:
                - BASE_IMAGE=${BASE_IMAGE}
            context: docker/
            dockerfile: Xray-Debian.dockerfile
        container_name: pds-xray
        env_file:
            - .env
            - .env-single
        networks:
            - "internal"
        volumes:
          - ./docker/scripts:/pds/scripts
networks:
    internal:
