# SPDX-License-Identifier: MIT

version: "3"
services:
    pds-xray:
        build:
            args:
                - BASE_IMAGE=${BASE_IMAGE}
                - XRAY_WRAPPER_VERSION=${XRAY_WRAPPER_VERSION}
            context: docker/
            dockerfile: Xray-Debian.dockerfile
        container_name: pds-xray
        hostname: pds-xray
        env_file:
            - .env
            - .env-single
        networks:
            - "sechub"
        volumes:
          - ./docker/scripts:/pds/scripts

networks:
    sechub:
        external: true
        name: "sechub"
