// SPDX-License-Identifier: MIT
package com.daimler.sechub.integrationtest;

import java.util.ArrayList;
import java.util.List;

/**
 * Just a JSON representation for output files generated by ciphertest.sh
 * 
 * @author Albert Tregnaghi
 *
 */
public class CipherTestData {

    public List<CipherCheck> cipherChecks = new ArrayList<>();

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        for (CipherCheck check : cipherChecks) {
            sb.append(check.toString());
            sb.append("\n");
        }
        return sb.toString();

    }

}
