// SPDX-License-Identifier: MIT
package com.daimler.sechub.integrationtest;

/**
 * Just a JSON representation for output files generated by ciphertest.sh
 * 
 * @author Albert Tregnaghi
 *
 */
public class CipherCheck {

    public String cipher;
    public String verified;
    public String error;

    @Override
    public String toString() {
        return "CipherCheck [" + (cipher != null ? "cipher=" + cipher + ", " : "") + (verified != null ? "verified=" + verified + ", " : "")
                + (error != null ? "error=" + error : "") + "]";
    }

}
