# SPDX-License-Identifier: MIT

# Internal access via cluster IP (maybe obsolete when an api-gateway is in place)
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-internal
spec:
  selector:
    name: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.targetPort.port }}
      targetPort: {{ .Values.targetPort.port }}
  type: ClusterIP
