# SPDX-License-Identifier: MIT

name: sechub scan
description: 'a GitHub actions wrapper for SecHub security scan.'
inputs:
  config-path:
    description: 'Path to sechub.json for manual configuration. If no value is set the input parameters will be used to create it for the scan.'
    required: false
  url:
    description: 'SecHub server URL'
    required: false
  api-token:
    description: 'SecHub API Token'
    required: false
  user:
    description: 'SecHub userid'
    required: false
  project-name:
    description: 'SecHub project name'
    required: false
  version:
    description: 'Which version of the SecHub'
    required: false
    default: '1.4.0'
  include-folders:
    description: 'a list of folders to include'
    required: false
    default: '.'
  exclude-folders:
    description: 'a list of folders to exclude'
    required: false

  action:
    description: |
      The report format generated as the scan output.
      Possible values are: 'json', 'html', 'spdx-json'
    required: true
  report-format:
    description: 'the report format generated as output for the scan'
    required: false
    default: 'json'
  debug:
    description: 'SecHub debug output on/off'
    required: false
  fail-job-with-findings:
    description: 'job will be marked as failed if sechub finds something'
    required: false
    default: 'true'

outputs:
  scan-trafficlight:
    description: 'Color of the traffic light reported by SecHub'
  scan-findings-count:
    description: 'Total number of findings reported by SecHub'
  scan-findings-high:
    description: 'Number of high findings reported by SecHub'
  scan-findings-medium:
    description: 'Number of medium findings reported by SecHub'
  scan-findings-low:
    description: 'Number of low findings reported by SecHub'
  scan-readable-summary:
    description: 'Readable summary of the findings reported by SecHub'

runs:
  using: 'node16'
  main: './dist/index.js'
