// SPDX-License-Identifier: MIT
:toc:
:toclevels: 5

== GitHub Action for SecHub scan

This GitHub action uses the SecHub cli to scan the repository for security issues.




=== Usage

To be able to use this action you need a SecHub project. Check the https://mercedes-benz.github.io/sechub/[documentation] on how to set one up.

[source,yaml]
----
- uses: mercedes-benz/sechub/github-actions/scan@master
  with:
    # OPTIONAL: Path to sechub.json for manual configuration. (See IMPORTANT section below for more information)
    config-path: 'sechub.json'

    # REQUIRED: SecHub server url (can alternatively provided via env variable or config file)
    url: ${{ secrets.SECHUB_SERVER }}

    # REQUIRED: SecHub api token (can alternatively provided via env variable)
    api-token: ${{ secrets.SECHUB_APITOKEN }}

    # REQUIRED: SecHub user (can alternatively provided via env variable or config file)
    user: ${{ secrets.SECHUB_USERID }}

    # REQUIRED: the name of the project registered in SecHub (can alternatively provided via env variable or config file)
    project-name: ${{ secrets.SECHUB_PROJECT }}

    # OPTIONAL: Which version of the SecHub cli to use
    # DEFAULT: latest
    version: 'latest'

    # OPTIONAL: Whether scm history should be uploaded or not
    # DEFAULT: false
    add-scm-history: false

    # OPTIONAL: A list of scan types that shall be used when a SecHub configuration file is generated.
    #           Allowed values: codeScan, secretScan and licenseScan - If you want other scan types you
    #           have to create a SecHub configuration file and provide it by the config-path attribute
    #           (ignored in the case of a custom configuration file)
    # DEFAULT: codeScan
    scan-types: codeScan, secretScan

    # OPTIONAL: A definition of the content type which shall be used for SecHub configuration file generation.
    #           Allowed values: source,binaries. Cannot be combined.
    #           (ignored in the case of a custom configuration file)
    # DEFAULT: source
    content-type: source

    # OPTIONAL: A list of folders to be included. Multiple folders can be separated by ,
    #           (ignored in the case of a custom configuration file)
    # DEFAULT: '.'
    include-folders: 'src,lib'

    # OPTIONAL: A list of folders to be excluded. Multiple folders can be separated by ,
    #           (ignored in the case of a custom configuration file)
    # DEFAULT: empty (see SecHub documentation for default excludes)
    exclude-folders: 'bin,build,dist'

    # REQUIRED: The formats in which the report should be downloaded. Multiple values can be separatd by ,
    # DEFAULT: json,html
    report-formats: 'json,html,spdx-json'

    # OPTIONAL: When set to true, then HTTPS certificate checking will be disabled. May be useful when using self-signed certificates.
    #           Please try to avoid this setting for security reasons.
    # DEFAULT: false
    trust-all: false

    # OPTIONAL: SecHub debug output on/off.
    # DEFAULT: false
    debug: false

    # OPTIONAL: job (pipeline) will be marked as failed if SecHub finds something
    # DEFAULT: true
    fail-job-with-findings: true
----

[IMPORTANT]
====
The following variables take priority over the configuration file:

- `debug`
- `project-name`
- `trust-all`
- `url`
- `user`

If no custom `sechub.json` is provided, it will be generated from the remaining specified variables and used. However, if a custom `sechub.json` is provided, no separate configuration will be created, meaning the remaining set variables will essentially be ignored.
====

=== Outputs

The following table lists the output variables available after this SecHub GitHub Action has completed:

[cols="20%,40%,40%"]
|===
| Output Name          | Description                                           | Expected Values

| scan-trafficlight    | The color of the traffic light reported by SecHub if the scan ran successfully, otherwise `FAILURE`. | One of `GREEN`, `YELLOW`, `RED`, or `FAILURE`.
| scan-findings-count  | The total number of findings reported by SecHub. Returns 0 if the scan didn't complete.         | 0
| scan-findings-high   | The number of high-level findings reported by SecHub.         | 0
| scan-findings-medium | The number of medium-level findings reported by SecHub.         | 0
| scan-findings-low    | The number of low-level findings reported by SecHub.         | 0
| scan-readable-summary| A human-readable summary of the scan outcome, including the traffic light color, findings count, and their distribution.         | For example, `SecHub scan could not be executed` if an error occurred. Otherwise, i.e. `SecHub reported traffic light color YELLOW with 15 findings, categorized as follows: MEDIUM (8), LOW (7)`

|===


You can access them after the action has run with `${{ steps.<step-id>.outputs.<output-name> }}`

=== Build

Make sure that you have installed https://nodejs.org/en/download/package-manager[Node.js]. +
To build the action locally you have to run these commands:

[source,npm]
----
# Install dependencies
npm install
# Build
npm run build
----

This runs the ncc compiler and transpiles the files from the src folder into the `dist/` folder.
The dist files will be executed by the GitHub Action.

It's necessary to execute the build after every change of the sources and you have to commit the changes in dist to git.

=== Test

==== Unit tests
To run the unit tests you have to execute this command:

[source,npm]
----
npm run test
----


==== Integration-Test
As a precondition to run the integration tests locally you have to

- execute `__test__/01-start.sh $secHubServerVersion $sechubServerPortNr $pdsVersion $pdsPortNr`

TIP: You can also start a SecHub server and a PDS (both in integration test mode) instead of using the `01-start` script.

After the script has been executed, you can execute integration tests multiple times via following command:

[source,npm]
----
npm run integration-test
----

To enable full debug output in integration tests please execute following before running the integration tests:
[source,npm]
----
export SECHUB_DEBUG=true
----

==== Debugging tests
The unit and also the integration tests are written with `jest` test framework.

===== Setup
====== VSCodium

Used extensions

- Test explorer
- Jest Test explorer
- Jest

In this setup the tests can be executed from sidebar and from links created inside the editor.

[TIP]
====
Unfortunately, the Jest UI integration works only for npm script "test". But to handle integration tests different (the tests shall only be executed when all is build and servers are started) they are not executed by "test" script.

If you want to **debug an integration test**, there is a temporary workaround necessary while you debug the test:

- open `package.json` and look into section `scripts`
- remove 'test' entry + copy `test-with-integrationtests` entry and rename copied part to `test`
  (but please do not push this - otherwise build will fail on integration test!)
- restart your VSCode/VSCodium instance (only necessary if integration tests are not listed in test explorer)
- debug the parts, fix it etc.
- remove 'test' entry + copy `test-without-integrationtests` entry and rename copied part to `test`
- if necessary push fixes/changes to remote...
====
