// SPDX-License-Identifier: MIT
:toc:
:toclevels: 5

== GitHub Action for SecHub scan

This GitHub action uses the SecHub cli to scan the repository for security issues.




=== Usage

To be able to use this action you need a SecHub project. Check the https://mercedes-benz.github.io/sechub/[documentation] on how to set one up.

If the action runs on a custom runner and a proxy is necessary to download the sechub client from https://github.com,
specify the proxy using the default ENV variables (lowercased like used by many other cli tools) `http_proxy` or `https_proxy`.
The ENV variable `https_proxy` will be used if `http_proxy` and `https_proxy` are set.
Make sure to use the following format:

- http_proxy="http://user:password@proxy.example.org:1234"
- https_proxy="https://user:password@proxy.example.org:1234"

or without credentials:

- http_proxy="http://proxy.example.org:1234"
- https_proxy="https://proxy.example.org:1234"

[source,yaml]
----
- uses: mercedes-benz/sechub/github-actions/scan@master

  # OPTIONAL: Set a proxy for the github action with or without credentials, e.g. to download the sechub client and to access sechub
  env:
    https_proxy: "https://user:password@proxy.example.org:1234"

  with:
    # OPTIONAL: Path to sechub.json for manual configuration. (See IMPORTANT section below for more information)
    config-path: 'sechub.json'

    # REQUIRED: SecHub server url (can alternatively provided via env variable or config file)
    url: ${{ secrets.SECHUB_SERVER }}

    # REQUIRED: SecHub api token (can alternatively provided via env variable)
    api-token: ${{ secrets.SECHUB_APITOKEN }}

    # REQUIRED: SecHub user (can alternatively provided via env variable or config file)
    user: ${{ secrets.SECHUB_USERID }}

    # REQUIRED: the name of the project registered in SecHub (can alternatively provided via env variable or config file)
    project-name: ${{ secrets.SECHUB_PROJECT }}

    # OPTIONAL: 'Which version of the SecHub client to use. E.g `latest` or `1.10.0'
    # DEFAULT: latest
    version: 'latest'

    # OPTIONAL: Whether scm history should be uploaded or not
    # DEFAULT: false
    add-scm-history: false

    # OPTIONAL: A list of scan types that shall be used when a SecHub configuration file is generated.
    #           Allowed values: codeScan, secretScan, iacScan and licenseScan - If you want other scan
    #           types you have to create a SecHub configuration file and provide it by the config-path
    #           attribute (ignored in the case of a custom configuration file)
    # DEFAULT: codeScan
    scan-types: 'codeScan,secretScan'

    # OPTIONAL: A definition of the content type which shall be used for SecHub configuration file generation.
    #           Allowed values: source,binaries. Cannot be combined.
    #           (ignored in the case of a custom configuration file)
    # DEFAULT: source
    content-type: source

    # OPTIONAL: A list of folders to be included. Multiple folders can be separated by ,
    #           (ignored in the case of a custom configuration file)
    # DEFAULT: '.'
    include-folders: 'src,lib'

    # OPTIONAL: A list of folders to be excluded. Multiple folders can be separated by ,
    #           (ignored in the case of a custom configuration file)
    # DEFAULT: empty (see SecHub documentation for default excludes)
    exclude-folders: 'bin,build,dist'

    # REQUIRED: The formats in which the report should be downloaded. Multiple values can be separatd by ,
    # DEFAULT: json,html
    report-formats: 'json,html,spdx-json'

    # OPTIONAL: When set to true, then HTTPS certificate checking will be disabled. May be useful when using self-signed certificates.
    #           Please try to avoid this setting for security reasons.
    # DEFAULT: false
    trust-all: false

    # OPTIONAL: SecHub debug output on/off.
    # DEFAULT: false
    debug: false

    # OPTIONAL: job (pipeline) will be marked as failed if SecHub finds something
    # DEFAULT: true
    fail-job-with-findings: true

    # OPTIONAL: The file that defines false positives.
    #           This step is executed before the scan.
    #           The action defineFalsePositives overwrites all previously marked false positives on SecHub side with the ones defined in this file.
    #           You can use the SecHub client action getFalsePositives to get the current false positives and extend the returned false positive list.
    define-false-positives: 'sechub-false-positives.json'
    
    # OPTIONAL: An explicit client build folder path if used client version is 'build'.
    #           The parameter is only for testing unreleased versions.
    client-build-folder: ''
----

[IMPORTANT]
====
The following variables take priority over the configuration file:

- `debug`
- `project-name`
- `trust-all`
- `url`
- `user`

If no custom `sechub.json` is provided, it will be generated from the remaining specified variables and used. However, if a custom `sechub.json` is provided, no separate configuration will be created, meaning the remaining set variables will essentially be ignored.
====

=== Use SecHub results in GitHub workflows

==== GitHub Output
Because of problems with GitHub outputs (see https://github.com/mercedes-benz/sechub/issues/3481 ) SecHub no longer supports outputs but provides environment variables instead.

==== Environment variables
The following table lists the environment variables containing result data after this SecHub GitHub Action has completed:

[cols="20%,40%,40%"]
|===
| Environment variable               | Description                                           | Expected Values

| SECHUB_OUTPUT_SCAN_TRAFFICLIGHT    | The color of the traffic light reported by SecHub if the scan ran successfully, otherwise `FAILURE`. | One of `GREEN`, `YELLOW`, `RED`, or `FAILURE`.
| SECHUB_OUTPUT_SCAN_FINDINGS_COUNT  | The total number of findings reported by SecHub. Returns 0 if the scan didn't complete.         | 0
| SECHUB_OUTPUT_SCAN_FINDINGS_HIGH   | The number of high-level findings reported by SecHub.         | 0
| SECHUB_OUTPUT_SCAN_FINDINGS_MEDIUM | The number of medium-level findings reported by SecHub.         | 0
| SECHUB_OUTPUT_SCAN_FINDINGS_LOW    | The number of low-level findings reported by SecHub.         | 0
| SECHUB_OUTPUT_SCAN_READABLE_SUMMARY| A human-readable summary of the scan outcome, including the traffic light color, findings count, and their distribution.         | For example, `SecHub scan could not be executed` if an error occurred. Otherwise, i.e. `SecHub reported traffic light color YELLOW with 15 findings, categorized as follows: MEDIUM (8), LOW (7)`

|===


You can access them after the action has run with `${{ env.<environment-variable-name> }}`

=== Build

Make sure that you have installed https://nodejs.org/en/download/package-manager[Node.js]. +
To build the action locally you have to run these commands:

[source,npm]
----
# Install dependencies
npm install
# Build
npm run build
----

This runs the ncc compiler and transpiles the files from the src folder into the `dist/` folder.

=== Deployment
A GitHub action needs a transpiled `index.js` to be used as an action from workflows.

As long as we do not provide a new index.js the old action is still in usage, even when the source code has 
changed. If we do not build the file and commit and push it to git repository, the action will not 
be available!

The complete deployment process is automated by `.github/workflows/release-github-action.yml` which will create a
PR which will do all necessary steps.

=== Test

==== Unit tests
To run the unit tests you have to execute this command:

[source,npm]
----
npm run test
----


==== Integration-Test

===== Start integration tests locally
As a precondition to run the integration tests locally you have to
execute `01-start.sh $secHubServerVersion $sechubServerPortNr $pdsVersion $pdsPortN`
inside the integration test folder.

An example:

[source,bash]
----
# Next lines will start a SecHub server of version 2.4.0 and a PDS with version 2.1.0
cd ./github-actions/scan/__test__/integrationtest
./01-start.sh 2.4.0 8443 2.1.0 8444
----

TIP: You can also start a SecHub server and a PDS from IDE (both in integration test mode) instead of using the `01-start` script.

After the script has been executed, you can execute integration tests multiple times via following command:

[source,npm]
----
npm run integration-test
----

====== Change used client version
Per default 'build' will be used as client version. This means that the local build is used and no
download happens.

If you want to to change this locally, just set environment variable `SECHUB_CLIENT_VERSION` to
your wanted version - e.g. `latest` or `1.10.0`

===== Start GitHub action workflow
The worklow `github-action-scan.yml`
will be triggered on every PR which changes the workflow or the github action.

It is also possible to trigger the workflow manually at
https://github.com/mercedes-benz/sechub/actions/workflows/github-action-scan.yml

====== Change used client version
The workflow `github-action-scan.yml` uses per default `build`.

If you want to change it and test a dedicated version of the client, just trigger a manual
build at the workflow and set the version inside the parameter panel.

===== Extended logging
To enable full debug output in integration tests please execute following before running the integration tests:
[source,npm]
----
export SECHUB_INTEGRATIONTEST_DEBUG=true
----

This will activate debug logging inside integration tests (via jest mocking core.debug).

==== Debugging tests
The unit and also the integration tests are written with `jest` test framework.

===== Setup

====== VSCodium

Used extensions

- Test explorer
- Jest Test explorer
- Jest

In this setup the tests can be executed from sidebar and from links created inside the editor.

[TIP]
====
Unfortunately, the Jest UI integration works only for npm script "test". 
But to handle integration tests different (the tests shall only be executed 
when all is built and servers are started) they are not executed by "test" script.

If you want to **debug an integration test**, there is a temporary workaround necessary while you debug the test:

- open `package.json` and look into section `scripts`
- remove 'test' entry + copy `test-with-integrationtests` entry and rename copied part to `test`
  (but please do not push this - otherwise build will fail on integration test!)
- restart your VSCode/VSCodium instance (only necessary if integration tests are not listed in test explorer)
- debug the parts, fix it etc.
- remove 'test' entry + copy `test-without-integrationtests` entry and rename copied part to `test`
- if necessary push fixes/changes to remote...
====
