/*
 * SecHub API
 * SecHub API description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.daimler.sechub.client.java.api;

import com.daimler.sechub.client.java.api.ApiException;
import com.daimler.sechub.client.java.api.model.UserSignup;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AnonymousApi
 */
@Ignore
public class AnonymousApiTest {

    private final AnonymousApi api = new AnonymousApi();

    
    /**
     * Check if the server is alive and running.
     *
     * An anonymous user or system wants to know if the server is alive and running.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void anonymousCheckAliveGetTest() throws ApiException {
        api.anonymousCheckAliveGet();

        // TODO: test validations
    }
    
    /**
     * Check if the server is alive and running.
     *
     * An anonymous user or system wants to know if the server is alive and running.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void anonymousCheckAliveHeadTest() throws ApiException {
        api.anonymousCheckAliveHead();

        // TODO: test validations
    }
    
    /**
     * User clicks link to get new api token
     *
     * User clicks link to get new api token
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userClicksLinkToGetNewAPITokenTest() throws ApiException {
        String oneTimeToken = null;
        api.userClicksLinkToGetNewAPIToken(oneTimeToken);

        // TODO: test validations
    }
    
    /**
     * User requests new API token
     *
     * User requests new API token
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userRequestsNewApiTokenTest() throws ApiException {
        String emailAddress = null;
        api.userRequestsNewApiToken(emailAddress);

        // TODO: test validations
    }
    
    /**
     * User self registration
     *
     * User self registration
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userSignupTest() throws ApiException {
        UserSignup userSignup = null;
        api.userSignup(userSignup);

        // TODO: test validations
    }
    
}
