// SPDX-License-Identifier: MIT
== Development Setup

=== Preparation
==== Tool installation
You need

- JAVA {required_java_version} JDK
- Go Lang (min. {required_go_version})
- GIT

NOTE: A Go installation is only necessary for client development. All tools must be accessible from PATH variable.

==== GIT setup

===== Clone
----
git clone https://github.com/mercedes-benz/sechub.git
----

[[sechub-git-configuration]]
===== GIT Configuration
After Git clone is done, please go into the repository's root folder and define

====== User name and email
Only necessary when not like your global configuration:
----
git config user.email $yourEmailAddress
git config user.name "$firstName $lastName"
----

====== SecHub wanted setup
[source,bash]
----
git config branch.autosetuprebase always
git config branch.master.rebase true
git config push.default current
git config core.autocrlf input
git config color.ui auto
git config --add remote.origin.fetch +refs/tags/*:refs/tags/*
----

==== IDE setup

===== Eclipse

====== Import projects
Open a console in {sechub}'s repository root folder and type:

----
./gradlew cleanEclipse eclipse assemble
----

This will setup all your eclipse settings and you are able to import the now existing projects into a workspace
of your choice.

====== Create localhost server certificate
This is automatically done by former gradle call, so not necessary here.

====== Add Sechub Java Code Formatter

include::../shared/configuration/eclipse-java-sechub-formatter-setup.adoc[]

===== Others
====== Import projects
Import as you would normally do in your IDE.

====== Create localhost server certificate
To get the localhost server certificate created, open a console
just call  `./gradlew ensureLocalhostCertificate`

This will generate a self signed server certificate for localhost.

====== Add Sechub Java Code Formatter (IntelliJ)

include::../shared/configuration/intelliJ-java-sechub-formatter-setup.adoc[]

==== Special developer files

===== Developer property file
Inside `~/.sechub/sechub-developer.properties` you can define some special default behaviours
[options="header",cols="1,1,1"]
|===
|Key                                |Possible values/types   |Description
//----------------------------------------------------------------------------------------
|sechub.integrationtest.running     |boolean                 |When `true`, every integration test is run,
                                                              no matter if system property is set for launch config or not
|===

See `LocalDeveloperFileSetupSupport.java` for details.

=== First steps
Here are some first steps to get {sechub} running and being able to start developing.

==== Integration test scenario

With this setup we will start a {sechub} server instance ready for executing integration tests.
It does use only security product mocks, so we got no long running sessions. We need
no running security suite... but of course we have no real products and can not make real scans.

===== Start integration test servers
====== IDE
include::../shared/launchconfig/launchconfig_start_integrationtest_server.adoc[]

====== Console
----
./gradlew startIntegrationTestInstances
----

===== Start integration tests

Integration tests do completely execute commands like done on real system - except there is no real communication with
security products but only with mocked variants.

NOTE: Integration tests do need always a running integration test server instance.

====== IDE
When you have running integration test server instance, just execute JUnit at complete project `sechub-integrationtest`
with
----
-Dsechub.integrationtest.running=true
----

[TIP]
====
To make things easier there is the possibility to define system properties also
inside file:
`~/.sechub/sechub-developer.properties`

This file is used inside integration tests automatically.
If you add a line with `sechub.integrationtest.running=true` to this file, you do not
need to set the system property for every integration test launch configuration...
====

To execute the integration tests, you can use the following command:

----
./gradlew integrationtest
----

[CAUTION]
====
The gradle task `integrationtest` does not depend on `build`. This was
explicit not done, because build server can create server, then client and
then start integration tests (different stages ...) without building again.

*But be aware:*

If you have executed a `clean` task before, you are forced to call
`gradlew build buildGo integrationtest` to get all things working again.

====

===== Stop integration test server
To stop your running server run:

====== Console
----
./gradlew stopIntegrationTestInstances
----

=== Developer Tools

The developer tools are a set of tools that help you to develop and test {sechub}.

==== Shell scripts

The scripts are located in the `sechub-developertools/scripts` module.
They are used to start and stop the {sechub} server, run integration tests, and perform other tasks related to development (sdc.sh).
The api scripts can communicate with the {sechub} API (sechub-api.sh) or with a PDS API (pds-api.sh).

Execute the scripts with `-h` to get a list of available commands and options.

==== Test containers: PostgreSQL and OAuth2 server (Keycloak)

The test containers are used to run a PostgreSQL database and an OAuth2 server in a docker container for testing purposes.
Both container can be started and stopped with gradle tasks, with bash scripts or as Java applications.

Please see to the README of the `sechub-developertools` module for more information about the test containers. +

==== Developer administration UI

There exists a very simple user interface for developers to test out the behaviour of the {sechub} server. There will be
all functions of server available, but in a very reduced way.

WARNING: The developer administration UI is only a tool for developers and should be handled with care. +
         It's an extreme simple client for administrative parts. For real administration a frontend for admins
         will be developed in future! It's not purposed to be in a deployment, but only for development.

===== General launch setup
include::./../shared/launchconfig/launchconfig_start_general_adminui.adoc[]

===== Integration test variant
include::./../shared/launchconfig/launchconfig_start_integrationtest_dev_adminui.adoc[]

Please see to the README of the `sechub-developertools` module for more information about the DAUI. +

=== Branching model

Overview of branch types:

[options="header",cols="1,1,1"]
|===
|Name-Pattern   |Parent branch  |Details
//----------------------
|`master`             |none          | This is the leading branch. Versions, Tags etc. are done here!
                                       Direct commits to master have to be avoided. Version build
                                       is done here.
|`hotfix`             |master        | Hotfix branch. This is the branch we use for hot fixes.
                                       So we ensure changes from `develop` are not in a hotfix.

                                       After a hotfix has been merged to master the changes must be applied
                                       to `develop` branch as well.
|`develop`            |master        | Development branch. This branch will be part of the next release.
                                       Do not commit into this branch. Instead create a dedicated feature-branch.
|`feature-${issue}`   |develop       | For each feature we create a `feature-1234-xyz` branch. It will be merged into the `develop` branch when finished. A git push to remote will trigger a full CI/CD build for SecHub client, server and PDS but not for SecHub github actions.

|===


[[section-infrastructure-setup]]
== SecHub infrastructure setup
include::../shared/infrastructure/infra_springboot.adoc[]

include::../shared/infrastructure/infra_localdevelopment.adoc[]

include::../shared/infrastructure/infra_security_products.adoc[]

include::../shared/infrastructure/infra_docker.adoc[]

include::../shared/infrastructure/infra_kubernetes.adoc[]

[[section-develop-use-real-products]]
== Test / Use real products

=== Mandatory configuration

include::../gen/gen_javalaunchexample.adoc[]

include::../shared/hint_admin_access_profile.adoc[]

==== Storage configuration
include::../shared/storage_configuration.adoc[]


=== Start server in DEV mode
include::./../shared/launchconfig/launchconfig_start_dev_server.adoc[]

TIP: Please refer also
     <<section-howto-integrate-a-new-product,Howto integrate new products>>

=== Start server in PROD mode
include::./../shared/launchconfig/launchconfig_start_prod_server.adoc[]


== Special setup

=== Terminate SSL and use HTTP only
Per default {sechub} will always use `HTTPS` for communication.

Its not recommended, but if somebody wants to use SecHub with `HTTP` only
_(e.g. when running behind a SSL proxy)_ this can be done in this way:

Start your server as described before but add following additional
system properties:

----
-Dserver.ssl.enabled=false
-Dsecurity.require-ssl=false
----

NOTE: This will disable ssl encryption and also Spring security which requires ssl.

If you want to administrate this by developer admin ui, you should also
switch to the HTTP protocol as described in section
<<section-developer-adminui-setup,developer admin UI setup>>
