// SPDX-License-Identifier: MIT
== Build

=== About build technology

Leading entry point/technology is always `gradle`. So if you want to build something, please look at the
corresponding gradle tasks.

We use `github-actions` for CI which gives us a quick response at
`github.com`. For automated deployment or S3 storage testing etc. Jenkins can
 be used by defined pipeline scripts. 

include::./../buildserver/jenkins-pipeline.adoc[]


===== Eclipse 
When you execute `./gradlew eclipse` at command line the eclipse files for those projects will be generated.
As next step import the additionally created projects manually into Eclipse ("Import -> existing projects").

If you are using the Eclipse standard Gradle integration (Eclipse Buildship), the manual import step 
is probably necessary as well.

Another option is to use the https://marketplace.eclipse.org/content/egradle-ide[`EGradle`] plugin - it uses also
`./gradlew eclipse` and does the import automatically.


===== IntelliJ
For IntelliJ - similar to the steps for Eclipse - you can use the gradle idea task
`./gradlew idea -Dsechub.build.stage=all`

=== Gradle build commands overview

==== Build Server
Just call
----
./gradlew build
----

==== Build Client
Just call
----
./gradlew buildGo
----

==== Execute integration tests

Start the integration test server
----
./gradlew startIntegrationTestServer
----

Execute tests
----
./gradlew integrationtest
----

Optionally shut down the integration test server
----
./gradlew stopIntegrationTestServer
----

==== Build Documentation
Just call
----
./gradlew documentation
----

=== Publishing artifacts / development naming convention
https://github.com/mercedes-benz/sechub/packages[Artifacts] are being published automatically when a https://github.com/mercedes-benz/sechub/actions?query=workflow%3A%22Release*%22[release workflow] runs on github.com.

If you publish artifacts while developing and testing then make sure that the versioning tag contains "-SNAPSHOT" behind the product version.

Examples (SecHub server 1.10.0 development): +
- `1.10.0_alpine-SNAPSHOT` +
- `1.10.0_alpine-SNAPSHOT1` +
- `1.10.0_alpine-SNAPSHOT-2024-11-30`
