// SPDX-License-Identifier: MIT
== Build

=== About build technology

Leading entry point/technology is always `gradle`. So if you want to build something, please look at the
corresponding gradle tasks.

We use `github-actions` for CI which gives us a quick response at
`github.com`. For automated deployment or S3 storage testing etc. Jenkins can
 be used by defined pipeline scripts. 

include::./../buildserver/jenkins-pipeline.adoc[]

=== Build stages
Builds stages were introduced because of a problematic build dependency situation when it comes
to Java API generation. Build stages avoid cyclic build dependencies.

`sechub-api-java` uses a code generator which needs an OpenAPI file. But this file
is only available when SecHub server and PDS projects are compiled! 

plantuml::diagrams/diagram_build_lifecycle_api_problem.puml[format=svg, title="Stages"]  

To switch between the stages you have to define system property `sechub.build.stage`.

[TIP]
====
You do not need to define a build stage for "normal" SecHub development. 

Only when you want to develop/build `sechub-pds-tools`, `sechub-systemtest` or the `sechub-api-java` you need to
setup the build stage accordingly.
====

==== Kind of stages
The build has following stages:

- `without-api` (default) +
  The build will build everything, except those gradle projects which require the OpenAPI file or the generated
  and compiled Java API.
  
- `api-necessary`
   The Gradle initialization phase does contain additionally the Gradle projects which rely on an existing OpenAPI definition
   and/or access to build artifacts of `sechub-api-java`. This means the open file definition does already
   exist and may not change in the build.

- `all` +
  Everything is included, no constraints at all.
  
  
The logic is provided inside `BuildStage.groovy` and a snippet inside `settings.gradle`.
In a nutshell: During the Gradle initialization phase the API related projects are only added 
if wanted.

==== Special treatment on IDE imports
Because the API related gradle projects are not initialized per default, the IDE import mechanism
will not automatically import gradle subprojects like `sechub-systemtest`. 

For the gradle eclipse task there is a special treatment added inside `sechub-developertools/build.gradle`:

===== Eclipse 
When you execute `./gradlew eclipse` at command line the eclipse files for those projects will be generated.
As next step import the additionally created projects manually into Eclipse ("Import -> existing projects").

If you are using the Eclipse standard Gradle integration (Eclipse Buildship), the manual import step 
is probably necessary as well.

Another option is to use the https://marketplace.eclipse.org/content/egradle-ide[`EGradle`] plugin - it uses also
`./gradlew eclipse` and does the import automatically.


===== IntelliJ
For IntelliJ - similar to the steps for Eclipse - you can use the gradle idea task
`./gradlew idea -Dsechub.build.stage=all`

=== Gradle build commands overview

==== Build Server
Just call
----
./gradlew build
----

==== Build Client
Just call
----
./gradlew buildGo
----

==== Execute integration tests
Just call
----
./gradlew integrationtest
----
This will start also an integration test server

==== Build Documentation
Just call
----
./gradlew documentation
----

=== Publishing artifacts / development naming convention
https://github.com/mercedes-benz/sechub/packages[Artifacts] are being published automatically when a https://github.com/mercedes-benz/sechub/actions?query=workflow%3A%22Release*%22[release workflow] runs on github.com.

If you publish artifacts while developing and testing then make sure that the versioning tag contains "-SNAPSHOT" behind the product version.

Examples (SecHub server 1.10.0 development): +
- `1.10.0_alpine-SNAPSHOT` +
- `1.10.0_alpine-SNAPSHOT1` +
- `1.10.0_alpine-SNAPSHOT-2024-11-30`
