// SPDX-License-Identifier: MIT
== Build

=== About build technology

Leading entry point/technology is always `gradle`. So if you want to build something, please look at the
corresponding gradle tasks.

We use `github-actions` for CI which gives us a quick response at
`github.com`. For automated deployment or S3 storage testing etc. Jenkins can
 be used by defined pipeline scripts. 

include::./../buildserver/jenkins-pipeline.adoc[]

=== Build stages
Builds stages were introduced because of a problematic build dependency situation when it comes
to Java API generation. Build stages avoid cyclic build dependencies.

`sechub-api-java` uses a code generator which needs an OpenAPI file. But this file
is only available when SecHub server and PDS projects are compiled! 

plantuml::diagrams/diagram_build_lifecycle_api_problem.puml[format=svg, title="Stages"]  

To switch between the stages you have to define system property `sechub.build.stage`.

[TIP]
====
You do not need to define a build stage for "normal" SecHub development. 

Only when you want to develop/build `sechub-pds-tools`, `sechub-systemtest` or the `sechub-api-java` you need to
setup the build stage accordingly.
====

==== Kind of stages
The build has following stages:

- `without-api` (default) +
  The build will build everything except those gradle projects, which need the OpenAPI file or the generated
  and compile Java API.
  
- `api-necessary`
   The gradle initialization phase does contain also the gradle projects which rely on an existing OpenAPI definition
   and/or access to build artifacts of `sechub-api-java`. This means the open file definition does already
   exist and may not change in the build.

- `all` +
  Everything is included, no constraints at all
  
  
The logic is provided inside `BuildStage.groovy` and a snippet inside `settings.gradle`.
In a nutshell: At gradle initialization phase the API related projects are only added 
if wanted.

==== Special treatment on IDE imports
Because the API related gradle projects are not initialized per default, the IDE import mechanism
will not automatically import gradle subprojects like `sechub-systemtest`. 

For eclipse task there is a special treatment added inside `sechub-developertools/build.gradle` - importing
at commandline by `./gradlew eclipse` or by `EGradle` plugin will automatically import those
projects automatically.

For the eclipse standard gradle integration (Eclipse Buildship) you must enter the following
command at root folder: 
`./gradlew eclipse -Dsechub.build.stage=all`
As next step import the additionally created projects manually into eclipse.

For IntelliJ similar:
`./gradlew idea -Dsechub.build.stage=all`

=== Gradle build commands overview

==== Build Server
Just call
----
./gradlew build
----

==== Build Client
Just call
----
./gradlew buildGo
----

==== Execute integration tests
Just call
----
./gradlew integrationtest
----
This will start also an integration test server

==== Build Documentation
Just call
----
./gradlew documentation
----

==== Publish artefacts
Just call
----
./gradlew publish
----
_(if not already builds done this will be triggered automatically)_