// SPDX-License-Identifier: MIT
== Build

=== About build technology

Leading entry point/technology is always `gradle`. So if you want to build something, please look at the
corresponding gradle tasks.

We use `github-actions` for CI which gives us a quick response at
`github.com`. For automated deployment or S3 storage testing etc. Jenkins can
 be used by defined pipeline scripts. 

include::./../buildserver/jenkins-pipeline.adoc[]

=== Build stages
Builds stages were introduced because of life cycle problem when it comes to API generation. 

Some parts need `sechub-api-java` which
is compiled at build time. But `sechub-api-java` uses a code generator which needs an OpenAPI file. 
Only after the generation the compile is possible.

But the OpenAPI file is generated by `sechub-doc` at compile time, means we have following situation:

plantuml::diagrams/diagram_build_lifecycle_api_problem.puml[format=svg, title="Stages"]  

To switch between the stages you have to define system property `sechub.build.stage`.

==== Kind of stages
The build has following stages:

- `all` (default) +
  Everything is included, no constraints at all
  
- `without-api` +
  The build will build everything except those gradle projects, which need the API elements.
  
- `api-necessary`
   The build will contain also the gradle projects which rely on an existing OpenAPI definition
   and/or access to build artifacts of `sechub-api-java`.
  
The logic is provided inside `BuildStage.groovy` and a snippet inside `settings.gradle`.

=== Gradle build commands overview

==== Build Server
Just call
----
./gradlew build
----

==== Build Client
Just call
----
./gradlew buildGo
----

==== Execute integration tests
Just call
----
./gradlew integrationtest
----
This will start also an integration test server

==== Build Documentation
Just call
----
./gradlew documentation
----

==== Publish artefacts
Just call
----
./gradlew publish
----
_(if not already builds done this will be triggered automatically)_