// SPDX-License-Identifier: MIT
[[section-technical-debt]]
== Technical debt

=== Long running transactions
There could be a problem about long running transactions.


=== Domain messaging system

==== Authorization
At the moment the domain `auth` is not 100% correct implemented
respectively used more as layer that being a domain having a bounded context.

*Explanation:*

Inside project `sechub-authorizhation` spring boot auth handling is
defined. We got our own database table starting with "AUTH_" and
communication is done by events. So far so good. It works very well 
at the moment.

But... this works only because we currently have ONE self contained
system. Spring boot uses the `UserDetailService` defined inside this project.
If we decide to separate {sechub} into different deployment
units, we must either use the project as a library for deployed parts
(so more a "layer") or we introduce a possiblitiy for other domains
to get authorization info from this one.

As long as we do not separate and have all contained in ONE application
this is not a problem. When separation must be done, we need a concept
to change auth handling in adequate way.

==== Current event bus implementation
Currently the domain messaging is done by a simple observer pattern. +
It's working, is easy to maintain, simple but has some caveats:

 * Domain communication is done only inside ONE cluster member (seen from starting point). +
   (We got still cluster side working! The scheduling approach handles it correctly. But a job will have
    communication etc. only inside same JVM - which is maybe even a good thing ? - and reduces complexity)

 ** What does this include?
 *** We got no "cluster communication".
 *** We got no fallback handling when e.g. a cluster fails we got no respawning of the handling or queue entry

NOTE: This was a wanted architecture decision to keep things simple on startup. The used wrapper mechanism gives us t
      the chance to change the implementation when necessary, without too much effort. The benefits of data separation
      is still there.

===== Additional information
 * Sending asynchronous messages *are* really asynchronous +
   The implementation in `DomainMessageService` uses a spring task executor to provide this in conjunction with observer pattern.

==== What possibilities do we have to change this in future?
 * Use Queuing System (maybe something more lightweight than KAFKA...)
 * Write another spring application which has got REST API and is installed one time in cluster
 ** Problem: Bottleneck, much effort, deployment, etc.
 * Keep simple implementation as is but implement resilience

