// SPDX-License-Identifier: MIT
[[section-howto-integrate-a-new-product]]
=== Howto integrate a new product

At the beginning of {sechub} it was always necessary to implement a new product adapter (in Java), create 
a new product executor (in Java) and create new product result importer (also in Java).

*Those days are gone*. Nowadays we are shifting every new product into a {pds} (product delegation server)
 solution. For {pds} we have an already existing {pds} adapter (the logic to communicate with {pds})
 which is used always.
 
 
[IMPORTANT]
====
At the moment we have still some direct product adapters. Some are marked as deprecated and will
vanish. Others will be replaced by PDS solutions.

In the future there shall be only two products which have dedicated adapter implementations: SERECO and {pds}.
====
 
For every existing type of scan there is a dedicated {pds} product executor available. When the security 
product is able to produce SARIF output, we are able to import this already.
You can find multiple existing solutions and more details at {pds-solutions-projectsite}.

[NOTE]
====
In the best case scenario there is no need to write anything in Java - we copy an existing
pds-solution to a new folder name, make some necessary adjustments, change the caller script and we are done...
 
Only when a product result is not already supported by SERECO ({sechub} report collector), 
we must write a special `ProductResultImporter`.
====

==== Implement Wrapper or Product

Depending on the scan tool you want to add, you might need to implement a wrapper (o.a.) to communicate with the tool.

==== Create new Module and Integrate your code

. Create new gradle module
+
your project should look like sechub/your-new-module-name/src/main/java/com.mercedesbenz.sechub.yourpackagename/programm

. modify your gradle.build file
+

dependencies are global managed in sechub/gradle/wrapper, you can add new dependencies to libraries.gradle or use existing dependencies +

. add module and version to buildSrc/src/main/groovy/VersionData.groovy (to use getVersion function in your build.gradle)

. define your version in gradle/build-versioning.gradle

. include your module in sechub/settings.gradle

finally you should be able to run your task defined in your build.gradle with ./gradlew yourTask

==== PDS solution for your module

. Install docker compose as plugin https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-22-04[ubuntu22.04 install docker compose]

. copy all files from another PDS-solution +
throw everything away except the docker folder, the 01 script and the docker compose yaml used in the 01 script and the env file (if needed)

. rename all files to fit your modul name

. modify all files (Dockerfile, scripts, yaml, env ... ) to fit your modul

==== PDS standalone tests with pds-tools

Requires: sechub-solution-shared/scripts/01-test-pds.sh +
(example with licenseScan and tar upload)

. Export your variables
+
----
export PDS_SERVER=https://localhost:8444; export PDS_USERID=admin; export PDS_APITOKEN="pds-apitoken"; export PDS_PRODUCT_IDENTFIER=PDS_YOURPRODUCT
----

. Download PDS-Tools from release page https://github.com/mercedes-benz/sechub/releases

. create a sechub.json
+
[source,json]
----
{
  "apiVersion": "1.0",
  "licenseScan": {
    "use": [
      "test-sources"
    ]
  },
  "data": {
    "binaries": [
      {
        "name": "test-sources",
        "fileSystem" : {
        "folders" : [ "some-binary.tar" ]
      }
      }
    ]
  }
}
----

. create for this example a .tar file

. put both in a test folder

. run pds-tools
+
    java -jar sechub-pds-tools-cli-<version>.jar generate -p <testfolder>/sechub.json -s licenseScan

. create a pds-config.json
+
[source,json]
----
{
    "apiVersion" : "1.0",
    "sechubJobUUID": "288607bf-ac81-4088-842c-005d5702a9e9",
    "productId": "PDS_YOURPRODUCT",
    "parameters" : [ {
      "key" : "pds.scan.configuration",
      "value" : "{\n  \"licenseScan\" : {\n    \"use\" : [ \"test-sources\" ]\n  },\n  \"data\" : {\n    \"sources\" : [ ],\n    \"binaries\" : [ {\n      \"fileSystem\" : {\n        \"files\" : [ ],\n        \"folders\" : [ \"some-binary.tar\" ]\n      },\n      \"name\" : \"test-sources\"\n    } ]\n  },\n  \"apiVersion\" : \"1.0\"\n}"
  } ]
}
----
+
. Paste from created folder in /tmp/pds_solution_genxxx/pdsJobData the key values in your pds-config.json

. Copy the sourcecode.zip into your directory

. execute 01 script with your sourcode.zip your pds-cofig.json
+
    ./01-test-pds.sh sourcecode.zip pds-config.json

==== PDS and SecHub Server tests with SecHub Client

. create json product executor in sechub-solution/setup-pds/executors

. create setup-<your product>.sh in sechub-solution/setup-pds/

. create 05 scripts in sechub-pds-solutions/<your product>/

. start sechub in sechub-solution/ with

    ./01-start-single-docker-compose.sh
+

. start <your product> pds with 05 script ind sechub-pds-solutions/

    ./05-start-single-sechub-network-docker-compose.sh

. export SecHub environment variables
+
----
export SECHUB_USERID=admin; export SECHUB_APITOKEN='myTop$ecret!'; export SECHUB_SERVER=https://localhost:8443; export SECHUB_TRUSTALL=true; export SECHUB_WAITTIME_DEFAULT=3
----

. run the setup pds script in sechub-solution/setup-pds/

    ./setup-pds/<your product>.sh
+

. Download sechub client from release page https://github.com/mercedes-benz/sechub/releases/[releases]

. create sechub.json
+
[source,json]
----
{
  "apiVersion": "1.0",
  "licenseScan": {
    "use": [
      "test-binaries"
    ]
  },
  "data": {
    "binaries": [
      {
        "name": "test-binaries",
        "fileSystem" : {
        "folders" : [ "some-binary.tar" ]
      }
      }
    ]
  }
}
----
. execute scan with SecHub Client and test archive some-binary.tar and sechub.json

    sechub -project <project_name> scan