// SPDX-License-Identifier: MIT
[[section-howto-configure-mock-behaviours]]
=== Howto configure mock behaviours

The `MockedAdapterSetupService` reads a JSON configfile from file path.

Default file is located at `/sechub-other/mockdata/mockdata_setup.json`

If you want to use another location, use system property defined in
`MockedAdapterSetupService.java` to define another location.

Example:

[source,json]
----
{
    "entries": [
        { <1>
            "adapterId": "MockedNetsparkerAdapter",
            "combinations": [
                {<2>
                    "target" : "https://vulnerable.demo.example.org", <3>
                    "throwsAdapterException": false,<4>
                    "filePath": "./../sechub-other/mockdata/netsparker-mockdata-one-important-vulnerability.xml" <5>
                },
                {
                    "target": "https://safe.demo.example.org",
                    "throwsAdapterException": false,
                    "filePath": "./../sechub-other/mockdata/netsparker-mockdata-green.xml"
                },
                {
                    "target": "{any-other-target}",
                    "throwsAdapterException": false,
                    "filePath": "./../sechub-other/mockdata/netsparker-mockdata-green.xml"
                }
            ]
        }

    ]
}

----
<1> One Adapter definition for mocking, can be multiple times, but for each adapter only one definition!
<2> A combination for the adapter
<3> Target url definition, for code scanners the file resource folders are the targets
    e.g. `"../sechub-doc/src/main/java"`. When using `"{any-other-target}"` this will the combination
    used for all not defined combinations.
<4> Mocked adapter will not throw an exception on execution time, when true defined the adapter will
    thow an adapter execution. Interesting for tests
<5> Filepath for result file to return by mock when target url of Job starts with defined one