// SPDX-License-Identifier: MIT
[[section-initial-profile-and-executors]]
=== Execution profiles

An execution profile can contain multiple executor configurations. The configurations can be 
shared between multiple profiles. 

[NOTE]
====
As an example: a config with name "pds-gosec-1" can be used in profiles "profileA"
and also "profileB" at the same time. 
====

When a profile is assigned to a project and the profile is enabled, all of its 
enabled executor configurations are executed for the project when suitable for
code scan type.  

ifdef::techdoc[]
TIP: Technically we assign a projectId to a profile, because in domain `scan` we only know projectIds but not `Project` entity...
endif::techdoc[]
 
[IMPORTANT]
====
To have a scan job running, at least one executor configuration must match - 
otherwise you will have always a "green" scan result.
====

ifdef::usecasedoc[]
Following usecases are supported:

- <<section-usecase-UC_052,UC_052-Admin creates an execution profile>>

- <<section-usecase-UC_053,UC_053-Admin deletes execution profile>>

- <<section-usecase-UC_054,UC_054-Admin updates execution profile>>

- <<section-usecase-UC_055,UC_055-Admin fetches execution profile>>

- <<section-usecase-UC_056,UC_056-Admin fetches execution profile list>>

- <<section-usecase-UC_057,UC_057-Admin assigns execution profile to project>>

- <<section-usecase-UC_058,UC_058-Admin unassigns execution profile from project>>
endif::usecasedoc[]
