// SPDX-License-Identifier: MIT
[[section-initial-profile-and-executors]]
=== Profile and executor configuration

==== Executor configuration
With an executor configuration a product executor can be configured for product execution.
An executor will only be executed when configuration has been enabled!

ifdef::usecasedoc[]
Following usecases are supported:

- <<section-usecase-UC_047,UC_047-Admin creates an executor configuration>>

- <<section-usecase-UC_048,UC_048-Admin deletes executor configuration>>

- <<section-usecase-UC_049,UC_049-Admin fetches executor configuration list>>

- <<section-usecase-UC_050,UC_050-Admin fetches executor configuration>>

- <<section-usecase-UC_051,UC_051-Admin updates executor configuration>>
endif::usecasedoc[]

==== Execution profile
An execution profile can contain multiple executor configurations. The configurations can be 
shared between multiple profiles. 

[NOTE]
====
As an example: a config with name "pds-gosec-1" can be used in profiles "profileA"
and also "profileB" at the same time. 
====

Additionally a profile can be assigned to a project.

ifdef::techdoc[]
TIP: Technically we assign a projectId to a profile, because in domain `scan` we only know projectIds but not `Project` entity...
endif::techdoc[]
 
The profile has also an enabled state - like executors.

[IMPORTANT]
====
To have a scan job running for a project we need
- at least one enabled profile assigned to project
- also at least one configuration inside the profile must be enabled and suitable for wanted scan type (e.g. codescan) 
==== 

ifdef::usecasedoc[]
Following usecases are supported:

- <<section-usecase-UC_052,UC_052-Admin creates an execution proflie>>

- <<section-usecase-UC_053,UC_053-Admin deletes execution profile>>

- <<section-usecase-UC_054,UC_054-Admin updates execution profile>>

- <<section-usecase-UC_055,UC_055-Admin fetches execution profile>>

- <<section-usecase-UC_056,UC_056-Admin fetches execution proflie list>>

- <<section-usecase-UC_057,UC_057-Admin assigns execution profile to project>>

- <<section-usecase-UC_058,UC_058-Admin unassigns execution profile from project>>
endif::usecasedoc[]
