// SPDX-License-Identifier: MIT
[[scan-config-about]]
=== Scan configuration
Sometimes it is necessary to provide special scan configuration setup, e.g. when
initializing scan operations at server side.

This can be done by a special scan configuration which is defined as JSON.

Please don't be confused this configuration with `SecHub configuration` which is always on client side. 

The scan configuration feature was established before the runtime configuration
by profiles and executor configurations was introduced.

NOTE: The scan configuration is a *global configuration* for scan behaviour. At the 
moment there is no need any more for this - *now deprecated* - feature. Maybe it will be removed in the future
But we explain the concept and its possibilities here.

==== General
===== Name pattern ID providers
Currently only `namePatternIdProviders` are provided, which contain an id and mappings from name patterns
to identifiers. By this very generic approach dedicated adapters can fetch identifiers for specific name setups. 

==== Mapping
Scan configuration can be changed by {sechub} `mapping` - look at <<mapping-technical-details, mapping>> for more information.


NOTE: Just use the `provider` ID as mapping ID.


ifdef::techdoc[]
===== Technical details

*Usage*

A caller can use the `ScanConfigService` to fetch an `NamePatternIdprovider` which is able to provide
an ID for a given name. This is a very generic approach and callers must only use unique IDs to 
have dedicated, name based id mappings.

An ID can be any string. Given regular expressions are handled by https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html[JAVA regular expression Pattern] 


*Cluster handling*
Synchronization inside cluster is done over database and a special scheduler service:
`ScanConfigRefreshTriggerService` . This servcie checks periodically if current `scan configuration`
has been changed by administrators. If so the name pattern provider will be rebuild.

endif::techdoc[]

