// SPDX-License-Identifier: MIT
=== SecHub configuration JSON

A `{sechub}` configuration  must be valid `JSON` and is defined
at caller side.

It is used by the client and also by rest calls to define {sechub}
scan jobs and add meta data.

NOTE: Some minor parts are client specific and must
be handled by direct REST calls in a special way or do just not exist.
But this is mentioned inside this documentation

The individual components in the JSON are documented below:


==== API version
`apiVersion` must be defined (so mandatory). Currently only `1.0` is valid.


==== Server
`server` defines the url of your `{sechub}` server.
Information can be used by client implementations.

NOTE: This is an optional parameter only which is only interesting for the client to pass the URL.
      Every REST call contains the server URL already.


==== Project
`project` defines the project id within `{sechub}`. Information can be used by
client implementations.

NOTE: When using project id related REST calls, you do not need the project id inside the configuration.

[[sechub-config-code-scan]]
==== Code scan
`codeScan` defines the settings for code scans.

===== Upload source files from file system
This section applies only to the {sechub} client.

All source code files inside the defined folders will be automatically zipped and uploaded by the `{sechub}` client
to the {sechub} server for analysis.

Paths must be defined relative to caller location - for example
on a Jenkins Build Server this is usually the root folder of your repository.

[WARNING]
====
Please do *NOT* use `\` inside paths *but* always `/`.

We do *NOT* recommend using absolute paths *but* always relative paths! +
You should call {sechub} inside the repository's root folder - this is the standard on build servers.
====

There are two ways to define source code uploads for the {sechub} client:

###### Using `data` section

Define the files and folders in a `data` section and reference it inside the `codeScan`. +
This becomes useful e.g. if the same sources are used by different scan types.

Example `sechub.json` using `data` section

[[sechub-config-example-sourcescan-with-data-section]]
[source, json]
----
include::sechub_config_example1_sourcescan_data_section.json[]
----
<1> Define code scan
<2> Upload source code (in contrast to binary uploads)
<3> `fileSystem` - means uploading sources from local filesystem to {sechub} server
<4> Upload will contain sources from `gamechanger-android/src/main/java` and `gamechanger-server/src/main/java` and their sub folders
<5> Exclude directories (optional), the https://ant.apache.org/manual/Types/fileset.html[ANT fileset pattern notation] is supported. +
    * In the example above all files in directories named `mytestcode` and their subdirectories are excluded from upload.
    * Also all files matching `*.config` are excluded in any directory
    * Default excludes: +
     Per default, the directories `+**/test/**+` `+**/.git/**+` `+**/node_modules/**+` are already excluded.
<6> The {sechub} client only adds "well known" sources into the upload zip file.
    This reduces the upload size and the scan duration. (E.g. a codescan for a JPEG image would not make sense...) +
    In the {sechub} client documentation you will find a list of the default file endings. +
    Here we also add ".cplusplus" and ".py9" as additional accepted source file extensions.

###### `fileSystem` inside the `codeScan` section (deprecated)

Define a `fileSystem` child entry inside the `codeScan` section for code scanning. +

NOTE: This option is deprecated but still supported. +
  Please consider using the `data` section as described above as it provides more flexibility.

Example `sechub.json` using `fileSystem` inside the `codeScan` section (results in same upload as in above example):

[[sechub-config-example-sourcescan]]
[source, json]
----
include::sechub_config_example1_sourcescan_filesystem.json[]
----


==== License scan
`licenseScan` defines the settings for license scans.

[[sechub-config-example-licensescan-binary]]
===== Example binary license scan
[source, json, title="License scan configuration for binaries"]
----
include::sechub_config_example9_license_scan_with_binaries_data_reference.json[]
----
<1> name of the source <<sechub-config-data-section,data>> configuration: "firmware-images"
<2> license scan uses the referenced <<sechub-config-data-section,data>> configuration "firmware-images"

[[sechub-config-example-licensescan-sources]]
===== Example source license scan
[source, json, title="License scan configuration for sources"]
----
include::sechub_config_example10_license_scan_with_sources_data_reference.json[]
----
<1> name of the source <<sechub-config-data-section,data>> configuration: "firmware-sources"
<2> license scan uses the referenced <<sechub-config-data-section,data>> configuration "firmware-sources"

[[sechub-config-example-licensescan-combined-with-codescan]]
===== Example source licence scan with sources code scan combined
[source, json, title="License scan and code scan configuration for sources"]
----
include::sechub_config_example11_license_scan_and_code_scan_with_sources_data_reference.json[]
----
<1> name of the source <<sechub-config-data-section,data>> configuration: "firmware-sources"
<2> license scan uses the referenced <<sechub-config-data-section,data>> configuration "firmware-sources"
<3> code scan uses the referenced <<sechub-config-data-section,data>> configuration "firmware-sources"

==== Secret scan
`secretScan` defines the settings for scanning for secrets in your source code.

NOTE: The SecHub client automatically adds every file of the defined source directories. (Not only known programming language file extensions like with `codeScan`)

TIP: SecHub Client: With the `-addScmHistory` option SCM directories like `.git` are also uploaded because secrets could be in the SCM history of previous commits.

[[sechub-config-example-secretscan-sources]]
===== Example source secret scan
[source, json, title="Secret scan configuration for sources"]
----
include::sechub_config_example12_secret_scan_with_sources_data_reference.json[]
----
<1> name of the source <<sechub-config-data-section,data>> configuration: "gamechanger-source"
<2> source code folder(s) to scan. ("." = current directory)
<3> secret scan uses the referenced <<sechub-config-data-section,data>> configuration "gamechanger-source"

[[sechub-config-example-secretscan-binary]]
===== Example binary secret scan
[source, json, title="Secret scan scan configuration for binaries"]
----
include::sechub_config_example13_secret_scan_with_binaries_data_reference.json[]
----
<1> name of the source <<sechub-config-data-section,data>> configuration: "firmware-images"
<2> secret scan uses the referenced <<sechub-config-data-section,data>> configuration "firmware-images"

[[sechub-config-example-secretscan-combined-with-codescan-sources]]
===== Example source secret scan combined with code scan
[source, json, title="Secret scan and code scan configuration for sources"]
----
include::sechub_config_example14_secret_scan_and_code_scan_with_sources_data_reference.json[]
----
<1> name of the source <<sechub-config-data-section,data>> configuration: "gamechanger-source"
<2> source code folder(s) to scan.
<3> secret scan uses the referenced <<sechub-config-data-section,data>> configuration "gamechanger-source"
<4> code scan uses the referenced <<sechub-config-data-section,data>> configuration "gamechanger-source"

==== Web scan
`webScan` defines the settings for web scans (DAST).

===== URL
Use the `url` element to define a URL you want to scan.

WARNING: The URL must be whitelisted in your project. Otherwise it will be rejected.
         So you are not able to start scanning foreign domains and do _accidently_ attack them...

====== Example anonymous
[[sechub-config-example-webscan-anonymous]]
[source, json]
----
include::sechub_config_example2_webscan_anonymous.json[]
----
<1> Define web scan
<2> The `URL` to scan. This `URL` must be whitelisted in `{sechub}` project. Normally without a slash `/` at the end.
<3> *Optional*: Define includes, if you have a special path that is linked nowhere,
	so the scanner can not detect it automatically while crawling the application. You can use wildcards by using the symbol `<*>` like in the example above.
	To make the scan work the target URL will always be implicitly included with `"https://www.gamechanger.example.org<*>"` if no includes are specified. If includes are specified the scan is limited to these includes.
	In case you need to include certain parts of your application the scanner cannot detect,
	but you want everything else to be scanned as well, please specify a wildcard as include explicitly: `"includes": [ "/hidden/from/crawler/", "/<*>" ]`.
	- Includes starting with a slash (`/`) like `"includes": [ "/special/include","/special/include/<*>"]` they are interpreted relative to the scan target `URL` provided before.
	- Includes not starting with a slash (`/`) like `"includes": [ "<*>/en/contacts/<*>","en/contacts/<*>","en/contacts","en/contacts/"`] are interpreted as enclosed by wildcards like the first include in the list example: `"<*>/en/contacts/<*>"`.
<4> *Optional*: Define excludes, if you have a special path you want to exclude, from the scan.
	You can use excludes the same way you can use the includes.
	Excludes do always overwrite includes if the provided patterns for includes and excludes do have intersections.
<5> *Optional*: Define the maximum duration the scan can take.
    Scanning a "large" web page/application can take several hours or even days.
    This option ensures the scan will only run for a limited time.
<6> Define the unit of time.
    The unit can be: `millisecond`, `second`, `minute`, `hour`, `day`.

[CAUTION]
====
Includes are a different from excludes looking at wildcards, because in includes they might not be resolved properly, if the pages behind the wildcards cannot be detected by a web crawler.

If you only want to scan a specific part of your application e.g only the customers section `https://my-application.com/customer/`,
you can specify the target URL : `"url": "https://my-application.com"` and the wanted include starting with a slash like this : `"includes": [ "/customer/<*>"]`.
====

===== Login
A web scan does work much better if it has got access to all content
 - so a login is necessary most time. If you do not define a login configuration
 your web scan will be done only as anonymous user.

[CAUTION]
====
Providing login will enable web scanner to execute ALL possible
actions!

An example: Your test application has a Web UI for sending SMS which can
be triggered by an user. Then a web scan can trigger those operations as well!

If you do this inside an environment where a real SMS provider is connected,
this could result into mass SMS and also in a bigger invoice from your
SMS provider - *so be careful!*
====

====== Options

SecHub provides you with 2 options for login:

* basic authentication
* form based login
** script based

[NOTE]
====
When a web scan product (or its adapter) does not support your wanted options you
will have a failure at execution time!
====

====== Example basic authentication
[source,json]
----
include::sechub_config_example3_webscan_login_basicauth.json[]
----
<1> URL for web login
<2> Basic authentication, needs user id/name and password.
<3> *Optional*: You can set the realm used for basic authentication. But normally
    this is not necessary.

====== Example client certificate authentication
[source,json,title="client certificate authentication"]
----
include::sechub_config_example4_webscan_login_clientcertificate.json[]
----
<1> name of the source <<sechub-config-data-section,data>> configuration: "client-certificate-file-reference".
    Please use single files only instead of folders to specify the client certificate.
    If you want to combine this with an openAPI definition that must be uploaded for the scan as well,
    please refer to this <<sechub-config-openAPI-and-client-certificate, example>>.
<2> *Optional*: If the client certificate is password protected, the password can be specified here.
    Using our SecHub GO client you can make use of the GO templating engine.
    Like in the example above the you can provide an environment variable containing the password instead of writing the plaintext password in the JSON configuration file.
    In the example above the SecHub GO client will substitute the value of `"{{ .CERT_PASSWORD }}"` with the value of the environment variable `CERT_PASSWORD`.
<3> web scan uses the referenced <<sechub-config-data-section,data>> configuration "client-certificate-file-reference", to obtain the client certificate file.

====== Example form based login by script
WARNING: This example [.underline]#currently# [.underline]#only# works with the `Netsparker` DAST module. We deprecated the `Netsparker` integration because it is not developed any further from our side. We use and develop the `Zaproxy` integration. As soon as this feature is available for our actively maintained `Zaproxy` DAST module, we will remove this warning. If you host SecHub yourself with a `Netsparker` module, this does not affect you. You can use this configuration as before.

[source,json]
----
include::sechub_config_example5_webscan_login_from_sript.json[]
----
<1> URL for web login.
<2> Start of form based login.
<3> Script definition.
<4> Pages section. A page is a visible page. Some logins need more than one page.
<5> The actions which should be executed on each page.
<6> Type of action. Valid types are : +
    - `username` +
      name of user used for login
    - `password` +
      password entered at login
    - `input` +
      setup value for a field on UI
    - `click` +
      will simulate a mouse click on UI
    - `wait` +
      time to wait before executing the next action
<7> Selector (CSS) to identify web element.
<8> Value, used by most actions (`username|password|input|wait`). +
    In this examples you see variables
    in `go template` format. This is {sechub} client specific.
    If you use the REST API directly, you must use real values!
<9> A description can be added to explain an action.
<10> The time the next action will be delayed.
<11> Define the unit of time.
     The unit can be: `millisecond`, `second`, `minute`, `hour`, `day`.

WARNING: `username` and `password` are like input but {sechub} tries
         to hide these information in logs or at UI where possible.
         So do *NOT* use `input` for credentials!

[[sechub-config-example-webscan-openapi]]
====== Example OpenAPI scan
[source,json,title="Open API scan"]
----
include::sechub_config_example8_web_scan_openapi_with_data_reference.json[]
----
<1> name of the source <<sechub-config-data-section,data>> configuration: "open-api-file-reference"
<2> web scan uses "openApi" as API type
<3> web scan uses the referenced <<sechub-config-data-section,data>> configuration "open-api-file-reference"
    to obtain the open api configuration file

[[sechub-config-openAPI-and-client-certificate]]
====== Example combination of openAPI definition and client certificate authentication
[source,json,title="Open API scan with client certificate authentication"]
----
include::sechub_config_example16_webscan_client_certificate_with_openAPI.json[]
----
<1> Data section with files referenced by the `openAPI` definition. Multiple files (**NOT** folders) are possible.
<2> Data section with the file referenced by the `clientCertificate` definition. Only one single file shall be provided here.
<3> Reference to the data section containing files with your openAPI definitions (e.g. swagger.yml or openAPI.json)
<4> Reference to the data section containing file with your client certificate for authentication.

[[sechub-config-example-webscan-header]]
====== Example Header scan
[source,json,title="header scan"]
----
include::sechub_config_example15_web_scan_header.json[]
----
<1> Name of the specified header. Must not be null or empty.
<2> Value of the specified header. Must not be null or empty.
You can use the `go template` format like above by creating a environment variable like: `HEADER_VALUE="Bearer mytoken1234"`.
This might be useful to load the information via the SecHub client dynamically, if the header value you specify contains credentials.
<3> Name of the second header. You can specify a list of headers the DAST Scanner needs interact with your application.
<4> Value of the second header. Here no `go template` format is used, since in this example there are no credentials but only file size of an upload.
<5> Optional Parameter: For each header you can specify a list of URLs.
The header this list belongs to, will only be send when accessing one of the URLs on the list.
If you do not specify a list of URLs or the list is empty, the header will be send on each request to every URL.
You can also use wildcards by specifying `<*>` like in the example above.
Adding a wildcard to the end of an URL, the header will be sent to all sub URLs as well, otherwise it won't be sent to sub URLs.
Make sure that the header URL combinations are unique. This means do not specify the same header multiple times for the same scope of URLs.
<6> Optional Parameter to handle sensitive header data: If `true`, the value of this header will be masked inside the SecHub report to avoid leaking the information.
But if the parameter is set to `false` the value will be shown as is.
The **default** is `true` if nothing is specified.

[[sechub-config-example-webscan-header-value-from-data-section]]
====== Example Header scan with value from data section
[source,json,title="header scan with value from data section"]
----
include::sechub_config_example17_web_scan_header_value_from_data_section.json[]
----
<1> Name of the specified header. Must not be null or empty.
<2> Name of the source <<sechub-config-data-section,data>> configuration: "header-value-file-reference".
Please use single files only instead of folders to specify the header value. Use a separate data section for each header.
This can be used if you want to provide a large header value, which exceeds the maximum size of the sechub.json configuration file.
For each header provide either a `value` directly (as shown in <<sechub-config-example-webscan-header,Example Header scan>>) or a data section reference via `use` as shown in this example.

==== Infrastructure scan
`infraScan` (optional) defines the infrastructure scan settings.

===== URIs
Use `uris` element to define a string array containing `URIs` you want to scan.


====== Example infrascan one URI
[[sechub-config-example-infrascan-with-uri]]
[source, json]
----
include::sechub_config_example7_infrascan_uri.json[]
----
<1> Define infrastructure scan
<2> The `URI` s to scan. Every `URI` listed here must be white listed in `{sechub}` project.

===== IPs
Use `ips` element to define a string array containing `IPs` you want to scan.

====== Example infrascan one IP
[[sechub-config-example-infrascan-with-ip]]
[source, json]
----
include::sechub_config_example6_infrascan_ip.json[]
----
<1> Define infrastructure scan
<2> The `IP` s to scan. Every `IP` listed here must be white listed in `{sechub}` project.
    The given example with `127.0.0.1` represents only an example and will always not work
    because scanners do not scan them self.

[[sechub-config-data-section]]
==== Data section
With the `data` section users are able to

- define binary and source uploads
- reference the same by muliple scan types in one job

The scan configurations can reference the name data configuration elements by defining the
array attribute `"use"` with a list of references.

[source,json]
----
{
  // ..scan definition
  "use" : [ "reference-name-1","reference-name-2", ... ] //<1>
}
----
<1> the list of referenced data configurations . The referenced names must exist.

Here are some links to examples which are using <<sechub-config-data-section,data>> inside their configurations:

- <<sechub-config-example-licensescan-binary,License scan for binaries>>
- <<sechub-config-example-licensescan-sources,License scan for sources>>
- <<sechub-config-example-licensescan-combined-with-codescan,License scan for sources combined with code scan>>
- <<sechub-config-example-webscan-openapi,OpenAPI web scan>>

The next figure shows an example which presents all possibilities _(for simplicity the source and
binary configuration arrays do contain only just one entry)_:

[source, json, title="General JSON syntax"]
----
include::sechub_config_data_section_general_example1.json[]
----

<1> `data`: The main element for data configuration.
<2> `sources`: Inside this array multiple source data definitions can be listed
<3> `name`:  Is a unique name for the data configuration element. The name must
    be unique inside the whole {sechub} configuration file! Allowed characters are `a-z`,`0-9` and the special characters `_` and `-`.
<4> `fileSystem`: Describes fileystem parts which are available inside this data configuration element
<5> `files`: An array containing file paths to use for uploading dedicated files
<6> `folders`: An array containing folder paths to use for uploading dedicated folders
<7> `excludes`: Exclude directories (optional) - see <<sechub-config-example-sourcescan,code scan >>
for details. The excludes work for sources and binaries the same way.
<8> `additionalFilenameExtensions` Introduce additional file name extensions. See <<sechub-config-example-sourcescan,code scan >>
for details about default behaviour for sources.
<9> `sources`: Inside this array multiple binary data definitions can be listed.


[[sechub-config-metadata-section]]
==== MetaData
The {sechub} configuration file can have optional meta data.

===== Labels
With labels a user is able to add additional information to the
scan configuration which end up in the report as key value pairs.

TIP: Using the {sechub} client, you can also pass labels via command line or environment variables.

The next figure shows an example which presents all possibilities _(for simplicity other configuration
elements are removed)_.


[source, json, title="General JSON syntax"]
----
include::sechub_config_metadata_example1.json[]
----

<1> `metaData`: The main element for meta data configuration. It is optional.
<2> `labels`: Inside this element the user can define labels as key value pairs.
- maximum allowed entries per configuration file: 20
<3> represents the label key.
- allowed are characters `A-Z`,`a-z`,`0-9` and the special characters `_` , `-` and `.`
- minimum length: 1 character
- maximum length: 30 characters
<4> represents the label value.
- can contain any text (content will be escaped accordingly in reports)
- minimum length: 0 characters
- maximum length: 150 characters


