// SPDX-License-Identifier: MIT
=== SecHub configuration

A `{sechub}` configuration  must be valid `JSON` and is defined
at caller side.

It is used by client and also by rest calls to start {sechub}
scan jobs and add meta data. 

Some minor parts are client specific and must
be handled by direct REST calls in a special way or do just not exist. 
But this is mentioned inside this documentation

==== API version
`apiVersion` must be defined (so mandatory). Currently only `1.0` is valid.

[NOTE]
====
As long as the SecHub configuration is still strongly developed,
the API version remains - despite changes - to 1.0.

During this time, however, the API always remains backwards compatible!
====

==== Server
`server` (optional) defines the location to `{sechub}` server.
Information can be used by client implementations.

NOTE: When using REST calls directly you do not need the information inside
      configuration because you use server URL in every call...

==== Project
`project` (optional) defines the project to use. Information can be used by
client implementations.

NOTE: When using REST calls directly you do not need the information inside
      configuration because you use project id inside URL.

[[sechub-config-code-scan]]
==== Code scan
`codeScan` (optional) defines the code scan settings.

===== Upload sources from file system
Define `fileSystem` child entry and setup folders to use for code scanning by
`folders` sub entry.

All source code files inside these folders will be automatically zipped and uploaded by `{sechub}` client
to server side for ongoing source analysis.

Pathes must be defined relative from caller location - for example
on a Jenkins Build Server this is normally the root folder of repository.

NOTE: The configuration parts inside `fileSystem` entry are interpreted by
      `{sechub}` client! When you directly use the REST API you do not need
      to define this data but you have to upload sources as a `zip`file by
      your own over REST!

[WARNING]
====
Please do *NOT* use `\` inside pathes *but* always `/`.

Also do *NOT* use absolute pathes *but* always relative pathes! Normally you should
call {sechub} inside root folder of your source repository - this is the standard situation
on build servers.
====

===== Example sechub.json

[[sechub-config-example-sourcescan]]
[source, json]
----
include::sechub_config_example1_sourcescan_filesystem.json[]
----
<1> Define code scan
<2> Use filesystem - so means upload sources to server
<3> Upload will contain sources from `gamechanger-android/src/main/java` and `gamechanger-server/src/main/java` and their sub folders
<4> Exclude directories (optional), syntax is similar to https://ant.apache.org/manual/Types/fileset.html[ANT fileset]. +
    In the example above all files in following directories are excluded from upload: +
    * `+**/mytestcode/**+` +
    excludes all files under a directory named `build` including sub directories
    * `+**/documentation/**+` +
    same for folder `documentation`
    * default excludes +
     Per default, the directories `+**/test/**+` `+**/.git/**+`
are already excluded.
<5> {sechub} client does only add wellknown sources into created upload zip file. This removes
    unnecessary stuff and reduces upload size automatically. +
    _E.g. a codescan for a `JPEG` image would not make sense..._ +
    Instead of defining a negative list, we use a positive list and accept only wellknown sources,
    which is simply done by file ending. + 
    In the example we allow also ".cplusplus" and ".py9" as additional accepted source files.
    Inside client documentation you will find a list of the default file endings.  

==== License scan
`licenseScan`(optional) defines the license scan settings.

[[sechub-config-example-licensescan-binary]]
===== Example binary license scan
[source, json, title="License scan configuration for binaries"]
----
include::sechub_config_example9_license_scan_with_binaries_data_reference.json[]
----
<1> name of the source <<sechub-config-data-section,data>> configuration: "firmware-images"
<2> license scan uses the referenced <<sechub-config-data-section,data>> configuration "firmware-images"

[[sechub-config-example-licensescan-sources]]
===== Example source license scan
[source, json, title="License scan configuration for sources"]
----
include::sechub_config_example10_license_scan_with_sources_data_reference.json[]
----
<1> name of the source <<sechub-config-data-section,data>> configuration: "firmware-sources"
<2> license scan uses the referenced <<sechub-config-data-section,data>> configuration "firmware-sources"

[[sechub-config-example-licensescan-combined-with-codescan]]
===== Example source licence scan with sources code scan combined
[source, json, title="License scan and code scan configuration for sources"]
----
include::sechub_config_example11_license_scan_and_code_scan_with_sources_data_reference.json[]
----
<1> name of the source <<sechub-config-data-section,data>> configuration: "firmware-sources"
<2> license scan uses the referenced <<sechub-config-data-section,data>> configuration "firmware-sources"
<3> code scan uses the referenced <<sechub-config-data-section,data>> configuration "firmware-sources"

==== Web scan
`webScan` (optional) defines the web scan settings.

===== URI
Use the `uri` element to define a URI you want to scan.

WARNING: The URI must be whitelisted in your project. Otherwise it will be rejected.
         So you are not able to start scanning foreign domains and do _accidently_ attack them...

====== Example anonymous
[[sechub-config-example-webscan-anonymous]]
[source, json]
----
include::sechub_config_example2_webscan_anonyous.json[]
----
<1> Define web scan
<2> The `URI` to scan. This `URI` must be white listed in `{sechub}` project. Normally without a slash `/` at the end.
<3> *Optional*: Define includes, if you have a special path that is linked nowhere,
	so the scanner can not detect it automatically while crawling the application.
	Always use them starting with a slash (`/`) because they are interpreted relative to the `URI` provided before.
<4> *Optional*: Define excludes, if you have a special path you want to exclude, from the scan.
	Always use them starting with a slash (`/`) because they are interpreted relative to the `URI` provided before.
<5> *Optional*: Define the maximum duration the scan can take. 
    Scanning a "large" web page/application can take several hours or even days. 
    This option ensures the scan will only run for a limited time.
<6> Define the unit of time. 
    The unit can be: `millisecond`, `second`, `minute`, `hour`, `day`.

===== Login
A web scan does work much better if it has got access to all content
 - so a login is necessary most time. If you do not define a login configuration
 your web scan will be done only as anonymous user.

[CAUTION]
====
Providing login will enable web scanner to execute ALL possible
actions!

An example: Your test application has a Web UI for sending SMS which can
be triggered by an user. Then a web scan can trigger those operations as well!

If you do this inside an environment where a real SMS provider is connected,
this could result into mass SMS and also in a bigger invoice from your
SMS provider - *so be careful!*
====

====== Options

SecHub provides you with 2 options for login:

* basic authentication
* form based login
** script based

[NOTE]
====
When a web scan product (or its adapter) does not support your wanted options you
will have a failure at execution time!
====

====== Example no authentication
[source,json]
----
include::sechub_config_example3_webscan_login_basicauth.json[]
----
<1> URL for web login
<2> Basic authentication start, needs user id/name and password.
<3> *Optional*: You can set the realm used for basic authentication. But normally
    this is not necessary.

====== Example basic authentication
[source,json]
----
include::sechub_config_example3_webscan_login_basicauth.json[]
----
<1> URL for web login
<2> Basic authentication start, needs user id/name and password.
<3> You can set the realm used for basic authentication. But normally
    this is not necessary and you can use an empty string.



====== Example form based login by script
[source,json]
----
include::sechub_config_example5_webscan_login_from_sript.json[]
----
<1> URL for web login.
<2> Start of form based login.
<3> Script definition.
<4> Pages section. A page is a visible page. Some logins need more than one page.
<5> The actions which should be executed on each page. 
<6> Type of action. Valid types are : +
    - `username` +
      name of user used for login
    - `password` +
      password entered at login
    - `input` +
      setup value for a field on UI
    - `click` +
      will simulate a mouse click on UI
    - `wait` + 
      time to wait before executing the next action
<7> Selector (CSS) to identify web element.
<8> Value, used by most actions (`username|password|input|wait`). +
    In this examples you see variables
    in `go template` format. This is {sechub} client specific.
    If you use the REST API directly, you must use real values!
<9> A description can be added to explain an action.
<10> The time the next action will be delayed.
<11> Define the unit of time. 
     The unit can be: `millisecond`, `second`, `minute`, `hour`, `day`.

WARNING: `username` and `password` are like input but {sechub} tries
         to hide these information in logs or at UI where possible.
         So do *NOT* use `input` for credentials!

[[sechub-config-example-webscan-openapi]]
====== Example OpenAPI scan
[source,json,title="Open API scan"]
----
include::sechub_config_example8_web_scan_openapi_with_data_reference.json[]
----
<1> name of the source <<sechub-config-data-section,data>> configuration: "open-api-file-reference"
<2> web scan uses "openApi" as API type
<3> web scan uses the referenced <<sechub-config-data-section,data>> configuration "open-api-file-reference"
    to obtain the open api configuration file

==== Infrastructure scan
`infraScan` (optional) defines the infrastructure scan settings.

===== URIs
Use `uris` element to define a string array containing `URIs` you want to scan.


====== Example infrascan one URI
[[sechub-config-example-infrascan-with-uri]]
[source, json]
----
include::sechub_config_example7_infrascan_uri.json[]
----
<1> Define infrastructure scan
<2> The `URI` s to scan. Every `URI` listed here must be white listed in `{sechub}` project.

===== IPs
Use `ips` element to define a string array containing `IPs` you want to scan.

====== Example infrascan one IP
[[sechub-config-example-infrascan-with-ip]]
[source, json]
----
include::sechub_config_example6_infrascan_ip.json[]
----
<1> Define infrastructure scan
<2> The `IP` s to scan. Every `IP` listed here must be white listed in `{sechub}` project.
    The given example with `127.0.0.1` represents only an example and will always not work
    because scanners do not scan them self.

[[sechub-config-data-section]]
==== Data
The <<sechub-config-code-scan,codeScan>> element provides a way to define
source code uploads for code scans only.

With the (optional) `data` section users are able to 

- define binary and source upload information
- reference same uploads by muliple scan types in same job without another upload

The scan configurations can reference the name data configuration elements by defining the an 
array attribute `uses` with a list of unique references names.

[source,json]
----
{
    // ..scan definition
    "use" : [ "reference-name-1","reference-name-2", ... ] //<1>
}
----
<1> the list of referenced data configurations . The referenced names must exist.

Here are some links to examples which are using <<sechub-config-data-section,data>> inside their configurations:

- <<sechub-config-example-licensescan-binary,License scan for binaries>> 
- <<sechub-config-example-licensescan-sources,License scan for sources>> 
- <<sechub-config-example-licensescan-combined-with-codescan,License scan for sources combined with code scan>> 
- <<sechub-config-example-webscan-openapi,OpenAPI web scan>> 

TIP: If you want to upload binaries, you MUST use the data section, there is no other way to do this.

===== General JSON syntax 
The next figure shows an example which presents all possibilities _(for simplicity the source and 
binary configuration arrays do contain only just one entry)_.

[source, json, title="General JSON syntax"]
----
include::sechub_config_data_section_general_example1.json[]
----

<1> `data`: The main element for data configuration.
<2> `sources`: Inside this array multiple source data definitions can be listed
<3> `name`:  Is a unique name for the data configuration element. The name must
    be unique inside complete sechub configuration file! Allowed characters are
     - `a-z`
     - `0-9`
     - `-`
     - `_`
<4> `fileSystem`: Describes fileystem parts which are available inside this data configuration element
<5> `files`: An array containing file pathes to use for uploading dedicated files
<6> `folders`: An array containing folder pathes to use for uploading dedicated folders
<7> `excludes`: Exclude directories (optional) - see <<sechub-config-example-sourcescan,code scan >> 
for details. The excludes work for sources and binaries the same way.
<8> `additionalFilenameExtensions` Introduce additional file name extensions. See <<sechub-config-example-sourcescan,code scan >>
for details about default behaviour for sources. 
<9> `sources`: Inside this array multiple binary data definitions can be listed.

