/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 */

project.apply plugin: 'org.openrewrite.rewrite'

rewrite {
  activeRecipe('com.mercedesbenz.sechub.openrewrite.SanityCheck')
  exclusions.addAll('**/gen/src/main**')
  setExportDatatables(true)
  setFailOnDryRunResults(true)
}

dependencies {
    rewrite(platform("org.openrewrite.recipe:rewrite-recipe-bom:3.18.0"))
    rewrite("org.openrewrite.recipe:rewrite-migrate-java:3.21.1")
    rewrite("org.openrewrite.recipe:rewrite-java-security:3.20.0")
    rewrite("org.openrewrite.recipe:rewrite-rewrite:0.15.0")
    rewrite("org.openrewrite.recipe:rewrite-spring:6.18.0")
    rewrite("org.openrewrite.recipe:rewrite-static-analysis:2.21.0")
    rewrite("org.openrewrite.recipe:rewrite-third-party:0.30.0")
}
