// SPDX-License-Identifier: MIT
:nessus: Nessus
:netsparker: Netsparker
:checkmarx: Checkmarx

== Security Products

TIP: You must only setup those products you have listed inside your
     profiles. See <<section-initial-profile-and-executors,execution profiles and executor configurations>>

=== {pds}
==== General
The {pds} adapters can communicate with the {pds} instances which delegates to the underlying
security products.

Via {pds} every security product, even simple CLI tools, can be easily integrated
into {sechub}.

Please look into `Product delegation server` documentation for more information about the {pds} in common.


==== PDS solutions
There are already ready to use {pds} implementations available - we call them "{pds} solutions".

Every {pds} solution does work out of the box and provide the possibility to start in following three flavors:

- docker (single instance)
- docker compose (cluster)
- helm charts (k8s cluster)

The next sub chapters list the current implementations:

===== GoSec
The PDS integration of https://securego.io[GoSec] (SAST) can be found at
https://github.com/mercedes-benz/sechub/tree/develop/sechub-pds-solutions/gosec

===== Multi
This solution does integrate multiple SAST tools:

- https://github.com/PyCQA/bandit[Bandit]
- https://dwheeler.com/flawfinder/[FlawFinder]
- https://github.com/MobSF/mobsfscan[mobsfscan]
- https://github.com/ajinabraham/njsscan[njsscan]

It can be found at https://github.com/mercedes-benz/sechub/tree/develop/sechub-pds-solutions/multi

===== OWASP ZAP
This solution does integrate the https://www.zaproxy.org/ (web application scanner) - please look at
https://github.com/mercedes-benz/sechub/blob/develop/sechub-pds-solutions/owaspzap/

===== PMD
https://pmd.github.io/ stand normally for quality checks, but it does also provide some security check mechanism. The integration can be found at
https://github.com/mercedes-benz/sechub/tree/develop/sechub-pds-solutions/pmd

===== ScanCode
Implements https://github.com/nexB/scancode-toolkit as a license scan tool:
https://github.com/mercedes-benz/sechub/tree/develop/sechub-pds-solutions/scancode

=== {checkmarx}

==== What does the adapter do?
include::../shared/adapter/checkmarx_adapter_flow.adoc[]

===== What must be done on {checkmarx} UI
. At the moment you have create initial a {checkmarx} team which will be used for {sechub} scans
. If users shall have access to {checkmarx} UI you must add them to used {checkmarx} team (manual)


===== What can be configured for SecHub ?

====== Environment
Please look at <<section-gen-config-scope-checkmarx,checkmarx config>>  section.

====== Runtime
WARNING: Standard properties (like base URL, user id etc.) are currently NOT used from
         existing product executor configurations but only the environment configuration is used at the moment.

[options="header",cols="1,1,1"]
|===
|Parameter                   |Type     |Description
//--------------------------------------------------
|checkmarx.fullscan.always   |boolean  |When 'true' every scan will be done as a full scan and delta scan is not used.

                                        Use this only where a delta scan is not possible/ always rejected by checkmarx.
                                        When 'false' or any other value, delta scan feature is used.

                                        _If a scan fails because checkmarx has detected too many changes there will be a
                                        retry with fullscan. If you have permanent problems with delta scanning for a
                                        project you should set this option to 'true' in your checkmarx executor
                                        configuration._


|===

==== Summary
. Projects are initially created and reused automatically
. Old scans are *NOT* automatically deleted
. Multi tenancy is currently problematic: Same Team ID is always used
  _(will be changed with https://github.com/mercedes-benz/sechub/issues/58[Issue 58])_

// TODO 2019-10-02, Albert Tregnaghi: change here and text block before when team id handling is improved
IMPORTANT: Fix team ID will change in future to provide grouping of results in
           product(for multi tenancy).


=== {netsparker}

==== What does the adapter do?

include::../shared/adapter/netsparker_adapter_flow.adoc[]


==== What must be done on {netsparker} UI

===== Users
- Users must be manual created at {netsparker} UI
- Users must be added to the {netsparker} team used by {sechub}
- If you want to have multi tenancy you have to define website groups
  (see https://github.com/mercedes-benz/sechub/issues/59 for details)

==== Summary
. Websites are initially created and reused automatically
. Old scans are *NOT* automatically deleted

IMPORTANT: Currently {netsparker} adapter will always use ONE team user (admin) to
           create scans. The current logical structure of {netsparker} permissions
           gives all assigned users access to all scans! Keep this in mind.

=== Nessus

==== What does the adapter do?

include::../shared/adapter/nessus_adapter_flow.adoc[]

==== What must be done on {nessus} UI
- define the {nessus} policy UUID

==== Summary
. At the moment only one {nessus} policy UUID is used
. Every scan has got its own name which starts with {sechub} job UUID
. Old scans are *NOT* automatically deleted
