// SPDX-License-Identifier: MIT
=== Migration steps

==== Database
[WARNING]
====
Normally all updates in database are done by our flyway script automatically!

It is very uncommon to do something manually here. Every manual changes will be described why no
automation was possible!
====

[options="header",cols="1,3,4,4"]
|===
| Nr.                    | What                                                              | Why manual?                                           | Apply to version   
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| {counter:migrationNr}  | <<section-migration-spring-batch-477,post handle CVE-2020-5411>>  | Table to update does not exist on new started servers | Initial run < v0.19.0-server

|===
    

[[section-migration-spring-batch-477]]
===== Post handle CVE-2020-5411 

Script to prepare old jobs for Spring batch CVE-2020-5411 changes
  
With Server v0.19.0 we upgraded our Spring Boot dependencies footnote:update_0_19_0[https://github.com/Daimler/sechub/issues/472] but this led to cancelation problems on older jobs - 
this led to problems when deleting older jobs still running.footnote:problem_499[https://github.com/Daimler/sechub/issues/499]

The solution is to execute following `SQL` script on all environments:
[source,sql]
----
UPDATE batch_job_execution_context SET short_context='{"@class":"java.util.HashMap"}' WHERE short_context ='{}'<1>
----
<1> Migrate old (and empty) Spring Batch execution context JSON to correct format: an empty `HashMap`



Unfortunately it is not possible to automatically migrate the data by `flyway` script, because this would fail any new started server, because
a flyway update script would lead to:

``` java
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "BATCH_JOB_EXECUTION_CONTEXT" not found; SQL statement:
```

