[[rules]]
id = "kubernetes-certificate-or-client-data-base64"
description = "Detected kubernetes certificate or client data base64 encoded."
regex = '''\b((?:certificate-authority-data|client-certificate-data|client-key-data)(\s*)(:)(\s*)([-A-Za-z0-9+/]*={0,3}))\b'''
keywords = [
    "certificate-authority-data","client-certificate-data","client-key-data",
]