@startuml

'Hide empty parts:
hide empty fields
hide empty methods

'You can find more examles at https://plantuml.com/class-diagram



node InfralightPDS as "Infralight PDS" {

	database filesystem {
	
	}
	node script as "Infralight launcher script" {
	}


	component product1 {
	}
	
	component product2 {
	}
	script --> product1 : calls
	script --> product2 : calls
	script --> wrapper : calls
	
	product1 ....> filesystem
	product2 ....> filesystem
	wrapper <....> filesystem


	node wrapper {
	
		class SarifSchema {
		}
	
		class InfralightProductImporter {
		}
		
		
		class InfralightProductImportFilter {
		}
		
		InfralightProductImporter -> InfralightProductImportData : imports
		InfralightProductImportFilter ..> InfralightProductImportData : filters
		InfralighProductImportService --> InfralightProductImportStringDataProvider
		
		
		InfralighProductImportService --> InfralightProductImporter : uses
		InfralighProductImportService -> InfralightProductImportFilter: uses
	}

}
@enduml
