// SPDX-License-Identifier: MIT

package cli

/* Attention!
======================== 
DO NOT CHANGE THIS FILE!
======================== 
"constants_filepatterns_gen.go" is automatically generated by gradle genGo task


To avoid compile errors etc. when developers aren't aware about the generation and just doing
an import of the project into their IDE, we decided to NOT add to .gitgnore, but add this code
to git repository even when its generated  */

// DefaultZipAllowedFilePatterns - Defines file patterns to include in zip file.
// These patterns are considered as source code to be scanned.*/
var DefaultZipAllowedFilePatterns = []string{
    ".apex", ".apexp", ".component", ".object", ".page", ".report", ".tgr", ".trigger", ".workflow", /* Apex */
    ".asp", /* ASP (Active Server Pages) */
    ".ascx", ".aspx", /* ASP */
    ".c", ".c++", ".cc", ".cpp", ".cxx", ".h", ".h++", ".hh", ".hpp", ".hxx", /* C/C++ */
    ".bas", ".cls", ".cs", ".cshtml", ".csproj", ".ctl", ".dsr", ".frm", ".sln", ".vb", ".vbp", ".vbs", ".xaml", /* C#, VB.NET, Visual Basic, VB Script */
    ".go", /* Go, Protobuf */
    ".groovy", ".gsh", ".gvy", ".gy", /* Groovy */
    ".htm", ".html", /* HTML */
    ".hbs", ".java", ".javasln", ".jsp", ".jspf", ".project", ".properties", ".tag", ".tld", /* Java ecosystem */
    ".js", ".json", ".jsx", /* JavaScript */
    ".kt", ".kts", /* Kotlin */
    ".m", ".swift", ".xib", /* Objective C, Swift */
    ".pl", ".plx", ".pm", ".psgi", /* Perl */
    ".ctp", ".php", ".php3", ".php4", ".php5", ".php5.6", ".phtm", ".phtml", ".tpl", ".twig", /* php */
    ".pck", ".pkb", ".pkh", ".pks", ".pls", ".sql", /* PL/SQL */
    ".py", ".py2", ".py3", ".pyi", ".python", /* Python, Django */
    ".erb", ".rb", ".rhtml", ".rjs", ".rxml", /* Ruby */
    ".conf", ".sc", ".scala", /* Scala */
    ".ts", ".tsx", /* Typescript/Angular */
    ".build", ".cgi", ".config", ".inc", ".xml"} /* Others */
