// SPDX-License-Identifier: MIT
package cli
const EXIT_CODE_OK=0
const EXIT_CODE_FAILED=1
const EXIT_CODE_MISSING_PARAMETER = 3
const EXIT_CODE_MISSING_CONFIGFILE = 4
const EXIT_CODE_HTTP_ERROR = 5
const EXIT_CODE_ILLEGAL_ACTION = 6
const EXIT_CODE_MISSING_CONFIGPARTS = 7

const DEFAULT_SECHUB_CONFIG_FILE = "sechub.json"

const ACTION_EXECUTE_SYNCHRON="scan"
const ACTION_EXECUTE_ASYNCHRON="scanAsync"
const ACTION_EXECUTE_GET_STATUS="getStatus"
const ACTION_EXECUTE_GET_REPORT="getReport"

const EXECUTION_STATE_ENDED="ENDED"
const EXECUTION_RESULT_FAILED="FAILED"