apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 49%
  selector:
    matchLabels:
      name: {{ .Values.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
    spec:
      containers:
        # Web-UI container
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          labels:
            name: {{ .Values.name }}
          workingDir: /var/www/html/web-ui
          securityContext:
            runAsUser: 4242  # uid of the application user. (should be same as in the Nginx-Proxy.dockerfile)
            runAsGroup: 4242 # gid of the application group. (should be same as in the Nginx-Proxy.dockerfile)
            fsGroup: 4242    # This gid has write access to the mounted volumes.

        # Nginx container for serving the web-ui
        - name: {{ .Values.reverseProxy.name }}
          image: {{ .Values.reverseProxy.image }}
          labels:
            name: {{ .Values.reverseProxy.name }}
          workingDir: /var/www/html
          securityContext:
            runAsUser: 4242  # uid of the application user. (should be same as in the Nginx-Proxy.dockerfile)
            runAsGroup: 4242 # gid of the application group. (should be same as in the Nginx-Proxy.dockerfile)
            fsGroup: 4242    # This gid has write access to the mounted volumes.
          ports:
          - name: {{ .Values.reverseProxy.name }}
            containerPort: 8443