# SPDX-License-Identifier: MIT

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    name: {{ .Values.name }}
spec:
  type: LoadBalancer
  selector:
  name: {{ .Values.name }}
  ports:
    - name: {{ .Values.service.loadbalancer.port.name }}
      port: {{ .Values.service.loadbalancer.port.number }}
      protocol: TCP
      targetPort: 8443