@startuml
skinparam linetype ortho
hide empty methods
hide empty fields
package com.daimler.sechub.domain.scan.project{
'com.daimler.sechub.domain.scan.project.FalsePositiveJobDataService
   class FalsePositiveJobDataService ##[bold]black {
    ~ScanReportRepository : scanReportRepository
    ~ScanProjectConfigService : configService
    ~FalsePositiveJobDataListValidation : falsePositiveJobDataListValidation
    ~FalsePositiveJobDataConfigMerger : merger
  }
  FalsePositiveJobDataService *-- FalsePositiveJobDataConfigMerger
  FalsePositiveJobDataService -[#blue]- FalsePositiveJobDataList
  FalsePositiveJobDataService *-- FalsePositiveJobDataListValidation
  FalsePositiveJobDataService -[#blue]- FalsePositiveProjectConfiguration
  FalsePositiveJobDataService *-- ScanProjectConfigService
  FalsePositiveJobDataService *-- com.daimler.sechub.domain.scan.report.ScanReportRepository
'com.daimler.sechub.domain.scan.project.FalsePositiveJobDataConfigMerger
   class FalsePositiveJobDataConfigMerger{
  }
  FalsePositiveJobDataConfigMerger .[#green]. com.daimler.sechub.commons.model.SecHubCodeCallStack
  FalsePositiveJobDataConfigMerger -[#blue]- com.daimler.sechub.commons.model.SecHubFinding
  FalsePositiveJobDataConfigMerger .. FalsePositiveCodePartMetaData
  FalsePositiveJobDataConfigMerger .. FalsePositiveEntry
  FalsePositiveJobDataConfigMerger -[#blue]- FalsePositiveJobData
  FalsePositiveJobDataConfigMerger -[#blue]- FalsePositiveMetaData
  FalsePositiveJobDataConfigMerger -[#blue]- FalsePositiveProjectConfiguration
  FalsePositiveJobDataConfigMerger -[#blue]- com.daimler.sechub.domain.scan.report.ScanSecHubReport
'com.daimler.sechub.domain.scan.project.FalsePositiveJobDataList
   class FalsePositiveJobDataList{
    -String : apiVersion
    -String : type
    -FalsePositiveJobData : jobData
  }
  FalsePositiveJobDataList -[#blue]- FalsePositiveJobData
'com.daimler.sechub.domain.scan.project.FalsePositiveProjectConfiguration
   class FalsePositiveProjectConfiguration{
    -List<FalsePositiveEntry> : falsePositives
  }
  FalsePositiveProjectConfiguration -[#blue]- FalsePositiveEntry
'com.daimler.sechub.domain.scan.project.ScanProjectConfigService
   class ScanProjectConfigService{
    ~ScanProjectConfigRepository : repository
  }
  ScanProjectConfigService -[#blue]- ScanProjectConfig
  ScanProjectConfigService *-- ScanProjectConfigRepository
'com.daimler.sechub.domain.scan.project.FalsePositiveJobData
   class FalsePositiveJobData{
    -UUID : jobUUID
    -String : comment
  }
'com.daimler.sechub.domain.scan.project.FalsePositiveCodePartMetaData
   class FalsePositiveCodePartMetaData{
    -String : location
    -String : relevantPart
    -String : sourceCode
  }
'com.daimler.sechub.domain.scan.project.FalsePositiveEntry
   class FalsePositiveEntry{
    -FalsePositiveJobData : jobData
    -String : author
    -FalsePositiveMetaData : metaData
    -Date : created
  }
  FalsePositiveEntry -[#blue]- FalsePositiveJobData
  FalsePositiveEntry -[#blue]- FalsePositiveMetaData
'com.daimler.sechub.domain.scan.project.FalsePositiveMetaData
   class FalsePositiveMetaData{
    -ScanType : scanType
    -String : name
    -Severity : severity
    -FalsePositiveCodeMetaData : code
    -FalsePositiveWebMetaData : web
    -Integer : cweId
    -String : cveId
    -String : owasp
  }
  FalsePositiveMetaData -[#blue]- com.daimler.sechub.commons.model.ScanType
  FalsePositiveMetaData -[#blue]- com.daimler.sechub.commons.model.Severity
  FalsePositiveMetaData -[#blue]- FalsePositiveCodeMetaData
  FalsePositiveMetaData -[#blue]- FalsePositiveWebMetaData

'com.daimler.sechub.domain.scan.project.FalsePositiveCodeMetaData
   class FalsePositiveCodeMetaData{
    -FalsePositiveCodePartMetaData : start
    -FalsePositiveCodePartMetaData : end
  }
  FalsePositiveCodeMetaData *-- FalsePositiveCodePartMetaData
'com.daimler.sechub.domain.scan.project.FalsePositiveWebMetaData
   class FalsePositiveWebMetaData{
    -FalsePositiveWebRequestMetaData : request
    -FalsePositiveWebResponseMetaData: response
  }
  FalsePositiveWebMetaData *-- FalsePositiveWebRequestMetaData
  FalsePositiveWebMetaData *-- FalsePositiveWebResponseMetaData
'com.daimler.sechub.domain.scan.project.FalsePositiveWebRequestMetaData
   class FalsePositiveWebRequestMetaData{
    -String: method
    -String: target
    -String: protocol
    -String: version
    -String: attackVector
    
  }
  
  'com.daimler.sechub.domain.scan.project.FalsePositiveWebResponseMetaData
   class FalsePositiveWebResponseMetaData{
    -String: evidence
    -int: statuscode
  }
@enduml
