' SPDX-License-Identifier: MIT
@startuml 
hide empty fields
hide empty members

enum SecHubMessageType {
    ERROR
    WARNING
    INFO
}

class SecHubMessage {
    SecHubMessageType type
    String text
    
}

class AdapterExecutionResult{
    List<SecHubMessage> getProductMessages()
    String getProductResult()
}
abstract class AbstractProductExecutor implements ProductExecutor{
    updateCurrentProductResult(AdapterExecutionResult, ...)
}

class SecHubMessagesList {
    <<JSONable>>
    
    List<SecHubMessage> getSecHubMessages()
}

class Adapter{
    
}

class ProductResult {
    <<Entity>>
    String messages
    String result
}
SecHubMessage o-- SecHubMessageType : has

AdapterExecutionResult -> SecHubMessage : 1...n

AbstractProductExecutor ---> Adapter : calls (1)
AbstractProductExecutor -> SecHubMessagesList : creates (2)
AbstractProductExecutor ---> ProductResult : updates (3)
Adapter --> AdapterExecutionResult: returns


note right of ProductResult::messages 
Contains SecHubMessagesList 
as JSON after update
by AbstractProductExecutor 
end note


@enduml 