@startuml
' SPDX-License-Identifier: MIT

skinparam actorStyle awesome
actor User
participant "SecHub" as secuhb
participant "Product + PDS" as pds

User -> secuhb : Uploads files
secuhb -> pds : Uploads files
pds -> secuhb : Gets result
secuhb -> User : Download report

@enduml