' SPDX-License-Identifier: MIT
@startuml

'Hide empty parts:
hide empty fields
hide empty methods

'You can find more examples at https://plantuml.com/class-diagram

package com.mercedesbenz.sechub.adapter {

	interface AdapterMetaDataCallback{
		AdapterMetaData getMetaDataOrNull()
		persist(AdapterMetaData data)
	}
	
	class AdapterMetaData {
		setValue(String key, String value)
		String getValue(String key)
	}
	
	interface Adapter {
		AdapterExecutionResult start(C config, AdapterMetaDataCallback callback)
	}
	
	class PDSAdapterV1 implements Adapter{
		
	}
}


package com.mercedesbenz.sechub.domain.scan {
	 
	 
	class ScanService {
		startScan()
	} 
	
	class ScanJobExecutor{
	}
	 
	class ProductResult {
		UUID getSecHubJobUUID()
		UUID getProductExecutorConfigUUID()
		
	}
	
	class AbstractProductExecutionService {
		runOnExecutorWithOneConfiguration()
	}
	
	interface ProductExecutor {
		execute(SecHubExecutionContext context, P param)
	}
	
	interface ProductExecutorCallback extends AdapterMetaDataCallback{
		ProductResult getProductResult()
	}
	class ProductExecutorContextFactory
	class ProductExecutorCallbackImpl implements ProductExecutorCallback

	class ScanJobExecutionRunnable {
		
	}
}



note top of PDSAdapterV1
If meta data is available, the PDS adapter tries to fetch
former PDS job UUID from meta data of product result.

If the PDS job uuid is null, a new PDS job is created, otherwise the 
existing PDS job will be reused and the the current state handled.   
end note

ProductExecutorContextFactory -> ProductExecutorCallbackImpl : creates
AbstractProductExecutionService -> ProductExecutorContextFactory: calls to create callback instance
AbstractProductExecutionService "1" *-- "many" ProductExecutor
ProductExecutorCallback --> AdapterMetaData : provides

ProductResult <-- AbstractProductExecutionService : loads former product result for same executor and sechub job uuid
PDSAdapterV1 --> AdapterMetaData : stores and reads
PDSAdapterV1  -> AdapterMetaDataCallback: uses

ProductExecutor  -> Adapter : uses to communicate

ScanJobExecutionRunnable --> AbstractProductExecutionService: calls multiple implementations  

package com.mercedesbenz.sechub.domain.schedule {

	class ScheduleMessageHandler {
		handleJobRestartRequested()
	}
	
	class SchedulerRestartJobService {
		restartJob(UUID jobUUID, String ownerEmailAddress)
		- markJobAsNewExecutedNow(ScheduleSecHubJob secHubJob)
	}
	
	class ScheduleJobLauncherService {
	 	executeJob(ScheduleSecHubJob secHubJob) 
	}
}


package com.mercedesbenz.sechub.domain.administration {


	class JobRestartRequestService{
		restartJob(UUID sechubJobUUID) 
	}
}

class DomainMessageService {
}

JobRestartRequestService -[bold,#blue]> DomainMessageService: (1) REQEUST RESTART JOB (soft)
DomainMessageService -[bold,#blue]> ScheduleMessageHandler  : (2) REQEUST RESTART JOB (soft) 
ScheduleMessageHandler -[bold,#blue]> SchedulerRestartJobService

SchedulerRestartJobService -[bold,#green]> ScheduleJobLauncherService

ScheduleJobLauncherService -[bold,#green]> DomainMessageService : (3) START_SCAN (synchron)

DomainMessageService -[bold,#green]> ScanService: (4) START_SCAN (synchron)


ScanService -[bold,#green]> ScanJobExecutor

ScanJobExecutor  -> ScanJobExecutionRunnable 
@enduml
