@startuml

'Hide empty parts:
hide empty fields
hide empty methods

'You can find more examples at https://plantuml.com/class-diagram

package com.mercedesbenz.sechub.domain.scan {
	
	class ScanProgressMonitor 
	 
	class ScanJobExecutor {
	
	}
	 
	class ScanJobExecutionRunnable{
	
	}
	class ScanMessageHandler
}



package com.mercedesbenz.sechub.domain.schedule {

	class ScheduleMessageHandler {
		handleJobRestartRequested()
	}
	
	class SynchronSecHubJobExecutor {
	}
	
	class SchedulerTerminationService {
	   void terminate()
	   boolean isTerminating()
	}
	
	class SchedulerJobBatchTriggerService {
	   void triggerExecutionOfNextJob()
	}
	
	database DB {
    	entity ScheduleSecHubJob {
    	}
	}
	
}

SchedulerJobBatchTriggerService ..> SchedulerTerminationService 
SchedulerTerminationService -> ScheduleSecHubJob : persists with execution state\n`SUSPENDED`

node EventBus {
}

node springcontainer as "Spring boot container" {
}

springcontainer ..> SchedulerTerminationService: PreDestroy\ncalls terminate()

note top of SchedulerJobBatchTriggerService
Blocks execution of any new jobs 
inside the scheduler instance when
isTerminating() returns true
end note 

note bottom of SchedulerTerminationService
Only the schedule domain is allowed to update
the job state! After the job state TODO
end note

@enduml
