# SPDX-License-Identifier: MIT

version: "3"
services:
  pds-multi:
    build:
      args:
        - BASE_IMAGE=debian:12-slim
      context: docker/
      dockerfile: Multi-Debian.dockerfile
    container_name: pds-multi
    hostname: pds-multi
    volumes:
      - ./docker/scripts:/scripts
    env_file:
      - .env
    networks:
      - "sechub"

networks:
  sechub:
    external: true
    name: "sechub"
