# SPDX-License-Identifier: MIT

version: "3"
services:
  pds-multi:
    build:
      args:
        - BASE_IMAGE=${BASE_IMAGE}
      context: docker/
      dockerfile: Multi-Debian.dockerfile
    container_name: pds-multi
    env_file:
      - .env
      - .env-single
    volumes:
      - ./docker/scripts:/scripts
    ports:
      - "127.0.0.1:8444:8444"
      - "127.0.0.1:15024:15024"
    networks:
      - "internal"
networks:
  internal:
