# SPDX-License-Identifier: MIT

version: "3"
services:
  pds-multi:
    build:
      args:
        - BASE_IMAGE=debian:11-slim
      context: docker/
      dockerfile: Multi-Debian.dockerfile
    env_file:
      - .env-cluster
    networks:
      - "internal"
    volumes:
      - "shared_volume:/shared_volumes/uploads:rw"
      - ./docker/scripts:/scripts
    depends_on:
      - database

  loadbalancer:
    build:
      context: ../shared/docker/loadbalancer
      args:
        - PDS_SOLUTION=pds-multi
    env_file:
      - .env-cluster
    networks:
      - "internal"
    depends_on:
      - pds-multi
    ports:
      - "127.0.0.1:8444:8444"

  database:
    build:
      context: ../shared/docker/database
    env_file:
      - .env-cluster
    networks:
      - "internal"
    ports:
      - "127.0.0.1:5432:5432"

networks:
  internal:

volumes:
  shared_volume:
