# SPDX-License-Identifier: MIT
# Number of pds-gosec instances to spin up
replicaCount: 1

image:
  registry: "{{ .PDS_GOSEC_IMAGE_REGISTRY }}"
  tag: "{{ .PDS_GOSEC_IMAGE_TAG }}"
  # See https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy
  pullPolicy: "Always"

pds:
  heartbeatLogging: "false"

users:
  technical:
    id: "techuser"
    apiToken: "{{ .PDS_GOSEC_TOKEN_TECHUSER }}"
  admin:
    id: "admin"
    apiToken: "{{ .PDS_GOSEC_TOKEN_ADMINUSER }}"
