// SPDX-License-Identifier: MIT
include::launchconfig_common_dev_adminui_header.adoc[]

----
-Dsechub.developertools.admin.server=localhost <1>
-Dsechub.developertools.admin.serverport=8443<2>
-Dsechub.developertools.admin.integrationtestserver=true <3>
-Dsechub.developertools.admin.serverprotocol=https<4>
----

Environment entries:
----
SECHUB_ADMIN_USERID=int-test_superadmin<5>
SECHUB_ADMIN_APITOKEN=int-test_superadmin-pwd<5>
----

[[section-developer-adminui-setup]]

TIP: We use environment variables for credentials because otherwise everybody
     able to list running processes can see the user id and API token...

<1> Please replace this with your server location. For development `localhost`
<2> *Optional:* This is the server port - default
    is `443`. For development servers at your local machine
    you should normally set to `8443`.
<3> *Optional:* Enable special integration test actions - e.g. create test data, start jobs
    etc.
<4> *Optional:* Per default `https` will be used. If you have started (not recommended) {sechub}
    with `SSL` disabled and spring security disabled
<5> These are the credentials used for administrative access. For integration
    tests we got fix credentials - *so never use in production!*



