package com.mercedesbenz.sechub.pds.commons.core.config;

public class PDSStorageConstantsEnvironmentVariables {
    /* shared volume */
    public static final String ENV_PDS_STORAGE_SHAREDVOLUME_UPLOAD_DIR = "PDS_STORAGE_SHAREDVOLUME_UPLOAD_DIR";

    /* s3 */
    public static final String ENV_PDS_STORAGE_S3_ACCESSKEY = "PDS_STORAGE_S3_ACCESSKEY ";

    public static final String ENV_PDS_STORAGE_S3_SECRETKEY = "PDS_STORAGE_S3_SECRETKEY";

    public static final String ENV_PDS_STORAGE_S3_BUCKETNAME = "PDS_STORAGE_S3_BUCKETNAME";

    public static final String ENV_PDS_STORAGE_S3_ENDPOINT = "PDS_STORAGE_S3_ENDPOINT";

    public static final String ENV_PDS_STORAGE_S3_TIMEOUT_CONNECTION_MILLISECONDS = "PDS_STORAGE_S3_TIMEOUT_CONNECTION_MILLISECONDS";

    public static final String ENV_PDS_STORAGE_S3_TIMEOUT_SOCKET_MILLISECONDS = "PDS_STORAGE_S3_TIMEOUT_SOCKET_MILLISECONDS";

    public static final String ENV_PDS_STORAGE_S3_TIMEOUT_REQUEST_MILLISECONDS = "PDS_STORAGE_S3_TIMEOUT_REQUEST_MILLISECONDS";

    public static final String ENV_PDS_STORAGE_S3_TIMEOUT_EXECUTION_MILLISECONDS = "PDS_STORAGE_S3_TIMEOUT_EXECUTION_MILLISECONDS";

    public static final String ENV_PDS_STORAGE_S3_CONNECTION_MAX_POOLSIZE = "PDS_STORAGE_S3_CONNECTION_MAX_POOLSIZE";

    public static final String ENV_PDS_STORAGE_S3_CONNECTION_TTL_MILLISECONDS = "PDS_STORAGE_S3_CONNECTION_TTL_MILLISECONDS";

    public static final String ENV_PDS_STORAGE_S3_CONNECTION_IDLE_MAX_MILLISECONDS = "PDS_STORAGE_S3_CONNECTION_IDLE_MAX_MILLISECONDS";

    public static final String ENV_PDS_STORAGE_S3_CONNECTION_IDLE_VALIDATE_MILLISECONDS = "PDS_STORAGE_S3_CONNECTION_IDLE_VALIDATE_MILLISECONDS";

    public static final String ENV_PDS_STORAGE_S3_SIGNER_OVERRIDE = "PDS_STORAGE_S3_SIGNER_OVERRIDE";

}
