# SPDX-License-Identifier: MIT

version: "3"
services:
  sechub:
    build:
      args:
        - BASE_IMAGE=debian:12-slim
        - BUILD_TYPE=${BUILD_TYPE}
        - JAVA_DISTRIBUTION=${JAVA_DISTRIBUTION}
        - JAVA_VERSION=${JAVA_VERSION}
        - SECHUB_VERSION=${SECHUB_VERSION}
        - GO=${GO}
        - TAG=${TAG}
        - BRANCH=${BRANCH}
      context: docker/
      dockerfile: SecHub-Debian.dockerfile
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT}
          cpus: ${CPU_LIMIT}
    env_file:
      - .env
      - .env-cluster
    networks:
      - "sechub"
    volumes:
      - "shared_volume:/shared_volumes/uploads"
    depends_on:
      - database

  loadbalancer:
    build:
      context: supporting/loadbalancer
    env_file:
      - .env-cluster
    networks:
      - "sechub"
    depends_on:
      - sechub
    ports:
      - "127.0.0.1:8443:8443"

  database:
    build:
      context: supporting/database
    env_file:
      - .env-cluster
    networks:
      - "sechub"
    ports:
      - "127.0.0.1:5432:5432"

networks:
  sechub:
    name: sechub

volumes:
  shared_volume:
