// SPDX-License-Identifier: MIT

= SecHub Solution

This folder contains the scripts to run SecHub in a container.

== Local Container

=== Single Container

To start a single container run the script:

----
./01-start-single-docker-compose.sh
----

=== Single Container with Prepare (remote Data)

. Adjust the `docker-compose_sechub-debiian-prepare.yml` file and replace <user> with your linux home directory. +
Make sure the ./sechub/shared_volume folder exists and is writable for the docker. If not create the directory and execute `sudo chmod -R 777 ./sechub/sharedvolume`. +
This mounted NFS must be the same directory as the NFS directory in the PDS prepare (/pds-solutions/prepare/docker-compose-prepare_external-network.yml.

. Start the container with the script:

----
./01-start-single-docker-compose-prepare.sh
----

=== SecHub with PDS Solution

. First start a SecHub container.

. Most of the PDS Solutions have a script which starts with `05-*`. Execute this script next.

. Run one of the PDS setup scripts. For example: `setup-pds/setup-gosec.sh` to setup a GoSec project.

. Use the SecHub Client to scan.

== Build Container

Coming soon.

== Kubernetes

Coming soon.

