// SPDX-License-Identifier: MIT
export function getPrismLanguageFromFileExtension(location: string): string | undefined {
	const fileName = location.split('/').pop() || '';
	const fileExtension = fileName.split('.').pop()?.toLowerCase() || '';
	switch (fileExtension) {
		case 'js':
		case 'mjs':
		case 'cjs':
			return 'javascript';
		case 'ts':
		case 'tsx':
			return 'typescript';
		case 'html':
		case 'htm':
		case 'svelte':
			return 'html';
		case 'css':
			return 'css';
		case 'scss':
			return 'scss';
		case 'less':
			return 'less';
		case 'xml':
		case 'svg':
		case 'rss':
		case 'atom':
			return 'xml';
		case 'json':
			return 'json';
		case 'md':
		case 'markdown':
			return 'markdown';
		case 'java':
			return 'java';
		case 'py':
			return 'python';
		case 'c':
			return 'c';
		case 'cpp':
		case 'cc':
		case 'cxx':
		case 'h':
		case 'hpp':
		case 'hxx':
			return 'cpp';
		case 'cs':
			return 'csharp';
		case 'php':
			return 'php';
		case 'rb':
			return 'ruby';
		case 'swift':
			return 'swift';
		case 'go':
			return 'go';
		case 'kotlin':
			return 'kotlin';
		case 'sql':
			return 'sql';
		case 'yaml':
		case 'yml':
			return 'yaml';
		case 'dockerfile':
			return 'docker';
		case 'gitignore':
			return 'git';
		case 'jsx':
			return 'jsx';
		case 'graphql':
			return 'graphql';
		case 'wasm':
			return 'wasm';
		case 'lua':
			return 'lua';
		case 'perl':
		case 'pl':
			return 'perl';
		case 'r':
			return 'r';
		case 'dart':
			return 'dart';
		case 'objectivec':
		case 'objc':
			return 'objectivec';
		case 'arduino':
			return 'arduino';
		case 'latex':
		case 'tex':
			return 'latex';
		case 'bash':
		case 'sh':
		case 'zsh':
			return 'bash';
		default:
			return undefined;
	}
}
