// SPDX-License-Identifier: MIT
== Owasp Zap Wrapper

Owasp Zap Wrapper CLI for PDS

=== Usage

The wrapper connection to the zaproxy can be configured by using the command line parameters below. Additionally it is possible to use environment variables like that:
All configurations in a way that the command line parameters always overwrite the environment variables.

----
ZAP_HOST=127.0.0.1
ZAP_PORT=8090
ZAP_API_KEY=change-me
----

To Specify an additional proxy you can set the following environment variables or use the corresponding command line options.

----
PROXY_HOST=127.0.0.1
PROXY_PORT=1234
----

To use the wrapper see the help below:

----
Usage: OwaspZapWrapper [options]
  Options:
    --activeScan
      Set this option to enable Owasp Zap active scan.
      Default: false
    --ajaxSpider
      Set this option to enable Owasp Zap ajaxSpider.
      Default: false
    --fullRulesetfile
      Specify a file with all rules installed for the Owasp Zap.
    --help
      Shows help and provides information on how to use the wrapper.
    --jobUUID
      The Job-UUID, which will be used as internal identifier for the Owasp 
      Zap scan context.
    --proxyHost
      Specify a proxy host. You can also set the environment variable 
      PROXY_HOST, instead of using this parameter.
    --proxyPort
      Specify a proxy port. You can also set the environment variable 
      PROXY_PORT, instead of using this parameter.
      Default: 0
  * --report
      The output file, where the report will be written to.
    --rulesDeactivationfile
      Specify a file with rules to deactivate during the scan inside the Owasp 
      Zap. 
    --sechubConfigfile
      The SecHub config file, containing additonal configurations for the 
      scan. 
  * --targetURL
      Specifies the target url to be scanned.
    --verbose
      Set this option to provide additional output while scanning.
      Default: false
    --zapApiKey
      Specifies the Owasp Zap host api key. You can also set the environment 
      variable ZAP_API_KEY, instead of using this parameter.
    --zapHost
      Specifies the Owasp Zap host address. You can also set the environment 
      variable ZAP_HOST, instead of using this parameter.
    --zapPort
      Specifies the Owasp Zap host port. You can also set the environment 
      variable ZAP_PORT, instead of using this parameter.
      Default: 0
----

==== Deactivate scan rules

To deactivate scan rules you need to specify 2 files using 2 command line arguments.

The first file specified using --fullRulesetfile, 
represents the full ruleset of all installed rules inside the Owasp Zap.
The following snippet is an example of the files structure:
[source,json]
----
{
  "timestamp" : "2022-05-05 15:33:39.190796",
  "origin" : "https://www.zaproxy.org/docs/alerts/",
  "rules" : [{
    "id" : "0",
    "ref" : "Directory-Browsing-0",
    "name" : "Directory Browsing",
    "type" : "active",
    "link" : "https://www.zaproxy.org/docs/alerts/0"
  }, {
    "id" : "2",
    "ref" : "Private-IP-Disclosure-2",
    "name" : "Private IP Disclosure",
    "type" : "passive",
    "link" : "https://www.zaproxy.org/docs/alerts/2"
  }]
}
----

Additionally you need to specify a file with --rulesDeactivationfile,
which represents the rule by using the `ref` part of the file above.
The following snippet is an example of the files structure:
[source,json]
----
{
  "deactivatedRuleReferences" : [{
    "ref" : "Directory-Browsing-0",
    "info" : "Rule was deactivated because of ..."
  }, {
    "ref" : "Private-IP-Disclosure-2",
    "info" : "Rule was deactivated for testing reasons."
  }]
}
----