// SPDX-License-Identifier: MIT
== Zap Wrapper

Zap Wrapper CLI for PDS

=== Usage

The wrapper connection to the zaproxy can be configured by using the command line parameters below. Additionally it is possible to use environment variables like that:
All configurations in a way that the command line parameters always overwrite the environment variables.

----
ZAP_HOST=127.0.0.1
ZAP_PORT=8090
ZAP_API_KEY=change-me
----

To Specify an additional proxy you can set the following environment variables or use the corresponding command line options.

----
PROXY_HOST=127.0.0.1
PROXY_PORT=1234
----

To use the wrapper see the help below:

----
Usage: ZapWrapper [options]
  Options:
    --activeScan
      Set this option to enable Zap active scan.
      Default: false
    --ajaxSpider
      Set this option to enable Zap ajaxSpider.
      Default: false
    --ajaxSpiderBrowserId
      Set the browser id you want to use for the AjaxSpider module. Make sure 
      the browser you want to use is installed on the system running the scan. 
      Supported browsers are: [firefox-headless, firefox, chrome-headless, 
      chrome, htmlunit, safari].
      Default: firefox-headless
    --connectionCheck
      Set this option to enable an initial connection check performed by this 
      wrapper application.
      Default: false
    --deactivateRules
      Specify references of rules you want to deactivate during the scan 
      inside the Zap. If you specify multiple rules use comma separated values 
      like: rule1,rule,rule3
  * --fullRulesetfile
      Specify a file with all rules installed for the Zap.
    --groovyLoginScriptFile
      Groovy script file the ZAP wrapper uses for script based authentication 
      when templates are defined. You can also set the environment variable 
      ZAP_GROOVY_LOGIN_SCRIPT_FILE, instead of using this parameter.
    --help
      Shows help and provides information on how to use the wrapper.
    --jobUUID
      The Job-UUID, which will be used as internal identifier for the Zap scan 
      context. 
    --maxNumberOfConnectionRetries
      Maximum number of times the wrapper tries to reach each URL. Including 
      each URL constructed from the sechub includes.
      Default: 3
    --pdsEventFolder
      Folder where the ZAP wrapper listens for events of the PDS, like cancel 
      requests for the current job. You can also set the environment variable 
      PDS_JOB_EVENTS_FOLDER, instead of using this parameter.
    --pdsUserMessageFolder
      Folder where the user messages are written to. You can also set the 
      environment variable PDS_JOB_USER_MESSAGES_FOLDER, instead of using this 
      parameter. 
    --proxyHost
      Specify a proxy host. You can also set the environment variable 
      PROXY_HOST, instead of using this parameter.
    --proxyPort
      Specify a proxy port. You can also set the environment variable 
      PROXY_PORT, instead of using this parameter.
      Default: 0
  * --report
      The output file, where the report will be written to.
    --retryWaittimeInMilliseconds
      Specify the time to wait between connection retries in milliseconds. The 
      value cannot be less than 1000 milliseconds.
      Default: 1000
    --rulesDeactivationfile
      Specify a file with rules to deactivate during the scan inside the Zap.
    --sechubConfigfile
      The SecHub config file, containing additonal configurations for the 
      scan. 
  * --targetURL
      Specifies the target url to be scanned.
    --verbose
      Set this option to provide additional output while scanning.
      Default: false
    --zapApiKey
      Specifies the Zap host api key. You can also set the environment 
      variable ZAP_API_KEY, instead of using this parameter.
    --zapHost
      Specifies the Zap host address. You can also set the environment 
      variable ZAP_HOST, instead of using this parameter.
    --zapPort
      Specifies the Zap host port. You can also set the environment variable 
      ZAP_PORT, instead of using this parameter.
      Default: 0
----

==== Deactivate scan rules

To deactivate scan rules you need to specify 2 files using 2 command line arguments.

===== Full ruleset file
The first file specified using `--fullRulesetfile`, 
represents the full ruleset of all installed rules inside the Owasp Zap. 
The default file contains all rules of all release status (alpha, beta, release).
The following snippet is an example of the file structure:

[source,json]
----
{
  "timestamp" : "2022-05-13 14:44:00.635104",
  "origin" : "https://www.zaproxy.org/docs/alerts/",
  "rules" : {
    "Directory-Browsing-0" : {
      "id" : "0",
      "name" : "Directory Browsing",
      "type" : "active",
      "link" : "https://www.zaproxy.org/docs/alerts/0"
    },
    "Private-IP-Disclosure-2" : {
      "id" : "2",
      "name" : "Private IP Disclosure",
      "type" : "passive",
      "link" : "https://www.zaproxy.org/docs/alerts/2"
    }
  }
}
----

The file above can be generated using the helper Python script link:src/main/resources/owaspzap-ruleset-helper/owaspzap_ruleset_helper.py[owaspzap_ruleset_helper.py].
Before using this script make sure to install the dependencies using link:src/main/resources/owaspzap-ruleset-helper/requirements.txt[requirements.txt].

If you do not wish to install this on your system, you can use a Python virtual environment.
Please refer to the official https://docs.python.org/3.10/tutorial/venv.html[*documentation*].
Depending on your default Python installation you might need to use `pip3`:

* `pip install -r requirements.txt`

The `owaspzap_ruleset_helper.py` has the following command line options:
----
 -h, --help            show this help message and exit
  --output-file OUTPUT_FILE
  --rule-release-status [{release,beta,alpha} ...]
                        Specify values separated by spaces like: release beta alpha
----

The parameter `--output-file` is required. Make sure the directory exists, since only the file is created if it does not exist.

With `--rule-release-status` you can specify which rules you want to include in the result.
If you do not specify any restrictions, rules of all release status are included.
This means `alpha`, `beta` and `release`. Please specify this values separated by spaces as shown above.


===== Deactivation file

Additionally you need to specify a file with `--rulesDeactivationfile`,
which represents the rule by using the `ref` part of the file above.
For this feature to work, make sure all of the specified rules are installed on your ZAP installation 
and set a file with `--fullRulesetfile` which contains all installed rules. 
The following snippet is an example of the file structure:

[source,json]
----
{
  "deactivatedRuleReferences" : [{
    "ref" : "Directory-Browsing-0",
    "info" : "Rule was deactivated because of ..."
  }, {
    "ref" : "Private-IP-Disclosure-2",
    "info" : "Rule was deactivated for testing reasons."
  }]
}
----

Additionally the rules to deactivate can be specified via command line using `--deactivateRules`. Please use comma separated values like:
----
$ java -jar sechub-pds-wrapperowaspzap-0.30.0.jar --deactivateRules Directory-Browsing-0,Private-IP-Disclosure-2
----
Another possibility to deactivate certain rules is the environment variable `ZAP_DEACTIVATED_RULE_REFERENCES`.
----
ZAP_DEACTIVATED_RULE_REFERENCES=Directory-Browsing-0,Private-IP-Disclosure-2
----
But if the command line parameter `--deactivateRules` is set, the wrapper ignores this environment variable.
The rules to deactivate specified via `--rulesDeactivationfile`, will always be added to the list of deactivated rules.
To set the env variable you can use `zap.deactivation.rule.references=Directory-Browsing-0,Private-IP-Disclosure-2`,
inside the executor config.


==== Groovy Script Login
To handle more complex authentication scenarios, the wrapper uses pre-defined groovy scripts.
The groovy authentication scripts have access to certain data from the wrapper application:

- An initialized selenium `FirefoxDriver` object that can be used directly
- An initialized selenium `WebDriverWait` object that can be used directly, implicitly using the firefox web driver
- An initialized selenium `JavascriptExecutor` object, which on default is the previously introduced `FirefoxDriver` 
- The `SecHubWebScanConfiguration` that was used to configure the scan
- The `TOTPGenerator` that can be used for two-factor-authentication
- The `user` configured for the authentication
- The `password` of the `user`
- The `loginUrl` necessary to authenticate.
- The `targetUrl`, which is the base URL specified for the scan.

The example script below shows how these bindings can be accessed and used. In the example script all bindings are listed, even the ones not used by the script.
The script can also be created completely without using anything of the pre-defined data.

The `TOTPGenerator` is an easy to use implementation of TOTP for two-factor-authentication if necessary. Using `totpGenerator.now()` returns the currently valid TOTP.
To make use of the script authentication the wrapper application expects a SecHub configuration json for the scan, which contains a template data definition and optionally a TOTP configuration.
See web scan example configurations for details.
The following example contains all available bindings, even if they are unused in the script below:

[source,groovy]
----
import static com.mercedesbenz.sechub.zapwrapper.scan.login.ZapScriptBindingKeys.*

import com.mercedesbenz.sechub.zapwrapper.util.TOTPGenerator

import org.openqa.selenium.firefox.FirefoxDriver
import org.openqa.selenium.support.ui.ExpectedConditions
import org.openqa.selenium.By
import org.openqa.selenium.support.ui.WebDriverWait
import org.openqa.selenium.JavascriptExecutor

import com.mercedesbenz.sechub.commons.model.SecHubWebScanConfiguration

// all available bindings
final FirefoxDriver firefox = binding.getVariable(FIREFOX_WEBDRIVER_KEY)
final WebDriverWait webdriverWait = binding.getVariable(FIREFOX_WEBDRIVER_WAIT_KEY)
final JavascriptExecutor javaScriptExecutor = binding.getVariable(JAVASCRIPTEXECUTOR_KEY)
final SecHubWebScanConfiguration sechubWebScanConfig = binding.getVariable(SECHUB_WEBSCAN_CONFIG_KEY)
final TOTPGenerator totpGenerator = binding.getVariable(TOTP_GENERATOR_KEY)

final String user = binding.getVariable(USER_KEY)
final String password = binding.getVariable(PASSWORD_KEY)
final String loginUrl = binding.getVariable(LOGIN_URL_KEY)
final String targetUrl = binding.getVariable(TARGET_URL_KEY)

// example authentication script steps
firefox.get(loginUrl)

webdriverWait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".close-dialog"))).click()
webdriverWait.until(ExpectedConditions.presenceOfElementLocated(By.id("email"))).sendKeys(user)
webdriverWait.until(ExpectedConditions.presenceOfElementLocated(By.id("password"))).sendKeys(password)
webdriverWait.until(ExpectedConditions.presenceOfElementLocated(By.id("loginButton"))).click()
webdriverWait.until(ExpectedConditions.presenceOfElementLocated(By.id("otp"))).sendKeys(totpGenerator.now())
webdriverWait.until(ExpectedConditions.presenceOfElementLocated(By.id("submitOtp"))).click()
----