# SPDX-License-Identifier: MIT

# This is just a sample values file.

replicaCount: 1

image:
    registry: "my.registry.example.org/pds-owasp-zap"
    tag: "latest"

pds:
    startMode: localserver
    javaDebug:
        enabled: false
    keepContainerAliveAfterPDSCrashed: false
    config:
        execute:
            queueMax: 10
            workerThreatCount: 1

zap:
    apiKey: "<random-api-key>"
    proxy:
        host: "127.0.0.1"
        port: "9999"

users:
    technical:
        id: "techuser"
    admin:
        id: "admin"

storage:
    local:
        enabled: true
    s3:
        enabled: false
        endpoint: "https://<minio-or-s3-server>:<port>"
        bucketname: "<my-bucketname>"
        accesskey: "<my-accesskey>"
        secretkey: "<my-secretkey>"
    sharedVolume:
        enabled: false
        upload:
            dir: "/mount/nfs/shares/<sharename>"

database:
    postgres:
        enabled: false
        connection: "jdbc:postgresql://database:5432/pds"
        username: "owaspzap"
        password: "<password-of-db-user>"

networkPolicy:
    enabled: false
    ingress:
    - from:
        - podSelector:
            matchLabels:
                name: sechub-server
        - podSelector:
            matchLabels:
                name: sechub-adminserver
