# SPDX-License-Identifier: MIT

# Title for the gitleaks configuration file.
title = "Gitleaks custom file"

# Extend the base (this) configuration. When you extend a configuration
# the base rules take precedence over the extended rules. I.e., if there are
# duplicate rules in both the base configuration and the extended configuration
# the base rules will override the extended rules.
# Another thing to know with extending configurations is you can chain together
# multiple configuration files to a depth of 2. Allowlist arrays are appended
# and can contain duplicates.
# useDefault and path can NOT be used at the same time. Choose one.
[extend]
# useDefault will extend the base configuration with the default gitleaks config:
# https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml
useDefault = true

[[rules]]
id = "cryptographic-certificate"
description = "Identified a cryptographic certificate, which may compromise cryptographic security and sensitive data encryption."
regex = '''(?i)-----BEGIN[ A-Z0-9_-]{0,100}CERTIFICATE( BLOCK)?-----[\s\S-]*KEY( BLOCK)?----'''
keywords = [
    "-----begin",
]

[[rules]]
id = "kubernetes-certificate-or-client-data-base64"
description = "Detected kubernetes certificate or client data base64 encoded."
regex = '''\b((?:certificate-authority-data|client-certificate-data|client-key-data)(\s*)(:)(\s*)([-A-Za-z0-9+/]*={0,3}))\b'''
keywords = [
    "certificate-authority-data","client-certificate-data","client-key-data",
]

[[rules]]
id = "vehicle-identification-number"
description = "Detected vehicle identification number."
regex = '''\b(?:[^A-HJ-NPR-Z0-9]*|^)([A-HJ-NPR-Z0-9]{17})(?:[^A-HJ-NPR-Z0-9]*|$)\b'''

# The conditions below require the VINs to be a combination of digits and letters, which cannot be guaranteed with the initial pattern
[[rules.allowlists]]
# note: |regexes| defaults to check the _Secret_ in the finding.
# Acceptable values for |regexTarget| are "secret" (default), "match", and "line".
regexTarget = "secret"
regexes = [ '''[0-9]{17}''', '''[A-HJ-NPR-Z]{17}''' ]
