# SPDX-License-Identifier: MIT

apiVersion: v2
name: pds-pmd
description: SecHub PDS + PMD as Helm chart for Kubernetes

maintainers:
  - name: Jeremias Eppler
  - name: Sven Dolderer
  - name: Valentyn Grygoriev

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.7.0
