// SPDX-License-Identifier: MIT
== Secret validation Wrapper

This wrapper is a Spring Boot application, that is supposed to run on PDS solutions performing secret scans.
After the secret scanning tool is done it will try to validate secrets found and enhance the SARIF report with a custom PropertyBag for each finding location.
It will add a custom severity with the key `secretscan.sereco.severity` with
one of the following values `["info", "unclassified", "low", "medium", "high", "critical"]` to a SARIF PropertyBag which contains a generic map for custom values.
This values can then be used by the `sechub-sereco` module to improve the severity categorization of a finding. We add this custom severities with a `PropertyBag` because the SARIF default called `Level` does not support `CRITICAL`.

In case the secret was valid, the key `secretscan.validated.by.url` will be added to the PropertyBag as well with the value containing the URL the secret was valid for.

=== Use wrapper
The wrapper application is an executable jar and needs no command line arguments.

[source, bash]
----
java -jar sechub-wrapper-secretvalidation.jar
----

It needs the following mandatory environment variables set:

[horizontal]
*SECRET_VALIDATOR_CONFIGFILE*::
The file, which must be configured by `SECRET_VALIDATOR_CONFIGFILE`, contains the configuration for each secret type in JSON format which basically tells the wrapper application how to validate secrets of a certain type. +
For each product a custom file is necessary where some kind of finding identifier should be used, like the SARIF `ruleId` to identify each configuration. +
*PDS_JOB_RESULT_FILE*::
This points to the input report file in SARIF format for the secret validation. +
When called from a SecHub PDS then `PDS_JOB_RESULT_FILE` is already defined.
See: https://mercedes-benz.github.io/sechub/latest/sechub-product-delegation-server.html#launcher-scripts[standard PDS environment variables] +
The Secret Validation Wrapper updates this file according to the validation results.

==== Configuration file
Configuration file example:

[source, json]
----
{
  "validatorConfigList": [ <1>
    {
      "ruleId": "sarif-result-rule-id", <2>
      "categorization": { <3>
        "defaultSeverity": "high",
        "validationFailedSeverity": "medium",
        "validationSuccessSeverity": "critical"
      },
      "requests": [ <4>
        {
          "url": "https://api.example.com",
          "proxyRequired": true,
          "verifyCertificate": false,
          "headers": [
            { "name": "Authorization", "valuePrefix": "Bearer" }
          ],
          "expectedResponse": { <5>
            "httpStatus": 200,
            "contains": {
              "allOf": [ "is", "there" ],
              "oneOf": [ "success", "authorized" ]
            }
          }
        }
      ]
    }
  ]
}
----
<1> Define a list of configuration entries. One entry represents a type of secret identified by a dedicated rule id.
<2> The `ruleId` identifies this configuration so the requests defined in the later section are performed for each finding of this type.
<3> The `categorization` configuration. If empty no categorization will be performed, otherwise:
- The `defaultSeverity` will be applied if there are no requests defined for this type of secret.
- The `validationFailedSeverity` will be applied if all validation requests failed for this secret.
- The `validationSuccessSeverity` will be applied if the secret was successfully validated with one of the requests defined.
<4> The `requests` array defines all known requests to validate a secret of this certain type.
This is an array because for some secrets it might be necessary to validate against multiple servers e.g. when a company uses multiple AWS instances.
It might be necessary to perform validation requests to all possible AWS instances to check if a secret is valid for any of them:
- `proxyRequired` specifies if the URL can only be accessed using a proxy server.
- `url` specifies the URL the request will be performed to.
- `headers` specifies the header `name` and `valuePrefix` if necessary for the secret found.
It is an array because it could be useful in the future. Currently the header is used for the secret because it is assumed to be a token send via HTTP header.
<5> The `expectedResponse` section contains information expected on a request with a valid secret,
like a specific `httpStatus` code or the response body should contain `allOf` or `oneOf` certain strings.


Optional environment variables:
[horizontal]
*SECRET_VALIDATOR_MAXIMUMRETRIES*::
The property `secret.validator.maximum-retries` or the corresponding environment variable `SECRET_VALIDATOR_MAXIMUMRETRIES` can be used to specify the number of retries for each of the request, to be more resistant to network issues. The default value is `3`` meaning in the worst case scenario `4`` requests will be performed for each secret.

*SECRET_VALIDATOR_TIMEOUTSECONDS*::
The property secret.validator.timeout-seconds or the corresponding environment variable SECRET_VALIDATOR_TIMEOUTSECONDS can be used to specify the number of seconds for each of the request before returning because of a timeout. The default value is 5 seconds. This means on default after maximum 5 seconds the next request will be performed.

===== Default spring boot configuration
The defaults can be found inside the link:src/main/resources/application.properties[application.properties] file.


==== Proxy configuration
Inside the configuration file each request has to be configured if a proxy server is required to access this URL or not. +
The wrapper is implemented to use the default proxy of the system properties. To configure a proxy, launch the application with the following arguments:

[source, bash]
----
java -Dhttp.proxyHost=localhost -Dhttp.proxyPort=1234 \
     -Dhttps.proxyHost=localhost -Dhttps.proxyPort=1234 \
     -jar sechub-wrapper-secretvalidation.jar
----

=== Testing
For testing purposes there is another implementation present which is only available and used if the wrapper is started with the "integrationtest" profile:

[source, bash]
----
java -Dspring.profiles.active=integrationtest \
     -jar sechub-wrapper-secretvalidation.jar
----

If the "integrationtest" profile is used the application will flag all findings in the SARIF report as valid, that has a non-empty list of requests configured.
In case no requests are configured the finding will be flagged as invalid.
