# SPDX-License-Identifier: MIT

# Logging: suitable for development - e.g. when searching for failures in test cases
logging:
 level:
   com.mercedesbenz.sechub: DEBUG
   org.apache.http: DEBUG
   org.springframework: DEBUG
 
