# SPDX-License-Identifier: MIT
# only used in development or demo mode - so username password does not matter...
spring:
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1