# SPDX-License-Identifier: MIT
## --------------------------------------------
##  PostgreSQL setup
## --------------------------------------------

# next lines are defined for integration tests using PostgreSQL test container
# for production you must change it by setting environment entries. E.g. in k8s deployment
spring:
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
   datasource:
      url: ${POSTGRES_DB_URL}
      username: ${POSTGRES_DB_USERNAME}
      password: ${POSTGRES_DB_PASSWORD}
      driverClassName: org.postgresql.Driver