/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AsyncButton: typeof import('./components/AsyncButton.vue')['default']
    EmailVerificationSuccess: typeof import('./components/EmailVerificationSuccess.vue')['default']
    JobDetaillsToolBar: typeof import('./components/JobDetaillsToolBar.vue')['default']
    JobDetails: typeof import('./components/JobDetails.vue')['default']
    JobDetailsStatus: typeof import('./components/JobDetailsStatus.vue')['default']
    JobReport: typeof import('./components/JobReport.vue')['default']
    JobReportCodescanDetails: typeof import('./components/JobReportCodescanDetails.vue')['default']
    JobReportOverview: typeof import('./components/JobReportOverview.vue')['default']
    JobReportStatus: typeof import('./components/JobReportStatus.vue')['default']
    JobReportWebscanDetails: typeof import('./components/JobReportWebscanDetails.vue')['default']
    JobScanReport: typeof import('./components/JobScanReport.vue')['default']
    JobsScanReportTable: typeof import('./components/JobsScanReportTable.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    ProjectDetails: typeof import('./components/ProjectDetails.vue')['default']
    ProjectDetailsFab: typeof import('./components/ProjectDetailsFab.vue')['default']
    ProjectJobList: typeof import('./components/ProjectJobList.vue')['default']
    ProjectsList: typeof import('./components/ProjectsList.vue')['default']
    ProjectToolbar: typeof import('./components/ProjectToolbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanCreate: typeof import('./components/ScanCreate.vue')['default']
    ScanFileUpload: typeof import('./components/ScanFileUpload.vue')['default']
    ScanTypeSelect: typeof import('./components/ScanTypeSelect.vue')['default']
    UserDetailInformation: typeof import('./components/UserDetailInformation.vue')['default']
  }
}
