/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    ProjectDetails: typeof import('./components/ProjectDetails.vue')['default']
    ProjectDetailsFab: typeof import('./components/ProjectDetailsFab.vue')['default']
    ProjectJobList: typeof import('./components/ProjectJobList.vue')['default']
    ProjectsList: typeof import('./components/ProjectsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanCreate: typeof import('./components/ScanCreate.vue')['default']
    ScanFileUpload: typeof import('./components/ScanFileUpload.vue')['default']
    ScanTypeSelect: typeof import('./components/ScanTypeSelect.vue')['default']
    UserDetailInformation: typeof import('./components/UserDetailInformation.vue')['default']
  }
}
