// SPDX-License-Identifier: MIT
[[section-start-configuration]]
==== Profiles / running the {sechub} {pds}

===== Production mode
You can start a PDS in production profile which requires a running PostgreSQL
database. Please refer also to <<section-postgresql-configuration,PostgreSQL configuration>> for
database setup which must be done before.

Example:
----
java -jar Dspring.profiles.active=pds_prod sechub-pds-0.25.0.jar
----

NOTE: There are some more mandatory parameters, please refer to <<section-general-configuration,general configuration>>

===== Integration test mode
You can start a PDS in integration test mode if you just want to
test


Example:
----
java -jar -Dspring.profiles.active=pds_integrationtest,pds_h2 sechub-pds-0.25.0.jar
----


===== Logging
====== Default output
{pds} uses per default logging to `stdout`. In case you are running on Kubernetes or similar platforms you can use
`fluentd` to gather the log output.

====== Logstash support
When you want to use `logstash` you just have to set the environment variable
`LOGGING_TYPE` to `LOGSTASH_JSON` before server starts.


[[section-db-configuration]]
==== Database configuration

[[section-postgresql-configuration]]
===== PostgreSQL

First of all install a PostgreSQL database.

Then define following environment entries before you start the server
with active postgres profile:

- POSTGRES_DB_URL
- POSTGRES_DB_USERNAME
- POSTGRES_DB_PASSWORD

Examples:
----
POSTGRES_DB_URL=jdbc:postgresql://127.0.0.1:49153/pds-gosec
POSTGRES_DB_USERNAME=pds-gosec-pg-admin
POSTGRES_DB_PASSWORD=a-very-strong-password...
----

[[section-general-configuration]]
==== General configuration
{pds} can be configured by keys on server startup.
Using the spring `@Value` annotation we are able to
use these keys as Java system properties but also as environment entries.

E.g. a key like `pds.admin.apitoken` can be set with

----
java ... -Dpds.admin.apitoken={noop}12345exampleToken
----

or with an environment entry `PDS_ADMIN_APITOKEN` which
is e.g. more suitable for a `kubernetes` cluster deployment.

[TIP]
====
When you have secret information you can define those information as a template by using environment
variables from your {sechub} installation.

An example:

```
pds.admin.apitoken=env:PDS_GOSEC_SOLUTION_APITOKEN
```

If your SecHub process runs in an environment with variable `PDS_GOSEC_SOLUTION_APITOKEN` set
to 'very-secret-apitoken1234' _(e.g. by using secrets inside K8s)_, the authentication sent to
{pds} by {sechub} will use
```
pds.admin.apitoken=very-secret-apitoken1234
```
====

ifdef::showhintaboutgenerated[]
include::./../shared/pds_hint_generated_systemproperties.adoc[]
endif::[]

[[link-gen-pds-systemproperties]]
include::./../gen/gen_pds_systemproperties.adoc[]


include::pds_solution_configurations.adoc[]
