# SPDX-License-Identifier: MIT

version: "3"
services:
  web-server:
    build:
      args:
        - BASE_IMAGE=${BASE_IMAGE}
        - BUILD_TYPE=${BUILD_TYPE}
        - WEB_SERVER_VERSION=${WEB_SERVER_VERSION}
        - JAVA_VERSION=${JAVA_VERSION}
        - TAG=${TAG}
        - BRANCH=${BRANCH}
      context: docker/
      dockerfile: Web-Server-Debian.dockerfile
    container_name: web-server
    env_file:
      - .env
      - .env-web-server
    ports:
      - "${HOST_NAME}:${WEB_SERVER_PORT}:4443"
      - "${HOST_NAME}:${JAVA_DEBUG_PORT}:15025"
    networks:
      - "internal"

networks:
  internal:
