# SPDX-License-Identifier: MIT

version: "3"
services:
  web_server:
    build:
      args:
        - BASE_IMAGE=${BASE_IMAGE}
        - BUILD_TYPE=${BUILD_TYPE}
        - WEBSERVER_VERSION=${WEBSERVER_VERSION}
        - JAVA_VERSION=${JAVA_VERSION}
        - TAG=${TAG}
        - BRANCH=${BRANCH}
      context: docker/
      dockerfile: Web-Server-Debian.dockerfile
    container_name: webserver
    env_file:
      - .env
      - .env-web-server
    ports:
      - "${HOST_NAME}:${WEBSERVER_PORT}:4443"
      - "${HOST_NAME}:${JAVA_DEBUG_PORT}:15025"
    networks:
      - "sechub"

networks:
  sechub:
    external: true
    name: "sechub"
