// SPDX-License-Identifier: MIT
For some security products it's necessary to differ between `intranet` and `internet` scan targets. 
This is represented by the class `NetworkTarget`.

Some products are not able to handle different network targets when not being installed
twice,  some can do this by a product specific identifier. {sechub} must be able to 
automatically call the correct product installation in such cases. 

To handle this always the same way some framework mechanism was introduced, see next chapter.

[[sechub-concept-installsetup]]
==== Automatic Network Target info resolving

The class `AbstractProductExecutor` is the single base class for mostly all product executors and does
automatically provide network target handling for scan types `webScan` and `infraScan`.

The abstract executor will create a `ProductExecutorData` object at runtime let child implementations
customize it and then prepare all necessary stuff before giving it again to the child implementation
for final execution. 

For automated target handling the customization of `ProductExecutorData` must set a 
`NetworkTargetProductServerDataProvider` and a `NetworkTargetLocationProvider`.

[TIP]
====
For `PDS` the network target type will be injected to the `PDS` caller scripts automatically via
environment variable `PDS_SCAN_TARGET_TYPE`. Also `PDS` instances have the possibility to forbid
a target type - so for different target types we can define two different PDS executor configurations.
====

plantuml::diagrams/diagram_target_architecture.plantuml[format=svg, alt="Class diagram of target and install setup architecture"]