// SPDX-License-Identifier: MIT
[[sechub-concept-templates-and-assets]]
==== Templates and assets
===== About 
When it comes to complex configurations it can be cumbersome for {sechub} users, difficult for support
and - depending on the product - very hard to provide a complete generic approach via {sechub}  configuration
only. 

===== Example situation
To clarify this abstract situation here an example: Think about a wide range of applications inside 
a corporation which want to use a common single sign on with multi factor authentication and some 
other specific parts. The login configuration in {sechub} configuration file by defining explicit steps, pages etc.
would become complex and error prone because :

- not every user would understand exactly what to do
- if the single signon mechanism ever changes, every project/user would need to change their {sechub} configuration files!
  When talking about hundreds of projects this would be a great effort - for users and for support!

And let us assume the used product has hundreds of options which cannot be configured
by a generic approach easily (e.g. form login definition in configuration): How could this product
be provided in a desired way then? And what if there are some specific parts which are not 100% same
in every of these projects? 
 
This is the reason for the "templates and assets" concept which is described below.

===== Big picture
plantuml::./diagrams/diagram_templates-and-assets-big-picture.puml[format=svg, title="Big picture of templates and assets"]

===== Templates
{sechub} can have multiple templates. Every template has a type and can contains a set of 
assets and also a variable definition. It can be administrated via REST end points.

====== Template id format
A template id

- has a minimum length of 3
- has a maximum length of 40
- can contain only `a-z` `A-Z`, `0-9` or  `-` or `_`

====== Template definition
The template definitions are hold inside {sechub} database.
A template is defined by following json syntax:

.Template definition syntax
[source,json]
----
include::../snippet/template-definition-syntax.json[]
----
<1> The template identifier
<2> The type of the template. Must be set when a template is created. Will
    be ignored on updates. Possible values are: `webscan-login`
<3> Asset identifier for the template
<4> Variable definitions as list of key and value pairs which can be mandatory or optional. 
Via the type {sechub} server is able to check if the configuration is valid and give 
response to users when job starts.
<5> Name of the variable
<6> Describes if the variable is optional.  +
    When `false` configuration must contain the variable inside template data. When `true`
    the configuration is valid without the variable. The default is `false`.
<7> Variable content validation definition ((optional)
<8> Minimum length (optional)
<9> Maximum length (optional)
<10> Regular expression (optional). If defined, the content must match the given regular expression
    to be valid. 

[CAUTION]
====
The validation section inside the definition is only for a "first simple check" on {sechub} side, to
stop before any {pds} job is created. 

*But {pds} solutions which are using templates must ensure,that the given user content 
(variable) is correct and not some malicious injected data!*
====
====== Mapping templates to projects

plantuml::./diagrams/diagram_templates-mapping-to-projects.puml[format=svg, title="Mapping of templates and projects"]

As shown in the figure above, the template data is hold inside domain "scan". The reason is, that
template details are necessary inside the scan operation and no where else.

The association between project and used templates is done in administration domain because the project
entity and its details are used here. At the `administration` domain only the template identifiers 
used by this project are necessary.

A mapping of templates to a project is dependent on the template type: Same type of a template cannot
be added twice to a project! Because the `administration` domain does not know about the template details,
a synchronous event to `scan` domain will be sent to assign the template to the project.

The scan domain will update this information inside `ScanProjectConfig` entities and will drop
a former assigned template of same type from the config.

After this is done as a syncron result the scan domain will return all assigned 
templates, as shown in next figure:

plantuml::./diagrams/diagram_templates-mapping-to-projects-events.puml[format=svg, title="Mapping of templates and projects (Events)"]

[NOTE]
====
The mapping is stored with template type as part of the composite key: 
If two template definitions with same type are uploaded, the last one will
overwrite the first one.
====

====== Templates in SecHub configuration file
The users can now define in their {sechub} configuration file that they want to use the
configured template for web scanning by defining a templateData section inside the login
configuration.

For example:
[source,json]
----
include::../configuration/sechub_config_example22_webscan_with_template.json[]
----
<1> Define template data for the login. The user
is not able to define which template is used.
<2> Setup template variables by a list of key and value pairs. 

If the user has defined a `templateData` section in the configuration but no template of that type is assigned to the project, a
dedicated error message must be returned to the user and the {sechub} job will always fail.

[IMPORTANT]
====
For templates and assets we must use shared storage between {sechub} and {pds}. {pds} solutions may 
not to provide own storage for {pds} - different storages are not supported here.
====

===== Assets
====== Asset id format
An asset id

- has a minimum length of 3
- has a maximum length of 40
- can contain only `a-z` `A-Z`, `0-9` or  `-` or `_`

====== {sechub} server uses product identifiers for asset ids
The {sechub} server will use the product identifiers from {pds} executor configurations
as file names when storing asset data inside database and storage. The product identifiers
are also defined inside the {pds} server configuration files.

Here an example for storage paths:
```
/assets/
   asset-id-1/
      PDS_OWASP_ZAP.zip
      PDS_OWASP_ZAP.zip.sha256
      OTHER_PRODUCT_X.zip
      OTHER_PRODUCT_X.zip.sha256
```
[IMPORTANT]
====
The content and the structure inside the ZIP files is absolute solution specific:
Means the {pds} solution defines which kind of template data is necessary and how the 
structure looks like. Because of this necessary template variables, file structure for 
asset zip files etc. must be documented inside the {pds} solution!
====

====== Asset operations
*General*

*Usecases*

- Admin creates or updates asset
-  

Over REST API Administrators will be able to 

- upload asset ZIP files by REST API and create checksum file
- download asset files by REST API
- list asset details (filenames and checksums)
- delete single asset file by REST API
- delete all asset data by REST API 

The REST API will always create an audit log entry 

*Upload*

The upload and delete operations will always handle DB and storage (S3/NFS)!
If an asset ZIP file already exists, the operation will overwrite the file and the 
old sha256 checksum in both locations.

[TIP]
====
Main reason why we store always in DB and use storage (S3/NFS) as a cache only:

1. Restore a DB backup on a fresh installation:  +
   Administrators can just apply the database backup and everything works again
2. Storage could be volatile/be deleted etc. (we rely to the database)
3. For having multiple and also different cluster types ( {sechub} cluster and multiple {pds} clusters)
   having not same database we need a common way to exchange data.
   Each {pds} cluster and also the {sechub} cluster have their own
   database - means cannot be used for exchange.
====
 

[IMPORTANT]
====
This works only when the storage is shared between {sechub} and {pds}.
If the {pds} uses its own storage (which should NOT be done for production, but only
for PDS solution development) the assets would needed to be uploaded directly to the PDS storage 
location with correct checksum etc. 
====

===== SecHub runtime
====== Validate config uses valid template location
When a {sechub} job starts and there is a template data definition inside the configuration, 
{sechub} will validate if the project has a template assigned for the location inside
the configuration. e.g. templates with type `webscan-login` may only be defined inside 
web scan login configuration).

If this validation fails, the complete {sechub} job will fail and stop processing.

[[sechub-concept-asset-upload-lazy]]
====== Validate config uses valid template location 

When validation did not fail, {sechub} will check if the current version of the
necessary product specific asset ZIP file is exsting in storage. 

When not uploaded to storage, the file will be uploaded before the job is 
further processed.

====== Template PDS parameter calculation
If the job configuration has valid template data and the template 
is available in storage, {sechub} will calculate the
{pds} parameter : `pds.config.template.metadata.list` with JSON:

[[sechub-concept-template-metadata-example]]
.PDS parameter syntax for template meta data
[source,json]
----
include::../snippet/pds-param-template-metadata-syntax.json[]
----
<1> Meta data array
<2> Template identifier - just as an information for logging etc.
<3> Template type
<4> Asset information array
<5> Asset identifier
<6> Name of file (inside asset)
<7> Checksum of the file (SHA256)

===== PDS runtime
====== Asset handling
{sechub} calls {pds}, with {pds} parameter `pds.template.metadata` (syntax is described above).

The {pds} instance will fetch all defined files from storage (S3 or NFS) 
and extract/copy it to `$workspaceFolder/assets/`. 

Before extraction is done a checksum for the downloaded file is created and compared
with the checksum from template meta data. The checksum algorithm is SHA256.
If it is different the {pds} job will fail with a dedicated error message.

If the checksum is valid, the assets ZIP file will be unzipped below a subfolder with the 
template type:
 
[source,text]
----
`$workspaceFolder/
     assets/
        $template-type/
                    ...
----

An example:

The `WEBSCAN_PRODUCT_ID.zip` file contains

[source,text]
----
/login-script.groovy
/development/
             debug-settings.json
----

and the template meta data looks like this:

[source,json]
----
include::../snippet/pds-param-template-metadata-example1.json[]
----

The extraction is done into folder:
`$workspaceFolder/assets/$templateType/` which will be made available to launcher scripts (and wrapper
applications) by environmnet variable `PDS_JOB_EXTRACTED_ASSETS_FOLDER`.

For the former example `WEBSCAN_PRODUCT_ID.zip` will be extracted the following way:

[source,text]
----
`$workspaceFolder/
     assets/
        webscan-login/
                    login-script.groovy
                    development/
                              debug-settings.json
   
----

====== Example code for usage inside PDS solutions/wrappers

Here an example how a product could use the assets inside 
a wrapper application for a PDS solution:

[source,java]
----
import java.nio.file.*;
import com.mercedesbenz.sechub.commons.model.JSONConverter;
import com.mercedesbenz.sechub.commons.model.template.*;
// ...

String sechubConfigAsJson = System.getenv("PDS_SCAN_CONFIGURATION");
SecHubConfigurationModel sechubConfig = JSONConverter.get().fromJSON(SecHubConfigurationModel.class,sechubConfigAsJson);

TemplateDataResolver resolver = new TemplateDataResolver();

TemplateData templateData = resolver.resolveTemplateData(TemplateType.WEBSCAN_LOGIN, sechubConfig);
if (templateData!=null){

    Map<String, String> variables = templateData.getVariables();

    // read template script file from extracted folder
    String assetExtractionFolder = System.getenv("PDS_JOB_EXTRACTED_ASSETS_FOLDER");
    Path path = Paths.get(assetExtractionFolder, TemplateType.WEBSCAN_LOGIN.getId(), "login-script.groovy");
    String scriptTemplate = Files.readString(path);
    
    // replace variable parts inside template
    String script = scriptTemplate ;
    script = script.replaceAll("#user", variales.get("user");
    script = script.replaceAll("#pwd", variales.get("password");
    
    // execute script
    // ...
    
}

----





