// SPDX-License-Identifier: MIT
[[concept-pds_solution_metadata]]

When communication of {pds} with the used product is stateful and is a long running operation, 
it can be useful to store such state/meta data.  

One use case is the restart possibility for a {sechub} job. Another one are debugging or 
trace information.

[TIP]
====
Most times {pds} solutions do not need to store special meta data information: When the PDS job starts
a CLI tool, the result or the failure will just be returned to the {sechub} side.

If it shall be done again (because of on failure) just a new {pds} job will be started. 

If a PDS job has meta data this means it should be restarted
====

A {pds} launcher script has no access to the {pds} database!
If meta data shall be read or written, we just have the workspace file `metadata.txt`. 
Inside this file the product relevant meta data
of the job run must be available, see next diagram for details:

plantuml::diagrams/diagram_pds_metadata.puml[] 

====== Checkmarx PDS solution adapter meta data handling

The {pds} solution for `Checkmarx` does reuse the already existing `CheckmarxAdapter` class.
A `sechub-wrapper-checkmarx` gradle project was introduced which contains a simple spring boot
CLI application which uses the adapter for communication. The adapter callback is not directly
reading or writing to the database but uses the cmetadata.txt` file from the {pds} workspace. 

Look at next figure for more details: 


plantuml::diagrams/diagram_pds_solution_checkmarx_overview.puml[] 
