// SPDX-License-Identifier: MIT
[[concept-mapping]]
{sechub} needed a way to configure simple configuration values and also
provide a mapping from project names to adapter specific values (see 
<<scan-config-about,Scan config>> )

==== Structure 
To provide this in a very generic way {sechub} does use the `mappings` means
a simple setup of
 
- pattern +
  _(simple key or a regular expression)_
- replacement +
  _(just the value)_
- comment 
  _(describes what this mapping is used for - just for information)_

==== Domain handling

===== Global mappings
The `Administration` domain will know every global mapping (e.g. scan configuration) and provide the 
corresponding REST API for administrators.

Changes of global mappings will be sent from administration domain to other
domains via event bus and a message with ID: <<section-gen-messaging-mapping_configuration_changed,MAPPING_CONFIGURATION_CHANGED>>.

Dedicated message handlers inside other domains will recognize wanted parts and store information when
necessary.

===== Product executor parameter mappings
This will not lead to any domain event. The product executors will inspect the mapping information always again before a job has been started.
The mapping data is stored inside executor configurations, which is always available inside a job execution, so there is no need of any domain events. 