// SPDX-License-Identifier: MIT
[[section-shared-concepts-module-groups]]
The Spring Security OAuth2 library is used in {sechub} and is configured inside
class `SecHubSecurityConfiguration` which extends `AbstractSecurityConfiguration`.

Because there was a need to configure OAuth2 handling very dynamically, we introduced an 
own data structure for setup, see class `SecHubSecurityProperties`.

The configuration and the description can be found in keys below `sechub.security.login` at
<<section-gen-configuration-scope-login_and_resource_server,Login and resource server configuration>> 

==== JWT handling
Standard Spring Boot way except the configuration keys which are SecHub specific (see link above).

==== Opaque token handling
Standard Spring Boot way except the configuration keys which are SecHub specific (see link above)
but also with a cache mechanism for repsonse tokens.

===== Opaque token cache mechanism
The opaque token handling is cached by two different caches:

First level cache is a fast in memory cache - which is persisted by InMemoryCachePersistance. 
This cache is only available on a JVM instance and exists only a short time (e.g. 10 seconds).

If the first level cache does not or does not longer contains the opaque token response data,
the second level (cluster) cache from cluster persistence is fetched and stored again in first cache.

If the second level cache also does not or does not longer contain the opaque token response data,
the IDP will be called to fetch the opaque token response data.

plantuml::diagrams/diagram_oauth2_opaque_token_caching_overview.puml[]


