// SPDX-License-Identifier: MIT
[[data-structure-tar-and-zip-files]]

The data structure inside `TAR` and `ZIP` files contains
data configuration parts inside `__data__` folder. 

[NOTE]
====
Before we introduced the possibility to define referenceable <<sechub-config-data-section,data>> inside a
{sechub} configuration, we already provided a `fileSystem` element inside 
 <<sechub-config-code-scan,code scan configuration>>. 

For source scans this a more convenient way and we wanted to keep this possiblity - also for
backward compatibility with existing sechub configuration files.

So this is the reason, why <<sechub-config-data-section,data>> is contained inside `\__data__` 
folder and there is still content inside the root folder as well. 

====

[WARNING]
====
Only source code scan configuration files may be located inside the root folder!
====

[source,shell]
----
${content} #<1>
__data__/unique-name-1/${content} #<2> 
__data__/unique-name-2/${content} #<3> 
...
----
<1> code scan embedded file system data
<2> content of a data configuration with name "unique-name-1"
<3> content of a data configuration with name "unique-name-2"


Here an example:

[source,json,title="Example JSON data definition to show resulting TAR and ZIP structures"]
----
include::../configuration/sechub_config_data_section_general_example2.json[]
----
<1> source definition - these structure parts are inside the `sourcecode.zip` file
<2> Name of one source data configuration
<3> binaries definition - these structure parts are inside the `binaries.tar` file
<4> Name of the first binaries data configuration
<5> Name of the second binaries data configuration

The example json configuration defines following content structure inside the upload files:
[source,shell, title="ZIP file content for sources"]
----
__data__/
    reference-name-sources-1/ #<2>
                  somewhere/
                     file1.txt 
                     file2.txt
                     subfolder1/
                        example-content.py9
                     subfolder2/
                        example-content.cplusplus
                        example-content.txt  
----

The example json configuration would lead to a `TAR` file containing:
[source,shell,title="TAR file content for binaries"]
----
__data__/
    reference-name-binaries-1/#<4>
                  somewhere/
                     file1.dll 
                     file2.a
                     subfolder1/
                        example-content.bin
                     subfolder2/
                        example-content.img
    reference-name-binaries-2/#<5>
                  somewhere-else/
                     file1.dll 
                     file2.a
                     subfolder1/
                        example-content.bin
                     subfolder2/
                        example-content.img
----

