// SPDX-License-Identifier: MIT
[[data-structure-tar-and-zip-files]]

The data structure inside `TAR` and `ZIP` files contains
data configuration parts inside `\\__data__` folder.

[NOTE]
====
Before we introduced the possibility to define referenceable <<sechub-config-data-section,data>> inside a
{sechub} configuration, we already provided a `fileSystem` element inside
 <<sechub-config-code-scan,code scan configuration>>.

For source scans this a more convenient way and we wanted to keep this possiblity - also for
backward compatibility with existing {sechub} configuration files.

So this is the reason, why <<sechub-config-data-section,data>> is contained inside `\\__data__`
folder and there is still content inside the root folder as well.
====

[source,shell]
----
${content} #<1>
__data__/unique-name-1/${content} #<2>
__data__/unique-name-2/${content} #<3>
...
----
<1> code scan embedded file system data
<2> content of a data configuration with name "unique-name-1"
<3> content of a data configuration with name "unique-name-2"


Here an example:

[source,json,title="Example JSON data definition to show resulting TAR and ZIP structures"]
----
include::../configuration/sechub_config_data_section_general_example2.json[]
----
<1> source definition - these structure parts are inside the `sourcecode.zip` file
<2> Name of one source data configuration
<3> binaries definition - these structure parts are inside the `binaries.tar` file
<4> Name of the first binaries data configuration
<5> Name of the second binaries data configuration

The example json configuration defines following content structure inside the upload files:
[source,shell, title="ZIP file content for sources"]
----
__data__/
    reference-name-sources-1/ #<2>
                  somewhere/
                     file1.txt
                     file2.txt
                     subfolder1/
                        example-content.py9
                     subfolder2/
                        example-content.cplusplus
                        example-content.txt
----

The example json configuration would lead to a `TAR` file containing:
[source,shell,title="TAR file content for binaries"]
----
__data__/
    reference-name-binaries-1/#<4>
                  somewhere/
                     file1.dll
                     file2.a
                     subfolder1/
                        example-content.bin
                     subfolder2/
                        example-content.img
    reference-name-binaries-2/#<5>
                  somewhere-else/
                     file1.dll
                     file2.a
                     subfolder1/
                        example-content.bin
                     subfolder2/
                        example-content.img
----

*How to support custom archive uploads by Web UI?*

Every scan configuration which relies on file data - except the `codeScan` legacy way - needs at least one 
reference to sources or binaries inside the data section.

With the `Web UI` users shall be able to upload custom source and/or binary archives and start a job directly.
But most users just want to create a simple archive with their sources (or binaries) inside and do not want
to bother with data sections. While creating a new {sechub} job, the `Web UI` generates a temporary {sechub} 
configuration file which must reference files related to the root folder of the custom user archives.  

To provide this in a convenient but still compatible way, following unique reference names/ids were introduced:

- `\\__sourcecode_archive_root__`  +
  _(for source code files at root level in a ZIP)_
- `\\__binaries_archive_root__` + 
  _(for binary files at root level in a TAR)_

They can be used like any other reference name within a configuration.
But they *cannot* be defined in a data section of a configuration, since their target, the root folder of the 
respective archive, is always present anyway. The `Web UI` can now generate a temporary config file by using the 
reserved reference names.

[WARNING]
====
If a data section of a configuration contains a reserved reference name the configuration is invalid for the server.
If the custom archive contains folders directly below `\\__data__` having the reserved name as folder name, they will be
ignored at extraction time. 
====

[TIP]
====
The {sechub} go client will always produce archives with `\\__data__` inside the root folder. 
The reserved reference names for archive root locations are only a workaround for custom created 
archives where no `\\__data__` folder exists.
====
