# SPDX-License-Identifier: MIT

version: "3"
services:
  pds-owaspzap:
    build:
      args:
        - BASE_IMAGE=${BASE_IMAGE}
        - OWASPZAP_WRAPPER_VERSION=${OWASPZAP_WRAPPER_VERSION}
        - OWASPZAP_VERSION=${OWASPZAP_VERSION}
        - OWASPZAP_SHA256SUM=${OWASPZAP_SHA256SUM}
      context: docker/
      dockerfile: Owasp-Zap-Debian.dockerfile
    env_file:
      - .env-cluster
    networks:
      - "internal"
      - "sechub"
    volumes:
      - "shared_volume:/shared_volumes/uploads"
      - ./docker/scripts:/pds/scripts
    depends_on:
      - database

  loadbalancer:
    build:
      context: ../shared/docker/loadbalancer
      args:
        - PDS_SOLUTION=pds-owaspzap
    env_file:
      - .env-cluster
    networks:
      - "internal"
    depends_on:
      - pds-owaspzap
    ports:
      - "127.0.0.1:8444:8444"

  database:
    build:
      context: ../shared/docker/database
    env_file:
      - .env-cluster
    networks:
      - "internal"
    ports:
      - "127.0.0.1:5432:5432"

networks:
  internal:
  sechub:
    name: "sechub"

volumes:
  shared_volume:
