# SPDX-License-Identifier: MIT

version: "3"
services:
  pds-owaspzap:
    build:
      args:
        - BASE_IMAGE=${BASE_IMAGE}
        - OWASPZAP_WRAPPER_VERSION=${OWASPZAP_WRAPPER_VERSION}
        - OWASPZAP_VERSION=${OWASPZAP_VERSION}
        - OWASPZAP_SHA256SUM=${OWASPZAP_SHA256SUM}
      context: docker/
      dockerfile: Owasp-Zap-Debian.dockerfile
    container_name: pds-owaspzap
    hostname: pds-owaspzap
    env_file:
      - .env
    networks:
      - "sechub"
    volumes:
      - ./docker/scripts:/pds/scripts

networks:
  sechub:
    external: true
    name: "sechub"
