/*
 * SecHub API
 * SecHub API description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.daimler.sechub.client.java.api.model;

import com.daimler.sechub.client.java.api.model.ExecutorConfigurationWithUUIDSetupCredentials;
import com.daimler.sechub.client.java.api.model.ExecutorConfigurationWithUUIDSetupJobParameters;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ExecutorConfigurationWithUUIDSetup
 */
public class ExecutorConfigurationWithUUIDSetupTest {
    private final ExecutorConfigurationWithUUIDSetup model = new ExecutorConfigurationWithUUIDSetup();

    /**
     * Model tests for ExecutorConfigurationWithUUIDSetup
     */
    @Test
    public void testExecutorConfigurationWithUUIDSetup() {
        // TODO: test ExecutorConfigurationWithUUIDSetup
    }

    /**
     * Test the property 'baseURL'
     */
    @Test
    public void baseURLTest() {
        // TODO: test baseURL
    }

    /**
     * Test the property 'credentials'
     */
    @Test
    public void credentialsTest() {
        // TODO: test credentials
    }

    /**
     * Test the property 'jobParameters'
     */
    @Test
    public void jobParametersTest() {
        // TODO: test jobParameters
    }

}
