/*
 * SecHub API
 * SecHub API description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.daimler.sechub.client.java.api.model;

import com.daimler.sechub.client.java.api.model.FalsePositivesJobData;
import com.daimler.sechub.client.java.api.model.FalsePositivesMetaData;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FalsePositivesFalsePositives
 */
public class FalsePositivesFalsePositivesTest {
    private final FalsePositivesFalsePositives model = new FalsePositivesFalsePositives();

    /**
     * Model tests for FalsePositivesFalsePositives
     */
    @Test
    public void testFalsePositivesFalsePositives() {
        // TODO: test FalsePositivesFalsePositives
    }

    /**
     * Test the property 'metaData'
     */
    @Test
    public void metaDataTest() {
        // TODO: test metaData
    }

    /**
     * Test the property 'jobData'
     */
    @Test
    public void jobDataTest() {
        // TODO: test jobData
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'author'
     */
    @Test
    public void authorTest() {
        // TODO: test author
    }

}
