/*
 * SecHub API
 * SecHub API description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.daimler.sechub.client.java.api.model;

import com.daimler.sechub.client.java.api.model.FalsePositivesMetaDataCode;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FalsePositivesMetaData
 */
public class FalsePositivesMetaDataTest {
    private final FalsePositivesMetaData model = new FalsePositivesMetaData();

    /**
     * Model tests for FalsePositivesMetaData
     */
    @Test
    public void testFalsePositivesMetaData() {
        // TODO: test FalsePositivesMetaData
    }

    /**
     * Test the property 'severity'
     */
    @Test
    public void severityTest() {
        // TODO: test severity
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'owasp'
     */
    @Test
    public void owaspTest() {
        // TODO: test owasp
    }

    /**
     * Test the property 'cweId'
     */
    @Test
    public void cweIdTest() {
        // TODO: test cweId
    }

    /**
     * Test the property 'cveId'
     */
    @Test
    public void cveIdTest() {
        // TODO: test cveId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'scanType'
     */
    @Test
    public void scanTypeTest() {
        // TODO: test scanType
    }

}
