/*
 * SecHub API
 * SecHub API description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.daimler.sechub.client.java.api.model;

import com.daimler.sechub.client.java.api.model.FalsePositivesMetaDataCodeEnd;
import com.daimler.sechub.client.java.api.model.FalsePositivesMetaDataCodeStart;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FalsePositivesMetaDataCode
 */
public class FalsePositivesMetaDataCodeTest {
    private final FalsePositivesMetaDataCode model = new FalsePositivesMetaDataCode();

    /**
     * Model tests for FalsePositivesMetaDataCode
     */
    @Test
    public void testFalsePositivesMetaDataCode() {
        // TODO: test FalsePositivesMetaDataCode
    }

    /**
     * Test the property 'start'
     */
    @Test
    public void startTest() {
        // TODO: test start
    }

    /**
     * Test the property 'end'
     */
    @Test
    public void endTest() {
        // TODO: test end
    }

}
