/*
 * SecHub API
 * SecHub API description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.daimler.sechub.client.java.api.model;

import com.daimler.sechub.client.java.api.model.ListOfExecutorConfigurationsExecutorConfigurations;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ListOfExecutorConfigurations
 */
public class ListOfExecutorConfigurationsTest {
    private final ListOfExecutorConfigurations model = new ListOfExecutorConfigurations();

    /**
     * Model tests for ListOfExecutorConfigurations
     */
    @Test
    public void testListOfExecutorConfigurations() {
        // TODO: test ListOfExecutorConfigurations
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'executorConfigurations'
     */
    @Test
    public void executorConfigurationsTest() {
        // TODO: test executorConfigurations
    }

}
