/*
 * SecHub API
 * SecHub API description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.daimler.sechub.client.java.api.model;

import com.daimler.sechub.client.java.api.model.ScanJobCodeScan;
import com.daimler.sechub.client.java.api.model.ScanJobInfraScan;
import com.daimler.sechub.client.java.api.model.ScanJobWebScan;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ScanJob
 */
public class ScanJobTest {
    private final ScanJob model = new ScanJob();

    /**
     * Model tests for ScanJob
     */
    @Test
    public void testScanJob() {
        // TODO: test ScanJob
    }

    /**
     * Test the property 'apiVersion'
     */
    @Test
    public void apiVersionTest() {
        // TODO: test apiVersion
    }

    /**
     * Test the property 'infraScan'
     */
    @Test
    public void infraScanTest() {
        // TODO: test infraScan
    }

    /**
     * Test the property 'codeScan'
     */
    @Test
    public void codeScanTest() {
        // TODO: test codeScan
    }

    /**
     * Test the property 'webScan'
     */
    @Test
    public void webScanTest() {
        // TODO: test webScan
    }

}
