/*
 * SecHub API
 * SecHub API description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.daimler.sechub.client.java.api.model;

import com.daimler.sechub.client.java.api.model.ScanJobWebScanLoginFormScriptActions;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ScanJobWebScanLoginFormScriptPages
 */
public class ScanJobWebScanLoginFormScriptPagesTest {
    private final ScanJobWebScanLoginFormScriptPages model = new ScanJobWebScanLoginFormScriptPages();

    /**
     * Model tests for ScanJobWebScanLoginFormScriptPages
     */
    @Test
    public void testScanJobWebScanLoginFormScriptPages() {
        // TODO: test ScanJobWebScanLoginFormScriptPages
    }

    /**
     * Test the property 'actions'
     */
    @Test
    public void actionsTest() {
        // TODO: test actions
    }

}
