/*
 * SecHub API
 * SecHub API description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.daimler.sechub.client.java.api.model;

import com.daimler.sechub.client.java.api.model.ScanJobWebScanLoginFormAutodetect;
import com.daimler.sechub.client.java.api.model.ScanJobWebScanLoginFormScript;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ScanJobWebScanLoginForm
 */
public class ScanJobWebScanLoginFormTest {
    private final ScanJobWebScanLoginForm model = new ScanJobWebScanLoginForm();

    /**
     * Model tests for ScanJobWebScanLoginForm
     */
    @Test
    public void testScanJobWebScanLoginForm() {
        // TODO: test ScanJobWebScanLoginForm
    }

    /**
     * Test the property 'autodetect'
     */
    @Test
    public void autodetectTest() {
        // TODO: test autodetect
    }

    /**
     * Test the property 'script'
     */
    @Test
    public void scriptTest() {
        // TODO: test script
    }

}
