# SPDX-License-Identifier: MIT

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web-server-policy
spec:
  podSelector:
    matchLabels:
      name: web-server
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: web-ui # Allow SecHub Web-UI access
    ports:
    - protocol: TCP
      port: 4443
