# SPDX-License-Identifier: MIT

# Internal access via cluster IP (maybe obsolete when an api-gateway is in place)
apiVersion: v1
kind: Service
metadata:
  name: web-server
spec:
  selector:
    name: web-server
  ports:
    - protocol: TCP
      port: 4443
      targetPort: 4443
  type: ClusterIP
