// SPDX-License-Identifier: MIT
== Secret valdiation Wrapper

This wrapper is a Spring Boot application, that is supposed to run on PDS solutions running performing secret scan.
After the secret scanning tool is done it will try to validate secrets found and enhance the SARIF report with a custom PropertyBag for each finding location.
It will add a custom severity with the key `secretscan.sechub.severity` and
one of the following values `["info", "unclassified", "low", "medium", "high", "critical"]` to the SARIF PropertyBag which contains a generic map for custom values.
This values can then be used by the `sechub-sereco` module to improve the severity categorization of a finding.

=== Usage

==== Start wrapper
The wrapper application is an executable jar and needs no command line arguments.
It can automatically use all 
https://mercedes-benz.github.io/sechub/latest/sechub-product-delegation-server.html#launcher-scripts[standard PDS environment variables] 
and following special mandatory environment variables:

----
SECRET_VALIDATOR_CONFIGFILE
----

[IMPORTANT]
====
This files contains the configuration for each secret type, which basically tells to wrapper how to validate secrets of a certain type.
For each product a custom file is necessary, where you should use the SARIF `ruleId` to identify each configuration.
From the https://mercedes-benz.github.io/sechub/latest/sechub-product-delegation-server.html#launcher-scripts[standard PDS environment variables]
only the `PDS_JOB_RESULT_FILE` is mandatory because without a valid SARIF report from a secret scanning tool no validations can be done.
====

===== Configuration file example
```json
{
  "validatorConfigList" : [ { <1>
    "ruleId" : "sarif-result-rule-id", <2>
    "categorization" : { <3>
      "defaultSeverity" : "high",
      "validationFailedSeverity" : "medium",
      "validationSuccessSeverity" : "critical"
    },
    "requests" : [ { <4>
      "proxyRequired" : true,
      "url" : "https://api.example.com",
      "headers" : [ {
        "name" : "Authorization",
        "valuePrefix" : "Bearer"
      } ],
      "expectedResponse" : { <5>
        "httpStatus" : 200,
        "contains" : {
          "allOf" : [ "is", "there" ],
          "oneOf" : [ "success", "authorized" ]
        }
      }
    } ]
  } ]
}
```
<1> Define a list of configuration, for each type of secret identified by the rule id.
<2> The `ruleId` identifies this configuration so the requests defined in the later section are performed for each finding of this type.
<3> Your `categorization` configuration. If empty no categorization will be performed, otherwise:
- The `defaultSeverity` will be applied if no requests are defined but you for this type of secret.
- The `validationFailedSeverity` will be applied if all validation requests failed for this secret.
- The `validationSuccessSeverity` will be applied if the secret was successfully validated with one of the requests defined.
<4> The `requests` array defines all requests you know how to validate a secret of this certain type.
This is an array because for some secrets you might need to validate against multiple e.g. when you have AWS credentials found with your secret scan.
You might want to be able to check if it is valid for the public AWS or your internal AWS instances if you have some:
- With `proxyRequired` you can specify if the URL can only be accessed using a proxy server.
- With `url` you specify the URL the request will be performed to.
- With `headers` you specify the header `name` and `valuePrefix` if necessary for the secret found.
It is an array because it could be useful in the future. Currently the header is used for the secret because it is assumed to be a token send via HTTP header.
<5> The `expectedResponse` section contains information you expect on a request with a valid secret,
like a specific `httpStatus` code or the response body should contain `allOf` or `oneOf` certain strings.



There exists also some optional variables:

----
SECRET_VALIDATOR_TRUSTALLCERTIFICATES
---- 

[TIP]
====
When `SECRET_VALIDATOR_TRUSTALLCERTIFICATES` set to `true`, certificate errors on validation web requests will be ignored.
This can be useful, if you are in a environment that needs a proxy server to access certain URLs you have in your configuration.
====

===== Proxy configuration
Inside the configuration file each request has to configure if a proxy server is required to access this specific URL or not.
The wrapper is implemented to use the default proxy of the system properties. To configure a proxy, launch the application with the following arguments.
For each request it will then be decided if the proxy is needed or not according to the configuration file provided:

----
java -Dhttp.proxyHost=localhost -Dhttp.proxyPort=1234 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=1234 -jar secret-validation-wrapper.jar
----