# SPDX-License-Identifier: MIT
webui:
  client:
    mocked: true
  sechub:
    ## Mocked sechub user (necessary for credentialinjection, we have no defaults...)
    userid: "mocked-user"
    apitoken: "mocked-apitoken"

spring:
  security:
    user:
      name: mock-user
      password: mock-password