# SPDX-License-Identifier: MIT
webui:
  client:
    mocked: true
  sechub:
    ## Mocked sechub user (necessary for credentialinjection, we have no defaults...)
    userid: "mocked-user"
    apitoken: "mocked-apitoken"
