spring:
  security:
    oauth2:
      client:
        registration:
          mercedes-benz:
            provider: mercedes-benz
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_REDIRECT_URI}
        provider:
          mercedes-benz:
            issuer-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_ISSUER_URI}
            authorization-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_AUTHORIZATION_URI}
            token-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_TOKEN_URI}
            user-info-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_USER_INFO_URI}
            jwk-set-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_JWK_SET_URI}
            user-name-attribute: sub

