# SPDX-License-Identifier: MIT
server:
  port:
    4443
    
sechub:
  serverUrl: "https://localhost:8443"
  trustAllCertificates: true
  userid: ${SECHUB_USERID}
  apiToken: ${SECHUB_APITOKEN}
  
spring:
  messages:
    basename: "languages/messages"