# SPDX-License-Identifier: MIT

# Main settings
server:
  port:
    4443
  ssl:
    enabled: true # always enabled
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3

sechub:
  serverUrl: "https://localhost:8443"
  trustAllCertificates: true
  
spring:
  messages:
    basename: "languages/messages"
  profiles:
     group: 
        dev: "localserver"
        test: "test"
