# SPDX-License-Identifier: MIT

# Main settings
server:
  port:
    4443
  ssl:
    enabled: true # always enabled
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3

spring:
  config:
    import: optional:classpath:application-local.yaml
  messages:
    basename: "i18n/messages"
  profiles:
    group:
      webui_prod: "webui_server"
      webui_dev: "webui_localserver,webui_mocked"
      webui_test: "webui_test"
      webui_integrationtest: "webui_localserver,webui_integrationtest-data"
  security:
    oauth2:
      client:
        registration:
          mercedes-benz:
            provider: sso.mercedes-benz.com
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: https://sechub.detss.corpintra.net/internal/login
        provider:
          mercedes-benz:
            authorization-uri: https://sso-int.mercedes-benz.com/as/authorization.oauth2
            token-uri: https://sso-int.mercedes-benz.com/as/token.oauth2
            user-info-uri: https://sso-int.mercedes-benz.com/idp/userinfo.openid
            jwk-set-uri: https://sso-int.mercedes-benz.com/pf/JWKS
            user-name-attribute: sub
