# SPDX-License-Identifier: MIT
server:
  ssl:
    key-store-type:
      PKCS12
    key-store:
       # we use a keystore location which is never tracked by git. 
       # see dev-create_localhost_certificate.sh and  dev-ensure_localhost_certificate.sh
       classpath:certificates-untracked/generated-dev-localhost-keystore.p12
    key-store-password:
      123456
    key-alias:
       tomcat
       
sechub:
  server-url: "https://localhost:8443"
  trust-all-certificates: true