# SPDX-License-Identifier: MIT

# Main settings
server:
  port:
    4443
  ssl:
    enabled: true # always enabled
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3


spring:
  messages:
    basename: "i18n/messages"
  profiles:
    group:
      webui_prod: "ssl-cert-required,oauth2-enabled"
      webui_int: "ssl-cert-required,oauth2-enabled,classic-auth-enabled"
      webui_dev: "ssl-cert-provided,classic-auth-enabled"
      webui_local: "ssl-cert-provided,classic-auth-enabled,local"
      webui_test: "test"
      webui_integrationtest: "ssl-cert-provided,integrationtest-data"
  web:
    resources:
      static-locations: classpath:/static
