spring:
  security:
    oauth2:
      client:
        registration:
          mercedes-benz:
            client-id: ${SECHUB_OAUTH2_CLIENT_ID}
            client-secret: ${SECHUB_OAUTH2_CLIENT_SECRET}
            provider: ${SECHUB_OAUTH2_PROVIDER}
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: ${SECHUB_WEBUI_OAUTH2_LOGIN_REDIRECT_URI}
        provider:
          mercedes-benz:
            issuer-uri: ${SECHUB_OAUTH2_ISSUER_URI}
            authorization-uri: ${SECHUB_OAUTH2_AUTHORIZATION_URI}
            token-uri: ${SECHUB_OAUTH2_TOKEN_URI}
            user-info-uri: ${SECHUB_OAUTH2_USER_INFO_URI}
            jwk-set-uri: ${SECHUB_OAUTH2_JWK_SET_URI}
            user-name-attribute: sub

