[[section-concept-false-positive-technical-details]]
==== Technical details about false positive handling

There are two different kind of phases: +

1. User definition of false positive definitions
2. Job execution / runtime 

===== Definition phase

When a user has a {sechub} report with some findings - he/she can define false positives by 
the report UUID and the finding id which represents the false positive.

The configuration is described at  <<section-false-positives-define-by-API,how to define false positives by API>>.

====== Overview
The next figure shows a simplified UML diagram (shows only relevant parts). Below the figure you will find sub chapters with more information. 

plantuml::diagrams/diagram_falsepositives_definition_overview.puml[format=svg, title="Overview definition phase"]

====== Used storage mechanism

For every {sechub} project a <<section-concept-project-scan-configuration,project scan config>> entry for false positives exists.
The entry does contain a `FalsePositiveProjectConfiguration` object as JSON.

====== Data structure
The `FalsePositiveProjectConfiguration` object contains a list of `FalsePositiveEntry` objects.

Every `FalsePositveEntry` object contains

- `FalsePositiveJobData` +
   contains job uuid, finding id and comment - this information is provided by user.

- `FalsePositiveMetaData`  +
   contains meta information about findings - this information is gathered and calculated by {sechub} internally when
   a user has marked a report finding as a false positive. So the meta information is independent (so when a reoprt has
   been deleted, we still have the false positive meta information).

   - It contains many meta information -e.g. a cweId - but also `FalsePositiveCodeMetaData` for code scans details.

====== Definition by user
A user does define a `FalsePositiveJobDataList` object which contains only `FalsePositiveJobData` inside. Such a list will
be used to add but also to remove false positives.

====== Merging
When a user adds or removes false positive definitions, the `FalsePositiveProjectConfiguration` will be updated by 
`FalsePositiveJobDataConfigMerger`.


===== Job execution phase

Here `Sereco` is in charge, which does only inspect the meta data.

====== Overview
plantuml::diagrams/diagram_falsepositives_runtime_overview.puml[format=svg, title="Overview runtime phase"]

