// SPDX-License-Identifier: MIT
[[section-false-positives-define-by-API]]
Defining false positives is done by sending false positive information via `JSON` either

- by referencing *job results* from former {sechub} job UUID and the corresponding finding entry (by id) or
- by specifying a *project data* section where specific patterns that match false positive findings are declared

and post it to the SecHub server REST API. 

[NOTE]
====
The `jobData` approach is very easy, generic - and also future-proof: The only dependency is to the job, 
`UUID`, for which the report must still exist while the definition is done. Every false-positive in 
any kind of scan can be handled like that.

The `REST` controller logic reads the job result data and creates internally false positive 
meta data.
====

[NOTE]
====
The `projectData` approach is more powerful for the user.
Since it is more powerful with the wildcard approach it requires more intial setup from the user.

There are no dependencies because all information necessary to identify certain findings are specified via `REST`.
Each entry can be removed by the given `id`.
====

*Example JSON*

[source,json]
----
include::false-positives-REST-API-content-example1.json[]
----
<1> API version
<2> type - must be `falsePositiveDataList` or the deprecated type `falsePositiveJobDataList`.
<3> List of jobData _(optional)_ that is used to mark a single finding as false positive
<4> SecHub Job-UUID of the report where the finding was
<5> finding-ID which shall be marked as false positive
<6> A comment (optional) describing the reason why this is a false positive
<7> List of projectData _(optional)_ that can be used to mark more than a single finding as false positive.
Currently only available for web scans. This is not necessarily bound to a SecHub report,
but it might be easier to create this type of false positive configuration with a SecHub report after a scan.
<8> `id` that identifies this entry. If the same `id` is used again,
the existing false positive entry will be overwritten. The `id` is also mandatory to unmark this entry. 
<9> `webScan` _(optional)_ section can be used to define false positive patterns for web scans to provide more possibilities to the user.
<10> `cweId` is used to mark a certain type of finding as false positive.
When handling web scan project data this will be treated as a _mandatory_ field,
but it can be omitted inside this configuration an will then match findings that do not have any `cweId`.
Since it is the integer ID of the CWE, fetching the false positive configuration will contain `"cweId": 0` since cweId zero does not exist.
<11> `urlPattern` specifies a URL pattern to identify a false positive. This is a `mandatory` field. 
Asterisks can be used as wildcards e.g. if you have different environments like DEV, INT, PROD or you have variable parts like in API calls or query paramaters `https://*.example.com/rest/*/search?*`.
<12> `methods` _(optional)_ can be used to further restrict the false positive matching, to specific request methods protocols, like GET, POST, etc.
Like any other _optional_ field, if this is missing it is simply ignored.


Important information on the wildcard approach in `projectData`, regarding web scans: +
- To be a false positive a finding must match the `cweId` and the `urlPattern` of at least one of the false positive entries.
  An _optional_ list of (HTTP) `methods` can be specified to limit the false positive entry to certain `methods`,
  e.g if you specify `"methods": [ "GET", "DELETE" ]` like in the example above that means even if the `cweId` and the `urlPattern` are matching, if the finding was found with a `POST` request it would not be a false positive.
  If no `methods` are specified, this false positive entry will not be restricted to any method. +
- Wildcards (`pass:[*]`) can be used inside `urlPattern`. +
- Wildcards match anything until the next NON-wildcard character. +
- Multiple wildcards can be used in one `urlPattern`. +
- An `urlPattern` which contains only wildcards (`pass:[*]`) is not allowed.
