// SPDX-License-Identifier: MIT
[[section-concept-false-positive-technical-details]]
==== Technical details about false positive handling

There are two different kind of phases: +

1. User definition of false positive definitions
2. Job execution / runtime 

===== Definition phase

When a user has a {sechub} report with some findings - the user can define false positives in two different ways. By 
the report UUID and the finding id which represents the false positive or by providing additional information like patterns to identify a false positive.

The configuration is described at  <<section-false-positives-define-by-API,how to define false positives by API>>.

[IMPORTANT]
====
When using the first approach by providing report UUID and the finding id, the user only gives information about which finding in an existing report is seen as a false positive. While a new
false positive is created, SecHub inspects the report and fetches all necessary meta data internally - depending on the scan type. 

These meta data will be stored independently from the report. So even if the report will be deleted afterwards, the false-positive handling
will still work!

When using the second approach the user provides additional data that helps identifying a false positive or even a specific group of false positives.
This approach requires more effort from a user to provide the data which identify the wanted false positives.
But it can be very helpful especially for web scans, where some finding parts dynamically change, like scanner payloads in query parameters or URL paths.
====

At this phase duplicate checks are only done for tuples of report UUID and finding id! The second approach with the additional projectData works a differently, since entries with the same `id` will be updated! +
*Meta data is only collected in definition phase, but NOT inspected!* !

[NOTE]
====

Here a simple example for better understanding.

On the first approach with finding id and report UUID:

- A user has 10 reports but containing always the same finding
- The user marks for all of these reports the finding again as false positive
- This will result in 10 false positive entries (and it's meta data) inside the database 
  because SecHub does NOT inspect at this time that we have duplicates here!

On the second approach with the additional data for the project:

- A user has specific type of finding that are all false positives
- The user marks all of them by providing information to identify these false positives
- One false positive entry with this approach can be used to mark a gruop of false positives. 

====

====== Overview
The next figure shows a simplified UML diagram (shows only relevant parts). Below the figure you will find sub chapters with more information. 

plantuml::diagrams/diagram_falsepositives_definition_overview.puml[format=svg, title="Overview definition phase"]

====== Used storage mechanism

For every {sechub} project a <<section-concept-project-scan-configuration,project scan config>> entry for false positives exists.
The entry does contain a `FalsePositiveProjectConfiguration` object as JSON.

====== Data structure
The `FalsePositiveProjectConfiguration` object contains a list of `FalsePositiveEntry` objects.

Every `FalsePositveEntry` object contains either

- `FalsePositiveJobData` +
   contains job uuid, finding id and comment - this information is provided by user.

and

- `FalsePositiveMetaData`  +
   contains meta information about findings - this information is gathered and calculated by {sechub} internally when
   a user has marked a report finding as a false positive. So the meta information is independent (so when a reoprt has
   been deleted, we still have the false positive meta information).

   - It contains many meta information - e.g. a `cweId` - but also `FalsePositiveCodeMetaData` for code scans details.
   
or

- `FalsePositiveProjectData`  +
   contains information to identify a finding or a group of findings as false positives. Currently it can only be used for web scans.
   In <<section-false-positives-define-by-API,how to define false positives by API>> the example shows all __mandatory__ and __optional__ parameters.
   
but never both in one `FalsePositveEntry`.

====== Definition by user
A user does define a `FalsePositiveDataList` object which contains a list of `FalsePositiveJobData` or `FalsePositiveProjectData`. Such a list will
be used to add false positives.

To remove a `FalsePositiveJobData` entry from the `FalsePositiveProjectConfiguration`, the user has to provide the job UUID and finding id already used to define this entry.

To remove a `FalsePositiveJobData` entry from the `FalsePositiveProjectConfiguration`, the user has to provide the id defined with the corresponding entry.

====== Merging
When a user adds or removes false positive definitions, the `FalsePositiveProjectConfiguration` will be updated by 
`FalsePositiveDataConfigMerger`.


===== Job execution phase

Here `Sereco` is in charge, which does inspect each `FalsePositveEntry` and use either the meta data or the project data depending on the entry.

====== Overview
plantuml::diagrams/diagram_falsepositives_runtime_overview.puml[format=svg, title="Overview runtime phase"]

