// SPDX-License-Identifier: MIT
[[section-development-servers]]
[[section-sechub-client]]
== SecHub client
=== In a nutshell
The `{sechub}` client program is an executable binary which can be used from command
line or in a build tool of your choice.

It's very easy to use and using the client you have not to handle and REST-API calls by yourself.

NOTE: Currently the client only supports only basic authentication, but of course always only over https.

=== Download
Download the binary for your operating system where you want to trigger `{sechub}` scanning.
You will have no dependencies, just place the single binary file to a location inside your path variable.

The latest releases can be found at {projectSite}/wiki/releases . For documentation please look at {webPage}[{secHub} web page] .

=== Usage

==== Show help
----
sechub -help
----
will print out a simple help of all command line options. Also an almost running example snippet is shown.
The example config file does contain many fake entries, even for `server` and webscan `url`.
Please change to correct values.

==== Actions

Following actions are supported:

===== scan

Does scan synchronous which means

 - will create a `{sechub}` job
 - upload necessary stuff to `{sechub}` (e.g. zipped sourcefiles for source scans)
 - approve job as being ready to start
 - wait for job done,
 - fetch automatically result report to output folder (html or json)
 - break your build when not `green`

TIP: The is the most preferred scan action for builds - you only have to make one
     single client call and your are done.

**Minimum call syntax**
----
sechub -apitoken ${apitoken} scan
----

===== scanAsync

Does scan asynchronous which means

  - will create a `{sechub}` job
  - upload necessary stuff to `{sechub}` (e.g. zipped sourcefiles for source scans)
  - approve job as being ready to start
  - returns `{sechub}` job UUID +
    which can be used to get status and also reports etc.
  - will **never** break your build!

TIP: This can be interesting if you have long running scans and you want have a fast
     continous integration build - but **be aware** that you have to manually check
     job state, fetch reports and you got no automated build break!


**Minimum call syntax**
----
sechub -apitoken ${apitoken} scanAsync
----


===== getStatus
Will fetch current job status and return result as json or html

**Minimum call syntax**
----
sechub -apitoken ${apitoken} -jobUUID ยง{jobUUID} getStatus
----

===== getReport
Will fetch report as json (result will only exist when job is done)

**Minimum call syntax**
----
sechub -apitoken ${apitoken} -jobUUID ยง{jobUUID} getReport
----
==== Options

- apitoken `<string>` +
  The api token. This is a mandatory option for every action. Can *NOT* be defined in config file
- configfile `<string>` +
  Path to `{sechub}` config file, if not defined `sechub.json` will be used in current directory
- help +
  Shows help and terminates
- jobUUID `<string>` +
  `{sechub}` job uuid (mandatory when using 'getStatus' or 'getReport')
- output `<string>` +
  Output folder for reports etc. per default current dir
- project `<string>` +
  Unique project id - mandatory, but can also be defined in config file
- reportformat `<string>` +
  Output format for reports, supported currently: [html,json]. If not a wellknown format json will always be the fallback. (default "json")
- server `<string>` +
  Server url of `{sechub}` server to use - e.g. https//example.com:8081. Mandatory, but can also be defined in config file
- user `<string>` +
  Username - mandatory, but can also be defined in config file
- version +
  Shows version info and terminates
- wait `<int>` + +
       wait time in seconds. Will be used for automatic status checks etc. when action='scan'. Default is 60 seconds (default 60)

=== Configuration file
If not defined, secHub client will load `sechub.json` file from current directory
and use it as sechub configuration. There must be always a valid configuration
file - otherwise client will not work.

==== Variables inside configuration files
All environment variables are available inside your configuration file in go
template syntax:

`{{ .ENV_VARIABLE_NAME }}`

For example: When you have defined `USED_API_VERSION` with value `1.0`, you can use
it in json config like

[source,json]
----
{
    "apiVersion" : "{{ .USED_API_VERSION }}"
}
----

`{sechub} client` will automatically fill the variable with content from environment
variable.

TIP: When you have enabled debug log by setting environment entry `SECHUB_DEBUG` to `true`
you will see network traffic and also JSON sent to server. This JSON will only
contain the origin template but not the replaced parts. This was done to prevent
accidently logging of variables - e.g. credentials.


include::../../shared/configuration/sechub_config.adoc[]

=== Examples

NOTE: Next following sub chapters contain some `{sechub}` configuration examples.
      You can use them as templates for your own files.
      At least replace example credentials `7536a8c4aa82407da7e06bdbEXAMPLE` and `alice` with your real ones to
      get them working.

==== Start a source scan

[source, bash]
----
sechub -apitoken 7536a8c4aa82407da7e06bdbEXAMPLE scan
----
with corresponding 'sechub.json' config file: see <<sechub-config-example-sourcescan,source scan example>> .

WARNING: Currently wrong defined folder setup will be not checked by client. So when wrong configured you will upload no sources...


==== Start a web scan

[source, bash]
----
sechub -apitoken 7536a8c4aa82407da7e06bdbEXAMPLE scan
----
with corresponding 'sechub.json' config file:
see <<sechub-config-example-webscan-anonymous,web scan example (anonymous)>>

==== Start a infra scan

[source, bash]
----

sechub -apitoken 7536a8c4aa82407da7e06bdbEXAMPLE scan
----
with corresponding `sechub.json` config file: <<sechub-config-example-infrascan-with-ip, infrastructure scan example>> .
