// SPDX-License-Identifier: MIT
[[section-development-servers]]
[[section-sechub-client]]
== SecHub client
=== In a nutshell
The `{sechub}` client program is an executable binary which can be used from command
line or in a build tool of your choice.

It's very easy to use and you do not have to handle all the REST-API calls by yourself.

NOTE: Currently the client only supports basic authentication, but of course always only over https.

=== Download
Download the binary for your operating system where you want to trigger `{sechub}` scanning.
You will have no dependencies, just place the single binary file to a location inside your path variable.

The latest releases can be found at {projectSite}/wiki/releases . For documentation please look at {webPage}[{secHub} web page] .

=== Supported Platforms

The SecHub Client is available for a number of platforms. A platform is a combination of an operating system and a CPU architecture.

.Supported platforms
|===
|Name |OS |CPU Architecture |Description

|darwin-amd64
|macOS
|AMD and Intel 64-bit
|The **macOS client**.

|linux-386
|Linux
|AMD and Intel 32-bit
|For old hardware running Linux as operating system.

|linux-amd64
|Linux
|AMD and Intel 64-bit
|The **Linux client**, unless you are using older hardware or an ARM system.

|linux-arm
|Linux
|ARM 32-bit
|For ARM 32-bit systems. For example, single board computers such as the Raspberry PIs, older Nvidia Jetson boards and many more.

|linux-arm64
|Linux
|ARM 64-bit
|For ARM 64-bit systems, such as ARM based servers and some single board computers. Examples include newer models of the Nvidia Jetson series, newer Raspberry PI models, servers from the Marvell ThunderX series and Amazon AWS EC2 A1, T4g, M6g, C6g, and R6g instances.

|windows-386
|Windows
|AMD and Intel 32-bit
|For older hardware running Windows as operating system.

|windows-amd64
|Windows
|AMD and Intel 64-bit
|The **Windows client**, unless you are using older 32-bit hardware.
|===

In case your platform is not included in the table, you might be able to compile the SecHub Client for your platform. The SecHub Client is written in the Go programming language. Go supports more platforms. For a full list of supported platforms have a look at the Go documentation: https://golang.org/doc/install/source#environment[Optional environment variables].

=== Usage

==== Show help
----
sechub -help
----
will print out a simple help of all command line options. Also an almost running example snippet is shown.
The example config file does contain many fake entries, even for `server` and webscan `url`.
Please change to correct values.

==== Actions

Following actions are supported:

===== scan

Does scan synchronous which means

 - will create a `{sechub}` job
 - upload necessary stuff to `{sechub}` (e.g. zipped sourcefiles for source scans)
 - approve job as being ready to start
 - wait for job done,
 - fetch automatically result report to output folder (html or json)
 - break your build when not `green`

TIP: For security reasons always pass your api token via the environment variable `SECHUB_APITOKEN`.

TIP: The is the most preferred scan action for builds - you only have to make one
     single client call and your are done.

**Minimum call syntax**

Prerequisite is a configuration file `sechub.json` in current directory. +
See here for details: <<section-client-configuration-file,Configuration file>>
----
SECHUB_APITOKEN=${apitoken}
sechub scan
----

===== scanAsync

Does scan asynchronous which means

  - will create a `{sechub}` job
  - upload necessary stuff to `{sechub}` (e.g. zipped sourcefiles for source scans)
  - approve job as being ready to start
  - returns `{sechub}` job UUID +
    which can be used to get status and also reports etc.
  - will **never** break your build!

TIP: This can be interesting if you have long running scans and you want have a fast
     continous integration build - but **be aware** that you have to manually check
     job state, fetch reports and you got no automated build break!


**Minimum call syntax**
----
SECHUB_APITOKEN=${apitoken}
sechub scanAsync
----


===== getStatus
Will fetch current job status and return result as json or html

**Minimum call syntax**
----
SECHUB_APITOKEN=${apitoken}
sechub -jobUUID ${jobUUID} getStatus
----

===== getReport
Will fetch report as json (result will only exist when job is done)

**Minimum call syntax**
----
SECHUB_APITOKEN=${apitoken}
sechub -jobUUID ${jobUUID} getReport
----


[[section-client-false-positives-mark]]
===== markFalsePositives
Read your report carefully and check which of the findings are really "false positives" (FP).
After this, create a json file containing jobUUID and ID of finding you decided to be a FP. If 
you like you can add an optional comment, describing your decision to mark this as FP.
Select this file by the `-file` argument and start action `markFalsePositives`.

*Example JSON:*

[source, json]
----
include::../../shared/concepts/false-positive-handling/false-positive-REST-API-content-example1.json[]
----
<1> api version
<2> type - must be `falsePositiveJobDataList`
<3> job where finding was in report
<4> ID of finding, which shall be marked as false positive
<5> Comment (optional) describing the reason why this is handled as false positive


===== getFalsePositives
This will fetch the false positives list of your project as JSON - format is same as for `markFalsePositives`


[[section-client-false-positives-unmark]]
===== unmarkFalsePositives
When you want to remvoe a former defined false positive entry you can do this the same way
as for mark operation: Just define a JSON file, select the file by the `-file` argument and start
action `unmarkFalsePositives`

*Example JSON:*

[source, json]
----
include::sechub_client_falsepositve_list_example_unmark.json[]
----

===== interactiveMarkFalsePositives
Instead of creating a json file to mark false positives, you can also do this interactively:
Go to the project directory containing `sechub.json` and a report file from a recent scan and run `sechub interactiveMarkFalsePositives`.

You can select the report file using the `-file` option of the client. Otherwise the latest report file in the current directory is automatically selected.

For each finding in the reports file, you are prompted: `"Add this as false positive?"`
Your choices are:

- `y` Yes - Mark as false positive. You are prompted for an optional comment line which can help to understand later why this has been marked.
- `n` No - Do nothing and go to next item.
- `s` Skip following findings - End the asking here and add the marked items to the false positives list on the sechub server.
- `c` Cancel - Quit and upload nothing

You can download and view your current false positives list with <<section-client-getFalsePositives,getFalsePositives>>

See also <<section-client-interactiveMarkFalsePositives-mark,example for interactiveMarkFalsePositives>> 

===== interactiveUnmarkFalsePositives
Instead of creating a json file to unmark false positives, you can also do this interactively:
Go to the project directory containing `sechub.json` and run `sechub interactiveUnmarkFalsePositives`

{sechub} client will download the current false posisitves list and interactively ask each entry: `"Do you want to remove this false positive?"`
Your choices are:

- `y` Yes - Unmark this false positive.
- `n` No - Do nothing and go to next item.
- `s` Skip the rest - End the asking here and remove the marked items from the false positives list on the sechub server.
- `c` Cancel - Quit and change nothing

See also <<section-client-interactiveMarkFalsePositives-mark,example for interactiveMarkFalsePositives>> 


==== Configuration overview
Basically parameters can be passed to the `{sechub}` client in three ways:

- commandline options (overrides below)
- environment variables (overrides config file)
- configuration file (default `sechub.json`)

In below table, there is an overview of what can be defined where.
|===
| *parameter* | *cmdline option* | *environment variable* | *config json file*
| api token | -apitoken _(!! not recommended !!)_ | SECHUB_APITOKEN |
| code scan config ||| codeScan
| configuration file | -configfile ||
| file | -file ||
| job uuid | -jobUUID ||
| network timeout | -timeout||
| output folder | -output ||
| poll interval | -wait | SECHUB_WAITTIME_DEFAULT |
| project id | -project | SECHUB_PROJECT |project
| quiet mode | -quiet | SECHUB_QUIET |
| report format | -reportformat||
| server url | -server | SECHUB_SERVER | server
| stop on yellow | -stop-on-yellow||
| user id | -user | SECHUB_USERID | user
| web scan config ||| webScan
|===


==== Mandatory parameters
Here is an overview of mandatory parameter for each `action`:
|===
| *action* | *mandatory parameters*
| scan |server + user + api token + projectID + configFile 
| scanAsync |server + user + api token + projectID + configFile 
| getStatus |server + user + api token + projectID + secHubJobUUID 
| getReport |server + user + api token + projectID + secHubJobUUID 
| getFalsePositives |server + user + api token + projectID
| markFalsePositives |server + user + api token + projectID + file 
| unmarkFalsePositives |server + user + api token + projectID + file 
| interactiveMarkFalsePositives |server + user + api token + projectID + (file only if no report file is in current dir)
| interactiveUnmarkFalsePositives |server + user + apiToken + projectID 
| help |
| version |
|===


==== Commandline Options

- `-apitoken <string>` +
  The api token. Although you can pass it as a runtime option, it is recommended for security reasons to define the environment variable `SECHUB_APITOKEN` (see: <<Environment variables>>) and not to use this option.
  Can *NOT* be defined in config file
- `-configfile <string>` +
  Path to `{sechub}` config file, if not defined `sechub.json` will be used in current directory
- `-file <string>` +
  Defines file to read from for actions `markFalsePositives` or `interactiveMarkFalsePositives` or `unmarkFalsePositives`
- `-help` +
  Shows help and terminates
- `-jobUUID <string>` +
  `{sechub}` job uuid (mandatory when using 'getStatus' or 'getReport')
- `-output <string>` +
  Output folder for reports etc. per default current dir
- `-project <string>` +
  Unique project id - mandatory, but can also be defined in config file or via environment variable.
- `-quiet` +
  Quiet mode - Suppress all informative output. Can also be defined via environment variable `SECHUB_QUIET=true`. +
  Only print filenames written to, errors and explicitely requested informations (job-UUID, version, status).
- `-reportformat <string>` +
  Output format for reports, supported currently: [html,json]. If not a wellknown format json will always be the fallback. (default "json")
- `-server <string>` +
  Server url of `{sechub}` server to use - e.g. https//example.com:8081. Mandatory, but can also be defined in config file or via environment variable.
- `-stop-on-yellow` +
  Makes a yellow traffic light in the scan result also break the build
- `-timeout <integer>` +
  Timeout for network communication in seconds. (default 120)
- `-user <string>` +
  Username - mandatory, but can also be defined in config file or via environment variable.
- `-version` +
  Shows version info and terminates
- `-wait <integer>` + 
       wait time in seconds (default 60). 
       Will be used for periodic status checks when action=`scan`.

==== Environment variables
Additionally to above cmdline options, you can set some values also via environment variables which can be helpful when you have different SecHub environments (like: dev, int, prod)

- `SECHUB_APITOKEN` +
  The SecHub api token for `SECHUB_USERID`. (same as `-apitoken` option)
- `SECHUB_PROJECT` +
  The SecHub project id. (same as `-project` option)
- `SECHUB_QUIET` +
  Quiet mode (`true` or `false` / unset) - Suppress all informative output. (same as `-quiet` option)
- `SECHUB_SERVER` +
  The SecHub server url. (same as `-server` option)
- `SECHUB_USERID` +
  The SecHub username. (same as `-user` option)
- `SECHUB_TRUSTALL` +
  When set to `true`, then HTTPS certificate checking will be disabled. May be useful when using self-signed certificates. Please try to avoid this setting for security reasons.

Settings for debugging/client development:

- `SECHUB_DEBUG` +
  When set to `true` then log as much as possible
- `SECHUB_IGNORE_DEFAULT_EXCLUDES` +
  When set to `true` then default exclude folders `+{"**/test/**", "**/.git/**"}+` will be included for code scan. In this case, you should declare your own exclude list in the config json.
- `SECHUB_KEEP_TEMPFILES` +
  When set to `true` then .zip files for code scan will not be removed, so you can check, what was uploaded to the `{sechub}` server
- `SECHUB_WAITTIME_DEFAULT` +
  Wait time in seconds (default 60). Will be used for automatic status checks etc. when action=`scan`.
  Try to avoid setting it shorter than 60 seconds, because the load on the `{sechub}` server will be increased.


==== Proxy support
The environment variables `http_proxy`, `https_proxy` and `no_proxy` (or the uppercase versions thereof) can be set to use a proxy for accessing the `{sechub}` server.
(`https_proxy` takes precedence over `http_proxy` for https requests.)

Syntax: `[<scheme>://][<username>:<password>@]<proxy host>[:<proxy port>]`

The environment values may be either a complete URL or a "host[:port]", in which case the "http" scheme is assumed.

Examples (Linux/Mac):

`export http_proxy=http://scott:tiger@proxy.example.org:3128`

`export http_proxy=http://localhost:3128` (e.g. when using a local CNTLM proxy)

[[section-client-configuration-file]]

=== Client configuration file
If not defined by option `-configfile`, secHub client will attempt to load `sechub.json` file from current directory
and use it as sechub configuration.

For scan actions, a valid configuration file is needed. Other actions like getReport or false-positives handling need no configuration file.

==== Variables inside configuration files
For advanced users: All environment variables are available inside your configuration file in go
template syntax:

`{{ .ENV_VARIABLE_NAME }}`

For example: When you have defined `USED_API_VERSION` with value `1.0`, you can use
it in json config like

[source,json]
----
include::sechub_config_apiversion_example.json[]
----

`{sechub} client` will automatically fill the variable with content from environment
variable.

TIP: When you have enabled debug log by setting environment entry `SECHUB_DEBUG` to `true`
you will see network traffic and also JSON sent to server. This JSON will only
contain the origin template but not the replaced parts. This was done to prevent
accidently logging of variables - e.g. credentials.

==== Accepted source code files
The client will per default only include wellknown source files.
This is done by inspecting the filename ending. The accepted defaults are shown in next table.

*All files having file endings not listed here, will be ignored* and not contained in source upload to
{sechub} server! 

NOTE: But of course you can also define additional source file endings - see <<sechub-config-example-sourcescan,config file example>> .

include::../../gen/client/gen_table_default_zip_allowed_file_patterns.adoc[]

include::../../shared/configuration/sechub_config.adoc[]

=== Examples

NOTE: Next following sub chapters contain some `{sechub}` configuration examples.
      You can use them as templates for your own files.
      At least replace example credentials `7536a8c4aa82407da7e06bdbEXAMPLE` and `alice` with your real ones to
      get them working.

==== Start a source scan

[source, bash]
----
SECHUB_APITOKEN=7536a8c4aa82407da7e06bdbEXAMPLE
sechub scan
----
with corresponding 'sechub.json' config file: see <<sechub-config-example-sourcescan,source scan example>> .


==== Start a web scan

[source, bash]
----
SECHUB_APITOKEN=7536a8c4aa82407da7e06bdbEXAMPLE
sechub scan
----
with corresponding 'sechub.json' config file:
see <<sechub-config-example-webscan-anonymous,web scan example (anonymous)>>

==== Start an infra scan

[source, bash]
----
SECHUB_APITOKEN=7536a8c4aa82407da7e06bdbEXAMPLE
sechub scan
----
with corresponding `sechub.json` config file: <<sechub-config-example-infrascan-with-ip, infrastructure scan example>> .

==== Mark false positives
[source, bash]
----
SECHUB_APITOKEN=7536a8c4aa82407da7e06bdbEXAMPLE
sechub -file mark-fp.json markFalsePositives
----
with a corresponding `mark-fp.json` - see <<section-client-false-positives-mark,Mark false positives JSON format>> 

==== Unmark false positives
[source, bash]
----
SECHUB_APITOKEN=7536a8c4aa82407da7e06bdbEXAMPLE
sechub -file mark-fp.json unmarkFalsePositives
----
with a corresponding `mark-fp.json` - see <<section-client-false-positives-unmark,Unmark false positives JSON format>> 

[[section-client-interactiveMarkFalsePositives-mark]]
===== interactiveMarkFalsePositives
[source, shell]
```
SECHUB_APITOKEN=7536a8c4aa82407da7e06bdbEXAMPLE
sechub interactiveMarkFalsePositives

/  ___|         | | | |     | |    
\ `--.  ___  ___| |_| |_   _| |__  
 `--. \/ _ \/ __|  _  | | | | '_ \ 
/\__/ /  __/ (__| | | | |_| | |_) |
\____/ \___|\___\_| |_/\__,_|_.__/ Client Version 0.20.0-b78

Using latest report file "sechub_report_0a84899f-1305-41e0-a2d5-e7c31d6185fd.json".
------------------------------------------------------------------
1: Side Channel Data Leakage, severity: HIGH
src/main/java/com/example/testapp/invoice/application/InvoiceApplicationService.java, line 651 column 17
        Invoice creditNote = getInvoice(invoiceId).orElseThrow(InvoiceNotFoundException::new);
------------------------------------------------------------------
Add this as false positive? ('y' Yes, 'n' No, 's' Skip following findings, 'c' Cancel) y
Please add a single line comment:
Can be ignored in our case
------------------------------------------------------------------
2: Unsafe Object Binding, severity: MEDIUM
src/main/java/com/example/testapp/api/ServiceOrderController.java, line 33 column 59
    public void saveAttachment(@RequestBody AttachmentDto attachmentDto){
------------------------------------------------------------------
Add this as false positive? ('y' Yes, 'n' No, 's' Skip following findings, 'c' Cancel) n
------------------------------------------------------------------
3: Unsafe Object Binding, severity: MEDIUM
src/main/java/com/example/testapp/api/CouponController.java, line 30 column 78
    public CouponVerifyResponseDto couponVerify(@RequestBody CouponVerifyDto couponVerifyDto) {
------------------------------------------------------------------
Add this as false positive? ('y' Yes, 'n' No, 's' Skip following findings, 'c' Cancel) s
- Successfully uploaded SecHub false-positives list for project "mytestproject" to server.
```

[[section-client-interactiveUnmarkFalsePositives-mark]]
===== interactiveUnmarkFalsePositives
[source, shell]
```
SECHUB_APITOKEN=7536a8c4aa82407da7e06bdbEXAMPLE
sechub interactiveUnmarkFalsePositives
 _____           _   _       _
/  ___|         | | | |     | |
\ `--.  ___  ___| |_| |_   _| |__
 `--. \/ _ \/ __|  _  | | | | '_ \
/\__/ /  __/ (__| | | | |_| | |_) |
\____/ \___|\___\_| |_/\__,_|_.__/ Client Version 0.20.0-b78

- Fetching false-positives list for project "mytestproject".
------------------------------------------------------------------
Side Channel Data Leakage, codeScan severity: HIGH
  Origin: Finding ID 1 in job 0a84899f-1305-41e0-a2d5-e7c31d6185fd
  File: src/main/java/com/example/testapp/invoice/application/InvoiceApplicationService.java
  Code:         Invoice creditNote = getInvoice(invoiceId).orElseThrow(InvoiceNotFoundException::new);
(Added by testuser at 2020-08-20 12:43:03; comment: "Can be ignored in our case")
------------------------------------------------------------------
Do you want to remove this false positive? ('y' Yes, 'n' No, 's' Skip the rest, 'c' Cancel) y
------------------------------------------------------------------
Side Channel Data Leakage, codeScan severity: HIGH
  Origin: Finding ID 2 in job 0c86134c-2305-41e0-a2d5-e7c31df45d15
  File: src/main/java/com/daimler/otr/invoice/application/ApplicationService.java
  Code:         Invoice invoice = getInvoice(invoiceId).orElseThrow(InvoiceNotFoundException::new);
(Added by testuser at 2020-08-20 12:43:03; comment: "Another explanation example")
------------------------------------------------------------------
Do you want to remove this false positive? ('y' Yes, 'n' No, 's' Skip the rest, 'c' Cancel) s
Applying false-positives to be removed for project "vpc_cn":
- JobUUID 0a84899f-1305-41e0-a2d5-e7c31d6185fd: finding #1
Transfer completed
```
