// SPDX-License-Identifier: MIT
[[section-development-servers]]
[[section-sechub-client]]
== SecHub client
=== In a nutshell
The `{sechub}` client program is an executable binary which can be used from command
line or in a build tool of your choice.

It's very easy to use and using the client you have not to handle and REST-API calls by yourself.

NOTE: Currently the client only supports only basic authentication, but of course always only over https.

=== Download
Download the binary for your operating system where you want to trigger `{sechub}` scanning.
You will have no dependencies, just place the single binary file to a location inside your path variable.

The latest releases can be found at {projectSite}/wiki/releases . For documentation please look at {webPage}[{secHub} web page] .

=== Usage

==== Show help
----
sechub -help
----
will print out a simple help of all command line options. Also an almost running example snippet is shown.
The example config file does contain many fake entries, even for `server` and webscan `url`.
Please change to correct values.

==== Actions

Following actions are supported:

===== scan

Does scan synchronous which means

 - will create a `{sechub}` job
 - upload necessary stuff to `{sechub}` (e.g. zipped sourcefiles for source scans)
 - approve job as being ready to start
 - wait for job done,
 - fetch automatically result report to output folder (html or json)
 - break your build when not `green`

TIP: The is the most preferred scan action for builds - you only have to make one
     single client call and your are done.

**Minimum call syntax**
----
sechub -apitoken ${apitoken} scan
----

===== scanAsync

Does scan asynchronous which means

  - will create a `{sechub}` job
  - upload necessary stuff to `{sechub}` (e.g. zipped sourcefiles for source scans)
  - approve job as being ready to start
  - returns `{sechub}` job UUID +
    which can be used to get status and also reports etc.
  - will **never** break your build!

TIP: This can be interesting if you have long running scans and you want have a fast
     continous integration build - but **be aware** that you have to manually check
     job state, fetch reports and you got no automated build break!


**Minimum call syntax**
----
sechub -apitoken ${apitoken} scanAsync
----


===== getStatus
Will fetch current job status and return result as json or html

**Minimum call syntax**
----
sechub -apitoken ${apitoken} -jobUUID ยง{jobUUID} getStatus
----

===== getReport
Will fetch report as json (result will only exist when job is done)

**Minimum call syntax**
----
sechub -apitoken ${apitoken} -jobUUID ยง{jobUUID} getReport
----
==== Options

- apitoken `<string>` +
  The api token. This is a mandatory option for every action. Can *NOT* be defined in config file
- configfile `<string>` +
  Path to `{sechub}` config file, if not defined `sechub.json` will be used in current directory
- help +
  Shows help and terminates
- jobUUID `<string>` +
  `{sechub}` job uuid (mandatory when using 'getStatus' or 'getReport')
- output `<string>` +
  Output folder for reports etc. per default current dir
- project `<string>` +
  Unique project id - mandatory, but can also be defined in config file
- reportformat `<string>` +
  Output format for reports, supported currently: [html,json]. If not a wellknown format json will always be the fallback. (default "json")
- server `<string>` +
  Server url of `{sechub}` server to use - e.g. https//example.com:8081. Mandatory, but can also be defined in config file
- user `<string>` +
  Username - mandatory, but can also be defined in config file
- version +
  Shows version info and terminates
- wait `<int>` + +
       wait time in seconds. Will be used for automatic status checks etc. when action='scan'. Default is 60 seconds (default 60)

==== Configuration file

A `{sechub}` configuration files must be a valid json file.
In following sub chapters the elements inside JSON format are described

===== API version
`apiVersion` must be defined (so mandatory). Currently only `1.0` is valid.

===== Server
`server` (optional) defines the location to `{sechub}` server. Normally always `https://sechub.example.org`.
This option can be set as CLI option as well. CLI option overrides value from configuration script!

===== Project
`project` (optional) defines the project to use.
This option can be set as CLI option as well. CLI option overrides value from configuration script!

===== Code scan
`codeScan` (optional) defines the code scan settings.
(see <<sechub-client-example-sourcescan-config,source scan configuration example>>)

====== Use uploaded sources from file system
Define `fileSystem` child entry and setup folders to use for code scanning by
`folders` sub entry. +
Those folders will be automatically zipped and uploaded to SecHub server for ongoing source analysis.

The folders should be defined relatively from caller location - for example on a Jenkins Build Server
this is normally the root folder of repository(see
<<sechub-client-example-sourcescan-config,source scan configuration example>>)

WARNING: Currently wrong defined folder setup will be not checked by client. So when wrong configured you will upload no sources...

===== Web scan
`webScan` (optional) defines the web scan settings (see <<sechub-client-example-webscan-config,web scan configuration example>>).

====== URIs
Use `uri` element to define a string array containing uris you want to scan.
(see <<sechub-client-example-webscan-config,web scan configuration example>>)

WARNING: URI must be one of the whitelisted URLs of your project. Otherwise it will be rejected.
         So your are not able to start scanning foreign domains and do _accidently_ an DoS attack...

===== Infrastructure scan
`infraScan` (optional) defines the infrastructure scan settings (see <<sechub-client-example-infrascan-config,web scan configuration example>>).

====== URIs
Use `uri` element to define a string array containing uris you want to scan.
(see <<sechub-client-example-webscan-config,web scan configuration example>>)

====== IPs
Use `ips` element to define a string array containing `IP` s you want to scan.

==== Examples

NOTE: Next following sub chapters contain some `{sechub}` configuration examples.
      You can use them as templates for your own files.
      At least replace example credentials `7536a8c4aa82407da7e06bdbEXAMPLE` and `alice` with your real ones to
      get them working.

===== Start a source scan

[source, bash]
----
sechub -apitoken 7536a8c4aa82407da7e06bdbEXAMPLE scan
----
with corresponding 'sechub.json' config file:
[[sechub-client-example-sourcescan-config]]
[source, json]
----
      {

        "apiVersion": "1.0",
        "server"    : "https://sechub.example.org",

        "project"   : "gamechanger",

        "codeScan": {<1>
           "fileSystem": {<2>
              "folders": ["gamechanger-android/src/main/java",
                          "gamechanger-server/src/main/java"], //<3>
           "excludes"  : ["**/*.log","README*.md"]  //<4>
        }
      }
----
<1> Define code scan
<2> Use filesystem - so means upload sources to server
<3> Upload will contain sources from `gamechanger-android/src/main/java` and `gamechanger-server/src/main/java` and their sub folders
<4> Exclude files (optional), syntax is similar to https://ant.apache.org/manual/Types/fileset.html[ANT fileset] - `+**/*+` is used to identify any folder +
    In example above following files are excluded from upload: +
    * `+**/*.log+` - excludes any log file in any sub directories of given folders
    * `+README*.md+` excludes all markdown README files in given folders. For example above this means:
      ** `gamechanger-android/src/main/java/README.md` and
      ** `gamechanger-server/src/main/java/README.md`

===== Start a web scan

[source, bash]
----
sechub -apitoken 7536a8c4aa82407da7e06bdbEXAMPLE scan
----
with corresponding 'sechub.json' config file:
[[sechub-client-example-webscan-config]]
[source, json]
----

      {
        "apiVersion": "1.0",

        "server"   : "https://sechub.example.org",
        "user"     : "alice",

        "project"  : "gamechanger",

        "webScan"  : {//<1>
            "uris": ["https://www.gamechanger.example.org"]//<2>
        }
      }
----
<1> Define web scan
<2> The `URI` s to scan. Every `URI` listed here must be white listed in `{sechub}` project.

===== Start a infra scan

[source, bash]
----

sechub -apitoken 7536a8c4aa82407da7e06bdbEXAMPLE scan
----
with corresponding `sechub.json` config file:
[[sechub-client-example-infrascan-config]]
[source, json]
----

      {
        "apiVersion": "1.0",

        "server"   : "https://sechub.example.org",
        "user"     : "alice",

        "project"  : "gamechanger",

        "infraScan": {//<1>
            "uris": ["https://www.gamechanger.example.org/"]//<2>
        }
      }
----
<1> Define infrastructure scan
<2> The `URI` s to scan. Every `URI` listed here must be white listed in `{sechub}` project.