// SPDX-License-Identifier: MIT
[[section-development-servers]]
[[section-sechub-client]]
== SecHub client
=== In a nutshell
The `{sechub}` client program is an executable binary which can be used from command
line or in a build tool of your choice.

It's very easy to use and using the client you have not to handle and REST-API calls by yourself.

NOTE: Currently the client only supports only basic authentication, but of course always only over https.

=== Download
Download the binary for your operating system where you want to trigger `{sechub}` scanning.
You will have no dependencies, just place the single binary file to a location inside your path variable.

The latest releases can be found at {projectSite}/wiki/releases . For documentation please look at {webPage}[{secHub} web page] .

=== Usage

==== Show help
----
sechub -help
----
will print out a simple help of all command line options. Also an almost running example snippet is shown.
The example config file does contain many fake entries, even for `server` and webscan `url`.
Please change to correct values.

==== Actions

Following actions are supported:

===== scan

Does scan synchronous which means

 - will create a `{sechub}` job
 - upload necessary stuff to `{sechub}` (e.g. zipped sourcefiles for source scans)
 - approve job as being ready to start
 - wait for job done,
 - fetch automatically result report to output folder (html or json)
 - break your build when not `green`

TIP: For security reasons always pass your api token via the environment variable `SECHUB_APITOKEN`.

TIP: The is the most preferred scan action for builds - you only have to make one
     single client call and your are done.

**Minimum call syntax**

Prerequisite is a configuration file `sechub.json` in current directory. +
See here for details: <<section-client-configuration-file,Configuration file>>
----
SECHUB_APITOKEN=${apitoken}
sechub scan
----

===== scanAsync

Does scan asynchronous which means

  - will create a `{sechub}` job
  - upload necessary stuff to `{sechub}` (e.g. zipped sourcefiles for source scans)
  - approve job as being ready to start
  - returns `{sechub}` job UUID +
    which can be used to get status and also reports etc.
  - will **never** break your build!

TIP: This can be interesting if you have long running scans and you want have a fast
     continous integration build - but **be aware** that you have to manually check
     job state, fetch reports and you got no automated build break!


**Minimum call syntax**
----
SECHUB_APITOKEN=${apitoken}
sechub scanAsync
----


===== getStatus
Will fetch current job status and return result as json or html

**Minimum call syntax**
----
SECHUB_APITOKEN=${apitoken}
sechub -jobUUID ${jobUUID} getStatus
----

===== getReport
Will fetch report as json (result will only exist when job is done)

**Minimum call syntax**
----
SECHUB_APITOKEN=${apitoken}
sechub -jobUUID ${jobUUID} getReport
----


[[section-client-false-positives-mark]]
===== markFalsePositives
Read your report carefully and check which of the findings are really "false positives" (FP).
After this, create a json file containing jobUUID and ID of finding you decided to be a FP. If 
you like you can add an optional comment, describing your decision to mark this as FP.
Select this file by the `-file` argument and start action `markFalsePositives`.

*Example JSON:*

[source, json]
----
include::../../shared/concepts/false-positive-handling/false-positive-REST-API-content-example1.json[]
----
<1> api version
<2> type - must be `falsePositiveJobDataList`
<3> job where finding was in report
<4> ID of finding, which shall be marked as false positive
<5> Comment (optional) describing the reason why this is handled as false positive


===== getFalsePositives
This will fetch the false positives list of your project as JSON - format is same as for `markFalsePositives`


[[section-client-false-positives-unmark]]
===== unmarkFalsePositives
When you want to remvoe a former defined false positive entry you can do this the same way
as for mark operation: Just define a JSON file, select the file by the `-file` argument and start
action `unmarkFalsePositives`

*Example JSON:*

[source, json]
----
include::sechub_client_falsepositve_list_example_unmark.json[]
----

===== interactiveMarkFalsePositives
Instead of creating a json file to mark false positives, you can also do this interactively:
Go to the project directory containing `sechub.json` and a report file from a recent scan and run `sechub interactiveMarkFalsePositives`.

You can select the report file using the `-file` option of the client. Otherwise the latest report file in the current directory is automatically selected.

For each finding in the reports file, you are prompted: `"Add this as false positive?"`
Your choices are:

- `y` Yes - Mark as false positive. You are prompted for an optional comment line which can help to understand later why this has been marked.
- `n` No - Do nothing and go to next item.
- `s` Skip following findings - End the asking here and add the marked items to the false positives list on the sechub server.
- `c` Cancel - Quit and upload nothing

You can download and view your current false positives list with <<section-client-getFalsePositives,getFalsePositives>>

See also <<section-client-interactiveMarkFalsePositives-mark,example for interactiveMarkFalsePositives>> 

===== interactiveUnmarkFalsePositives
Instead of creating a json file to unmark false positives, you can also do this interactively:
Go to the project directory containing `sechub.json` and run `sechub interactiveUnmarkFalsePositives`

{sechub} client will download the current false posisitves list and interactively ask each entry: `"Do you want to remove this false positive?"`
Your choices are:

- `y` Yes - Unmark this false positive.
- `n` No - Do nothing and go to next item.
- `s` Skip the rest - End the asking here and remove the marked items from the false positives list on the sechub server.
- `c` Cancel - Quit and change nothing

See also <<section-client-interactiveMarkFalsePositives-mark,example for interactiveMarkFalsePositives>> 


==== Commandline Options

- `-apitoken <string>` +
  The api token. Although you can pass it as a runtime option, it is recommended for security reasons to define the environment variable `SECHUB_APITOKEN` (see: <<Environment variables>>) and not to use this option.
  Can *NOT* be defined in config file
- `-configfile <string>` +
  Path to `{sechub}` config file, if not defined `sechub.json` will be used in current directory
- `-help` +
  Shows help and terminates
- `-jobUUID <string>` +
  `{sechub}` job uuid (mandatory when using 'getStatus' or 'getReport')
- `-output <string>` +
  Output folder for reports etc. per default current dir
- `-project <string>` +
  Unique project id - mandatory, but can also be defined in config file
- `-reportformat <string>` +
  Output format for reports, supported currently: [html,json]. If not a wellknown format json will always be the fallback. (default "json")
- `-server <string>` +
  Server url of `{sechub}` server to use - e.g. https//example.com:8081. Mandatory, but can also be defined in config file or via environment variable.
- `-user <string>` +
  Username - mandatory, but can also be defined in config file or via environment variable.
- `-version` +
  Shows version info and terminates
- `-wait <integer>` + 
       wait time in seconds (default 60). 
       Will be used for automatic status checks etc. when action=`scan`.

==== Environment variables
Additionally to above cmdline options, you can set some values also via environment variables which can be helpful when you have different SecHub environments (like: dev, int, prod)

- `SECHUB_USERID` +
  The SecHub username. (same as `-user` option)
- `SECHUB_APITOKEN` +
  The SecHub api token for `SECHUB_USERID`. (same as `-apitoken` option)
- `SECHUB_SERVER` +
  The SecHub server url. (same as `-server` option)

[[section-client-configuration-file]]

=== Client configuration file
If not defined, secHub client will load `sechub.json` file from current directory
and use it as sechub configuration. There must be always a valid configuration
file - otherwise client will not work.

==== Variables inside configuration files
All environment variables are available inside your configuration file in go
template syntax:

`{{ .ENV_VARIABLE_NAME }}`

For example: When you have defined `USED_API_VERSION` with value `1.0`, you can use
it in json config like

[source,json]
----
include::sechub_config_apiversion_example.json[]
----

`{sechub} client` will automatically fill the variable with content from environment
variable.

TIP: When you have enabled debug log by setting environment entry `SECHUB_DEBUG` to `true`
you will see network traffic and also JSON sent to server. This JSON will only
contain the origin template but not the replaced parts. This was done to prevent
accidently logging of variables - e.g. credentials.

==== Accepted source code files
The client will per default only include wellknown source files.
This is done by inspecting the filename ending. The accepted defaults are shown in next table.

*All files having file endings not listed here, will be ignored* and not contained in source upload to
{sechub} server! 

NOTE: But of course you can also define additional source file endings - see <<sechub-config-example-sourcescan,config file example>> .

include::../../gen/client/gen_table_default_zip_allowed_file_patterns.adoc[]

include::../../shared/configuration/sechub_config.adoc[]

=== Examples

NOTE: Next following sub chapters contain some `{sechub}` configuration examples.
      You can use them as templates for your own files.
      At least replace example credentials `7536a8c4aa82407da7e06bdbEXAMPLE` and `alice` with your real ones to
      get them working.

==== Start a source scan

[source, bash]
----
SECHUB_APITOKEN=7536a8c4aa82407da7e06bdbEXAMPLE
sechub scan
----
with corresponding 'sechub.json' config file: see <<sechub-config-example-sourcescan,source scan example>> .


==== Start a web scan

[source, bash]
----
SECHUB_APITOKEN=7536a8c4aa82407da7e06bdbEXAMPLE
sechub scan
----
with corresponding 'sechub.json' config file:
see <<sechub-config-example-webscan-anonymous,web scan example (anonymous)>>

==== Start an infra scan

[source, bash]
----
SECHUB_APITOKEN=7536a8c4aa82407da7e06bdbEXAMPLE
sechub scan
----
with corresponding `sechub.json` config file: <<sechub-config-example-infrascan-with-ip, infrastructure scan example>> .

==== Mark false positives
[source, bash]
----
SECHUB_APITOKEN=7536a8c4aa82407da7e06bdbEXAMPLE
sechub -f mark-fp.json markFalsePositives
----
with a corresponding `mark-fp.json` - see <<section-client-false-positives-mark,Mark false positives JSON format>> 

==== Unmark false positives
[source, bash]
----
SECHUB_APITOKEN=7536a8c4aa82407da7e06bdbEXAMPLE
sechub -f mark-fp.json unmarkFalsePositives
----
with a corresponding `mark-fp.json` - see <<section-client-false-positives-unmark,Unmark false positives JSON format>> 

[[section-client-interactiveMarkFalsePositives-mark]]
===== interactiveMarkFalsePositives
[source, shell]
```
SECHUB_APITOKEN=7536a8c4aa82407da7e06bdbEXAMPLE
sechub interactiveMarkFalsePositives

/  ___|         | | | |     | |    
\ `--.  ___  ___| |_| |_   _| |__  
 `--. \/ _ \/ __|  _  | | | | '_ \ 
/\__/ /  __/ (__| | | | |_| | |_) |
\____/ \___|\___\_| |_/\__,_|_.__/ Client Version 0.20.0-b78

Using latest report file "sechub_report_0a84899f-1305-41e0-a2d5-e7c31d6185fd.json".
------------------------------------------------------------------
1: Side Channel Data Leakage, severity: HIGH
src/main/java/com/example/testapp/invoice/application/InvoiceApplicationService.java, line 651 column 17
        Invoice creditNote = getInvoice(invoiceId).orElseThrow(InvoiceNotFoundException::new);
------------------------------------------------------------------
Add this as false positive? ('y' Yes, 'n' No, 's' Skip following findings, 'c' Cancel) y
Please add a single line comment:
Can be ignored in our case
------------------------------------------------------------------
2: Unsafe Object Binding, severity: MEDIUM
src/main/java/com/example/testapp/api/ServiceOrderController.java, line 33 column 59
    public void saveAttachment(@RequestBody AttachmentDto attachmentDto){
------------------------------------------------------------------
Add this as false positive? ('y' Yes, 'n' No, 's' Skip following findings, 'c' Cancel) n
------------------------------------------------------------------
3: Unsafe Object Binding, severity: MEDIUM
src/main/java/com/example/testapp/api/CouponController.java, line 30 column 78
    public CouponVerifyResponseDto couponVerify(@RequestBody CouponVerifyDto couponVerifyDto) {
------------------------------------------------------------------
Add this as false positive? ('y' Yes, 'n' No, 's' Skip following findings, 'c' Cancel) s
- Successfully uploaded SecHub false-positives list for project "mytestproject" to server.
```

[[section-client-interactiveUnmarkFalsePositives-mark]]
===== interactiveUnmarkFalsePositives
[source, shell]
```
SECHUB_APITOKEN=7536a8c4aa82407da7e06bdbEXAMPLE
sechub interactiveUnmarkFalsePositives
 _____           _   _       _
/  ___|         | | | |     | |
\ `--.  ___  ___| |_| |_   _| |__
 `--. \/ _ \/ __|  _  | | | | '_ \
/\__/ /  __/ (__| | | | |_| | |_) |
\____/ \___|\___\_| |_/\__,_|_.__/ Client Version 0.20.0-b78

- Fetching false-positives list for project "mytestproject".
------------------------------------------------------------------
Side Channel Data Leakage, codeScan severity: HIGH
  Origin: Finding ID 1 in job 0a84899f-1305-41e0-a2d5-e7c31d6185fd
  File: src/main/java/com/example/testapp/invoice/application/InvoiceApplicationService.java
  Code:         Invoice creditNote = getInvoice(invoiceId).orElseThrow(InvoiceNotFoundException::new);
(Added by testuser at 2020-08-20 12:43:03; comment: "Can be ignored in our case")
------------------------------------------------------------------
Do you want to remove this false positive? ('y' Yes, 'n' No, 's' Skip the rest, 'c' Cancel) y
------------------------------------------------------------------
Side Channel Data Leakage, codeScan severity: HIGH
  Origin: Finding ID 2 in job 0c86134c-2305-41e0-a2d5-e7c31df45d15
  File: src/main/java/com/daimler/otr/invoice/application/ApplicationService.java
  Code:         Invoice invoice = getInvoice(invoiceId).orElseThrow(InvoiceNotFoundException::new);
(Added by testuser at 2020-08-20 12:43:03; comment: "Another explanation example")
------------------------------------------------------------------
Do you want to remove this false positive? ('y' Yes, 'n' No, 's' Skip the rest, 'c' Cancel) s
Applying false-positives to be removed for project "vpc_cn":
- JobUUID 0a84899f-1305-41e0-a2d5-e7c31d6185fd: finding #1
Transfer completed
```
