# SPDX-License-Identifier: MIT

version: "3"
services:
  pds-owasp-zap:
    build:
      args:
        - BASE_IMAGE=${BASE_IMAGE}
      context: docker/
      dockerfile: Owasp-Zap-Debian.dockerfile
    container_name: pds-owasp-zap
    hostname: pds-owasp-zap
    env_file:
      - .env
    networks:
      - "sechub"
    volumes:
      - ./docker/scripts:/scripts

networks:
  sechub:
    external: true
    name: "sechub"
