# SPDX-License-Identifier: MIT

version: "3"
services:
  pds-owasp-zap:
    build:
      args:
        - BASE_IMAGE=${BASE_IMAGE}
      context: docker/
      dockerfile: Owasp-Zap-Debian.dockerfile
    container_name: pds-owasp-zap
    env_file:
      - .env
    ports:
      - "127.0.0.1:8444:8444"
      - "127.0.0.1:15024:15024"
    networks:
      - "sechub"
    volumes:
      - ./docker/scripts:/scripts

networks:
  sechub:
    name: "sechub"
