# SPDX-License-Identifier: MIT

version: "3"
services:
  pds-owasp-zap:
    build:
      args:
        - BASE_IMAGE=ubuntu:20.04
      context: docker/
      dockerfile: Owasp-Zap-Ubuntu.dockerfile
    env_file:
      - .env-cluster
    networks:
      - "internal"
      - "sechub"
    volumes:
      - "shared_volume:/shared_volumes/uploads"
    depends_on:
      - database

  loadbalancer:
    build:
      context: docker/loadbalancer
    env_file:
      - .env-cluster
    networks:
      - "internal"
    depends_on:
      - pds-owasp-zap
    ports:
      - "127.0.0.1:8444:8444"

  database:
    build:
      context: docker/database
    env_file:
      - .env-cluster
    networks:
      - "internal"
    ports:
      - "127.0.0.1:5432:5432"

networks:
  internal:
  sechub:
    name: "sechub"

volumes:
  shared_volume:
