# SPDX-License-Identifier: MIT

version: "3"
services:
    pds_gosec_ubuntu:
        build:
            args:
                - BASE_IMAGE=ubuntu:focal
            context: context/
            dockerfile: Dockerfile-Ubuntu
        env_file:
            - .env
        container_name: pds_gosec_ubuntu
        ports:
            - "8444:8444"
