# SPDX-License-Identifier: MIT

version: "3"
services:
    pds_gosec_alpine:
        build:
            args:
                - BASE_IMAGE=alpine:3.14
            context: context/
            dockerfile: Dockerfile-Alpine
        env_file:
            - .env
        container_name: pds_gosec_alpine
        ports:
            - "8444:8444"
