// SPDX-License-Identifier: MIT
[[section-sechub-client]]
== SecHub client
=== In a nutshell
The `{sechub}` client program is an executable binary which can be used from command
line or in a build tool of your choice.

It's very easy to use and you do not have to handle all the REST-API calls by yourself.

NOTE: Currently the client only supports basic authentication, but of course always only over https.

=== Download
Download the binary for your operating system where you want to trigger `{sechub}` scanning.
You will have no dependencies, just place the single binary file to a location inside your path variable.

Direct download link to the latest client release: {webPage}/latest/client-download.html
For documentation, please look at {webPage}[{sechub} web page] .

=== Supported Platforms

The SecHub Client is available for a number of platforms. A platform is a combination of an operating system and a CPU architecture.

.Supported platforms
|===
|Name |OS |CPU Architecture |Description

|darwin-amd64
|macOS
|AMD and Intel 64-bit
|The **macOS client**.

|darwin-arm64
|macOS
|ARM
|Support for recent Macs with ARM architecture.

|linux-386
|Linux
|AMD and Intel 32-bit
|Universal client for Linux as operating system. Statically linked - no dependencies. Also for older hardware.

|linux-amd64
|Linux
|AMD and Intel 64-bit
|The **Linux client**, unless you are using older hardware or an ARM system. Dynamically linked.

|linux-arm
|Linux
|ARM 32-bit
|For ARM 32-bit systems. For example, single board computers such as the Raspberry PIs, older Nvidia Jetson boards and many more.

|linux-arm64
|Linux
|ARM 64-bit
|For ARM 64-bit systems, such as ARM based servers and some single board computers. Examples include newer models of the Nvidia Jetson series, newer Raspberry PI models, servers from the Marvell ThunderX series and Amazon AWS EC2 A1, T4g, M6g, C6g, and R6g instances.

|windows-386
|Windows
|AMD and Intel 32-bit
|For older hardware running Windows as operating system.

|windows-amd64
|Windows
|AMD and Intel 64-bit
|The **Windows client**, unless you are using older 32-bit hardware.
|===

In case your platform is not included in the table, you might be able to compile the SecHub Client for your platform. The SecHub Client is written in the Go programming language. Go supports more platforms. For a full list of supported platforms have a look at the Go documentation: https://golang.org/doc/install/source#environment[Optional environment variables].

=== Usage

==== Show help
----
sechub help
----
will print out a simple help of all command line options. At the end you will find a link to the latest config and variable examples.

==== Actions

==== Parameter overview for client actions
Here is an overview of the mandatory parameters for each *action*:
|===
| *action* | *mandatory parameters*
| <<section-client-scan,scan>> |server + user + api token + projectID + <<section-client-configuration-file,configFile>>
| <<scanAsync>> |server + user + api token + projectID + <<section-client-configuration-file,configFile>>
| <<getStatus>> |server + user + api token + projectID
| <<getReport>> |server + user + api token + projectID
| <<listJobs>> |server + user + api token + projectID
| <<defineFalsePositives>> |server + user + api token + projectID
| <<getFalsePositives>> |server + user + api token + projectID
| <<interactiveMarkFalsePositives>> |server + user + api token + projectID + (file only if no report file is in current dir)
| <<interactiveUnmarkFalsePositives>> |server + user + apiToken + projectID
| <<markFalsePositives>> |server + user + api token + projectID + file
| <<unmarkFalsePositives>> |server + user + api token + projectID + file
| help |
| version |
|===


[[section-client-scan]]
===== scan

This is the recommended scan action: You only have to make one single client call to trigger a scan and get the report.

The client performs these steps for you:

 1. create a scan job on the {sechub} server
 2. upload necessary data (e.g. zipped sourcefiles for source scans)
 3. approve the job as ready to start
 4. wait until the job is done
 5. download the report file

NOTE: On "red" (critical or high findings) the {sechub} client exits with a non-zero status so your build will break (depends on your build tool).

IMPORTANT: For security reasons always pass your API-token via the environment variable `SECHUB_APITOKEN`.

**Minimum call syntax**

Prerequisite is a configuration file `sechub.json` in current directory. +
See here for details: <<section-client-configuration-file,Configuration file>>
----
sechub scan
----

TIP: If you prefer the report in HTML format: +
     `sechub -reportformat html scan`

TIP: With `-output ${file-or-directory}` you can define where to place the report. +
     Can be a directory, a file name or a file path. +
     Default: `sechub_report_${your-project}_${jobUUID}.{json|html|spdx}` in current directory

===== scanAsync

Does scan asynchronous:

- Identical to action `scan` but does not wait until the job has finished on the {sechub} server
- Returns the `{sechub}` job UUID of the newly created scan job.

TIP: This can be interesting if you have long running scans and you want have a fast
     continous integration build - but then you have to manually check the
     job state, fetch reports and you get no automated build break!

**Minimum call syntax**
----
sechub scanAsync
----


===== getStatus
Will fetch the job status and return result as json

**Minimum call syntax**
----
sechub getStatus
----

TIP: Defaults to latest job. +
     You can select the job by providing the wanted job UUID by adding `-jobUUID ${jobUUID}`

===== getReport
Will fetch the report as json. (result will only exist when job is done)

**Minimum call syntax**
----
sechub getReport
----

TIP: Defaults to latest finished job. +
     You can select the job by providing the wanted job UUID by adding `-jobUUID ${jobUUID}`

TIP: With `-output ${file-or-directory}` you can define where to place the report. +
     Can be a directory, a file name or a file path. +
     Default: `sechub_report_${your-project}_${jobUUID}.{json|html|spdx}` in current directory

===== listJobs
Lists the last jobs and their state.

**Minimum call syntax**
----
sechub listJobs
----

TIP: This might be useful for an overview or +
     when you want to see your project's scan job queue or +
     to find out the job UUID of a certain job.


===== defineFalsePositives
This will define the false positives list of your project. +
Default definition file to read from is `sechub-false-positives.json` - format is same as for <<section-client-false-positives-mark,markFalsePositives>>.

The client will compare against the already defined false-positives on the server and +
- add missing false-positive definitions +
- remove the ones which are not in the definition file

**Minimum call syntax**
----
sechub defineFalsePositives
----

TIP: With `-file ${file}` you can define where to read from. +
     Default: `sechub-false-positives.json` in current directory

TIP: It's a good idea to add your false-positives definition file in your source code repository. So everybody can easily have an overview about the declared false-positives.

===== getFalsePositives
This will fetch the false positives list of your project as JSON.

**Minimum call syntax**
----
sechub getFalsePositives
----

TIP: With `-output ${file-or-directory}` you can define where to place the result. +
     Can be a directory, a file name or a file path. +
     Default: `sechub-false-positives-${your-project}.json` in current directory

===== interactiveMarkFalsePositives
Instead of creating a json file to mark false positives, you can also do this interactively:
Go to the project directory containing `sechub.json` and a report file from a recent scan and run `sechub interactiveMarkFalsePositives`.

You can select the report file using the `-file` option of the client. Otherwise the project's latest report file in the current directory is automatically selected.

For each finding in the reports file, you are prompted: `"Add this as false positive?"`
Your choices are:

- `y` Yes - Mark as false positive. You are prompted for an optional comment line which can help to understand later why this has been marked.
- `n` No - Do nothing and go to next item.
- `s` Skip following findings - Finish the marking and add the marked items to the false positives list on the {sechub} server.
- `c` Cancel - Quit and upload nothing

TIP: You can download and view your current false positives list with <<getFalsePositives,getFalsePositives>>

See also <<section-client-interactiveMarkFalsePositives-mark,example for interactiveMarkFalsePositives>>

===== interactiveUnmarkFalsePositives
Instead of creating a json file to unmark false positives, you can also do this interactively:
Go to the project directory containing `sechub.json` and run `sechub interactiveUnmarkFalsePositives`

{sechub} client will download the current false positives list and interactively ask each entry: `"Do you want to remove this false positive?"`
Your choices are:

- `y` Yes - Unmark this false positive.
- `n` No - Do nothing and go to next item.
- `s` Skip the rest - End the asking here and remove the marked items from the false positives list on the {sechub} server.
- `c` Cancel - Quit and change nothing

See also <<section-client-interactiveMarkFalsePositives-mark,example for interactiveMarkFalsePositives>>


[[section-client-false-positives-mark]]
===== markFalsePositives
Read your report carefully and figure out which of the findings are "false positives" (FP).
After this, create a json file containing jobUUID and ID of the findings you decided to be a FP.
You should add an optional comment, describing your decision to mark this as FP.
Select this file by the `-file` argument and start action `markFalsePositives`.

**Minimum call syntax**
----
sechub -file ${json-file} markFalsePositives
----

include::../shared/false-positives/false-positives-howto-define-by-api.adoc[]

IMPORTANT: `markFalsePositives` only adds new false positives. +
  Providing an empty list here does *NOT delete* the already declared false positives! +
  If you want this, please use <<defineFalsePositives>>.

TIP: See also <<interactiveMarkFalsePositives,interactiveMarkFalsePositives>> for an easy way to declare false positives.


[[section-client-false-positives-unmark]]
===== unmarkFalsePositives
Remove formerly defined false positives. +
It works similar to `markFalsePositives`: Just define a JSON file, select the file by the `-file` argument and start
action `unmarkFalsePositives`

**Minimum call syntax**
----
sechub -file ${json-file} unmarkFalsePositives
----

*Example JSON:*

[source, json]
----
include::sechub_client_falsepositive_list_example_unmark.json[]
----

TIP: <<interactiveUnmarkFalsePositives,interactiveMarkFalsePositives>> might be much easier to use


==== Configuration overview
Basically parameters can be passed to the `{sechub}` client in three ways:

- commandline options (overrides below)
- environment variables (overrides config file)
- configuration file (default `sechub.json`)

In below table, there is an overview of what can be defined where.
|===
| *scope* | *cmdline option* | *environment variable* | *JSON config file*
| api token | `-apitoken` _(!! not recommended !!)_ | `SECHUB_APITOKEN` |
| append SCM history | `-addScmHistory` | `SECHUB_ADD_SCM_HISTORY` |
| code scan config ||| <<sechub-config-code-scan,codeScan>>
| JSON config file | `-configfile` ||
| file | `-file` ||
| job uuid | `-jobUUID` ||
| label definitions | `-label` | `SECHUB_LABELS` | <<labels,metaData.labels>>
| max. poll interval | `-wait` | `SECHUB_WAITTIME_DEFAULT` |
| network timeout | `-timeout` ||
| output folder or file | `-output` ||
| project id | `-project` | `SECHUB_PROJECT` |project
| quiet mode | `-quiet` | `SECHUB_QUIET` |
| report format | `-reportformat`||
| scan for secrets ||| <<secret-scan,secretScan>>
| server url | `-server` | `SECHUB_SERVER` | server
| stop on yellow | `-stop-on-yellow`||
| temporary dir | `-tempdir` | `SECHUB_TEMP_DIR` |
| trust all certificates || `SECHUB_TRUSTALL` |
| user id | `-user` | `SECHUB_USERID` | user
| web scan config ||| <<web-scan,webScan>>
| DEV: debug http traffic || `SECHUB_DEBUG_HTTP` |
| DEV: enable debugging || `SECHUB_DEBUG` |
| DEV: ignore default excludes || `SECHUB_IGNORE_DEFAULT_EXCLUDES` |
| DEV: initial wait interval || `SECHUB_INITIAL_WAIT_INTERVAL` |
| DEV: keep temporary files || `SECHUB_KEEP_TEMPFILES` |
|===


==== Commandline Options

- `-addScmHistory` +
  Secrets scan only: Upload SCM directories like `.git` for scanning. +
  Can also be defined via environment variable `SECHUB_ADD_SCM_HISTORY=true`.
- `-apitoken <string>` +
  The user's api token - mandatory. _Please try to avoid `-apitoken` parameter for security reasons!!_ +
  Use environment variable `SECHUB_APITOKEN` instead! (see: <<Environment variables>>)
- `-configfile <filepath>` +
  Path to `{sechub}` JSON config file. Defaults to `sechub.json` in current directory.
- `-file <filepath>` +
  Defines file to read from for actions <<defineFalsePositives>>, <<markFalsePositives>>, <<interactiveMarkFalsePositives>>, <<unmarkFalsePositives>>
- `-jobUUID <string>` +
  `{sechub}` job uuid. Optional for actions <<getStatus>> or <<getReport>>
- `-label <label definition>` +
  Define a SecHub label for the scan job. (Example: "key1=value1") Repeat to define multiple labels.
- `-output <path to folder or file>` +
  Where to place reports, false-positive files etc. Can be a directory, a file name or a file path (defaults to current working directory and default file names)
- `-project <string>` +
  Unique project id - mandatory, but can also be defined in config file or via environment variable.
- `-quiet` +
  Quiet mode - Suppress all informative output. Can also be defined via environment variable `SECHUB_QUIET=true`. +
  Only print filenames written to, errors and explicitely requested informations (job-UUID, version, status).
- `-reportformat <format>` +
  Output format for reports. Currently supported: [`json`, `html`, `spdx-json`]. If an unsupported format string is provided, "json" will always be the fallback.
- `-server <url>` +
  Server url of `{sechub}` server to use - e.g. https//example.com:8081. Mandatory, but can also be defined in config file or via environment variable.
- `-stop-on-yellow` +
  A yellow traffic light in the report will result in a non-zero return code.
- `-tempdir <path to folder>` +
  Temporary files will be placed here. (defaults to current working directory)
- `-timeout <seconds>` +
  Timeout for network communication in seconds. (default 120)
- `-user <string>` +
  Username - mandatory, but can also be defined in config file or via environment variable.
- `-wait <seconds>` +
  Maximum wait time in seconds (default 60).
  Will be used for periodic status checks when action=`scan` and for retries of HTTP calls.

==== Environment variables
Additionally to above cmdline options, you can set some values also via environment variables which can be helpful when you have different SecHub environments (like: dev, int, prod)

- `SECHUB_ADD_SCM_HISTORY` +
  (`true` or `false` / unset) Secrets scan only: Upload SCM directories like `.git` for scanning. (same as `-addScmHistory` option)
- `SECHUB_APITOKEN` +
  The SecHub api token for `SECHUB_USERID`. (same as `-apitoken` option)
- `SECHUB_LABELS` +
  Define one or more labels for the scan job. The labels will appear in your SecHub report. Separate multiple labels with ",". (see also `-label` option) +
  Example: `export SECHUB_LABELS="key1=test 1,key2=test 2"`
- `SECHUB_PROJECT` +
  The SecHub project id. (same as `-project` option)
- `SECHUB_QUIET` +
  Quiet mode (`true` or `false` / unset) - Suppress all informative output. (same as `-quiet` option)
- `SECHUB_SERVER` +
  The SecHub server url. (same as `-server` option)
- `SECHUB_TEMP_DIR` +
  Temporary files will be placed here. Make sure that the folder exists and is writeable. (same as `-tempdir` option)
- `SECHUB_TRUSTALL` +
  When set to `true`, then HTTPS certificate checking will be disabled. May be useful when using self-signed certificates. Please try to avoid this setting for security reasons.
- `SECHUB_USERID` +
  The SecHub username. (same as `-user` option)
- `SECHUB_WAITTIME_DEFAULT` +
  Maximum wait time in seconds (default 60). Will be used for automatic status checks etc. when action=`scan`.
- `SECHUB_WHITELIST_ALL` +
  When set to `true` then ignore the default whitelist for source files and add _every_ file. You may want to define <<sechub-config-example-sourcescan,excludes>> in your `sechub.json` file. _!! Handle with care !!_

Settings for debugging/client development:

- `SECHUB_DEBUG` +
  When set to `true` then log as much as possible (but not HTTP request contents)
- `SECHUB_DEBUG_HTTP` +
  When set to `true` then log HTTP request contents.
- `SECHUB_IGNORE_DEFAULT_EXCLUDES` +
  When set to `true` then default exclude folders `+{"**/test/**", "**/.git/**", "**/node_modules/**"}+` will be included for code scan. In this case, you should declare your own <<sechub-config-example-sourcescan,exclude list>> in the config json.
- `SECHUB_INITIAL_WAIT_INTERVAL` +
  Initial wait time (floating point number) until SecHub client polls the first time if the report is ready (`sechub scan`). Meant for local integration tests.
- `SECHUB_KEEP_TEMPFILES` +
  When set to `true` then `sourcecode-<projectID>.zip` files for code scan will not be removed, so you can check, what was uploaded to the `{sechub}` server.


==== Proxy support
The environment variables `http_proxy`, `https_proxy` and `no_proxy` (or the uppercase versions thereof) can be set to use a proxy for accessing the `{sechub}` server.
(`https_proxy` takes precedence over `http_proxy` for https requests.)

Syntax: `[<scheme>://][<username>:<password>@]<proxy host>[:<proxy port>]`

The environment values may be either a complete URL or a "host[:port]", in which case the "http" scheme is assumed.

Examples (Linux/Mac):

`export http_proxy=http://scott:tiger@proxy.example.org:3128`

`export http_proxy=http://localhost:3128` (e.g. when using a local CNTLM proxy)

==== Debugging
For troubleshooting, you can

- set environment variable `SECHUB_DEBUG` to `true` +
  Now you will see in detail what the client does and also the html calls sent to and received from {sechub} server.
- set environment variable `SECHUB_DEBUG_HTTP` to `true` +
  Now you will see the complete HTTP communication including headers. +
  (basic-auth headers (security) and contents of uploads (binary data) are filtered out)
- set environment variable `SECHUB_KEEP_TEMPFILES` to `true` +
  Now `sourcecode-<projectID>.zip` files for code scan or `binaries-<projectID>.tar` will not be removed, so you can check, what was uploaded to the `{sechub}` server.


[[section-client-configuration-file]]
include::../shared/configuration/sechub_config.adoc[]


==== Code scan: accepted source code files
The client will per default only include "wellknown" source files.
This is done by inspecting the filename ending. The accepted defaults are shown in next table.

NOTE: *All files having file endings not listed here, will be ignored* and not uploaded to {sechub} server. +
      *Except* the source data definition is also used for *secrets scanning*. Then every file is being uploaded.

TIP: You can also define additional source file endings - see <<sechub-config-example-sourcescan,config file example>> .

include::../gen/client/gen_table_default_zip_allowed_file_patterns.adoc[]


==== Inject variables into configuration files (For advanced users)
All environment variables are available inside your configuration file in Go
template syntax:

`{{ .ENV_VARIABLE_NAME }}`

For example: When you have defined `USED_API_VERSION` with value `1.0`, you can inject it into a json config file like this:

[source,json]
----
include::sechub_config_apiversion_example.json[]
----


=== Examples

The next subsections contain some `{sechub}` configuration examples.
You can use them as templates for your own files.

First: Define your `{SecHub}` environment variables:

[source, bash]
----
export SECHUB_SERVER=https://sechub.example.org
export SECHUB_USERID=alice
export SECHUB_APITOKEN=EXAMPLE4aa82407da7e06bdbEXAMPLE
export SECHUB_PROJECT=myproject
----

NOTE: Please replace the example values with your real ones to get them working.

==== Start a source code scan

[source, bash]
----
sechub scan
----
with corresponding 'sechub.json' config file: see <<sechub-config-example-sourcescan,source scan example>> .

==== Start a web scan

[source, bash]
----
sechub scan
----
with corresponding 'sechub.json' config file:
see <<sechub-config-example-webscan-anonymous,web scan example (anonymous)>>

==== Start a scan for secrets

[source, bash]
----
sechub scan
----
with corresponding 'sechub.json' config file:
see <<sechub-config-example-secretscan-sources,examples for secret scans>>

==== Start an infra scan

[source, bash]
----
sechub scan
----
with corresponding `sechub.json` config file: <<sechub-config-example-infrascan-with-ip, infrastructure scan example>> .

==== Mark false positives
===== markFalsePositives
[source, bash]
----
sechub -file mark-fp.json markFalsePositives
----
with a corresponding `mark-fp.json` - see <<section-client-false-positives-mark,Mark false positives JSON format>>

[[section-client-interactiveMarkFalsePositives-mark]]
===== interactiveMarkFalsePositives
[source, shell]
```
sechub interactiveMarkFalsePositives

/  ___|         | | | |     | |
\ `--.  ___  ___| |_| |_   _| |__
 `--. \/ _ \/ __|  _  | | | | '_ \
/\__/ /  __/ (__| | | | |_| | |_) |
\____/ \___|\___\_| |_/\__,_|_.__/ Client Version 0.29.0-20220401111823

Using latest report file "sechub_report_mytestproject_0a84899f-1305-41e0-a2d5-e7c31d6185fd.json".
------------------------------------------------------------------
1: Side Channel Data Leakage, severity: HIGH
src/main/java/com/example/testapp/invoice/application/InvoiceApplicationService.java, line 651 column 17
        Invoice creditNote = getInvoice(invoiceId).orElseThrow(InvoiceNotFoundException::new);
------------------------------------------------------------------
Add this as false positive? ('y' Yes, 'n' No, 's' Skip following findings, 'c' Cancel) y
Please add a single line comment:
Can be ignored in our case
------------------------------------------------------------------
2: Unsafe Object Binding, severity: MEDIUM
src/main/java/com/example/testapp/api/ServiceOrderController.java, line 33 column 59
    public void saveAttachment(@RequestBody AttachmentDto attachmentDto){
------------------------------------------------------------------
Add this as false positive? ('y' Yes, 'n' No, 's' Skip following findings, 'c' Cancel) n
------------------------------------------------------------------
3: Unsafe Object Binding, severity: MEDIUM
src/main/java/com/example/testapp/api/CouponController.java, line 30 column 78
    public CouponVerifyResponseDto couponVerify(@RequestBody CouponVerifyDto couponVerifyDto) {
------------------------------------------------------------------
Add this as false positive? ('y' Yes, 'n' No, 's' Skip following findings, 'c' Cancel) s
- Successfully uploaded SecHub false-positives list for project "mytestproject" to server.
```

==== Unmark false positives
===== unmarkFalsePositives
[source, bash]
----
sechub -file mark-fp.json unmarkFalsePositives
----
with a corresponding `mark-fp.json` - see <<section-client-false-positives-unmark,Unmark false positives JSON format>>

[[section-client-interactiveUnmarkFalsePositives-mark]]
===== interactiveUnmarkFalsePositives
[source, shell]
```
sechub interactiveUnmarkFalsePositives
 _____           _   _       _
/  ___|         | | | |     | |
\ `--.  ___  ___| |_| |_   _| |__
 `--. \/ _ \/ __|  _  | | | | '_ \
/\__/ /  __/ (__| | | | |_| | |_) |
\____/ \___|\___\_| |_/\__,_|_.__/ Client Version 0.29.0-20220401111823

- Fetching false-positives list for project "mytestproject".
------------------------------------------------------------------
Side Channel Data Leakage, codeScan severity: HIGH
  Origin: Finding ID 1 in job 0a84899f-1305-41e0-a2d5-e7c31d6185fd
  File: src/main/java/com/example/testapp/invoice/application/InvoiceApplicationService.java
  Code:         Invoice creditNote = getInvoice(invoiceId).orElseThrow(InvoiceNotFoundException::new);
(Added by testuser at 2020-08-20 12:43:03; comment: "Can be ignored in our case")
------------------------------------------------------------------
Do you want to remove this false positive? ('y' Yes, 'n' No, 's' Skip the rest, 'c' Cancel) y
------------------------------------------------------------------
Side Channel Data Leakage, codeScan severity: HIGH
  Origin: Finding ID 2 in job 0c86134c-2305-41e0-a2d5-e7c31df45d15
  File: src/main/java/com/mercedesbenz/otr/invoice/application/ApplicationService.java
  Code:         Invoice invoice = getInvoice(invoiceId).orElseThrow(InvoiceNotFoundException::new);
(Added by testuser at 2020-08-20 12:43:03; comment: "Another explanation example")
------------------------------------------------------------------
Do you want to remove this false positive? ('y' Yes, 'n' No, 's' Skip the rest, 'c' Cancel) s
Applying false-positives to be removed for project "vpc_cn":
- JobUUID 0a84899f-1305-41e0-a2d5-e7c31d6185fd: finding #1
Transfer completed
```
