# Number of SecHub server instances to spin up
replicaCount: 1

image:
  registry: "{{ .SECHUB_SERVER_IMAGE_REGISTRY }}"
  tag: "{{ .SECHUB_SERVER_IMAGE_TAG }}"
  # See https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy
  pullPolicy: "Always"

server:
  spring:
    # Set server profiles (See https://mercedes-benz.github.io/sechub/latest/sechub-techdoc.html#section-sechub-spring-profiles)
    #profiles: dev,h2,real_products,mocked_notifications
    profiles: localserver,initial_admin_predefined,admin_access,h2,real_products,mocked_notifications

env: |-
  - name: SECHUB_INITIALADMIN_APITOKEN
    value: "{{ .SECHUB_INITIALADMIN_APITOKEN }}"
  # -------------------------------------------------------------------------------#
  # - pds-gosec
  # ------------------------------------------------------------------------------ #
  - name: SECHUB_PDS_GOSEC_USERID
    value: "techuser"
  - name: SECHUB_PDS_GOSEC_PASSWORD
    value: "{{ .PDS_GOSEC_TOKEN_TECHUSER }}"
