# SPDX-License-Identifier: MIT

version: "3"
services:
    pds-pmd:
        build:
            args:
                - BASE_IMAGE=debian:12-slim
            context: docker/
            dockerfile: PMD-Debian.dockerfile
        container_name: pds-pmd
        hostname: pds-pmd
        volumes:
          - ./docker/scripts:/pds/scripts
        env_file:
            - .env
        ports:
            - "127.0.0.1:8444:8444"
            - "127.0.0.1:15024:15024"
        networks:
            - "sechub"

networks:
    sechub:
        external: true
        name: "sechub"
