// SPDX-License-Identifier: MIT

:toc:
:numbered:

= PMD + PDS

https://pmd.github.io/[PMD] is a free and open source static application security testing tool. PMD is a command line interface (CLI) tool. By combining PMD with the SecHub https://mercedes-benz.github.io/sechub/latest/sechub-product-delegation-server.html[Product Delegation Server (PDS)] in a container, PMD can be used with SecHub. Another scenario is to use PMD+PDS standalone.

Furthermore, the combination of PMD and PDS makes it possible to run both inside a Kubernetes cluster or virtual machines.

This folder contains the necessary scripts to run PMD+PDS inside a container locally. Additionally, it contains scripts to build and push the PMD+PDS container to your container registry and a Helm chart to install and run PMD+PDS in a Kubernetes cluster.

== Run Locally

This is the easiest way to get started.

=== Requirements

Docker and Docker-Compose need to be installed:

. https://docs.docker.com/engine/install/[Install Docker]

. Linux: https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user[Use Docker as non Root user]

. https://docs.docker.com/compose/install/[Install Docker-Compose]

=== Single Instance

Start a single instance by using the Bash wrapper script which does setup everything automatically for you.

==== Scan script

The folder contains a start script which does the manual steps for you:

----
./01-start-docker-compose.sh
----

==== Together with SecHub

The container will be started and attached to the `sechub` Network.

WARNING: Make sure the SecHub container is running.

. Start container:
+
----
./05-start-single-sechub-network-docker-compose.sh
----

=== Scan

The steps required to scan with the PDS.

==== Scan Script

. Set the environment variables
+
----
export PDS_SERVER=https://<pds-host>:<port>
export PDS_USERID=admin
export PDS_APITOKEN="<pds-admin-apitoken>"
export PDS_PRODUCT_IDENTFIER=PDS_PMD
----
+
For example:
+
----
export PDS_SERVER=https://localhost:8444
export PDS_USERID=admin
export PDS_APITOKEN="pds-apitoken"
export PDS_PRODUCT_IDENTFIER=PDS_PMD
----
+
[NOTE]
Those values are the default values from `env-initial` and `env-cluster-initial` files. In case you run PMD+PDS in Kubernetes or other environments those values will be different.

. Scan by providing a `ZIP` folder with Go source code.
+
----
cd ../shared/
./01-test.sh <path-to-zip-file>
----
+
For example:
+
----
cd ../shared/
./01-test.sh ~/myproject.zip
----

=== Cluster

The cluster is created locally via `docker-compose`.

==== Shared Volume

The cluster uses a shared volume defined in `docker-compose`. Docker allows to create volumes which can be used by multiple instances to upload files to. Reading, extracting and analysing the files is done in the PMD+PDS container.

The cluster consists of a PostgreSQL database, a Nginx loadbalancer and one or more PDS server.

image::../shared/media/cluster_shared_volume.svg[Components of cluster with shared volume]

===== Start Script

Starting several PMD+PDS instances:

----
./50-start-multiple-docker-compose.sh <replicas>
----

Example of starting 3 PMD+PDS instances:

----
./50-start-multiple-docker-compose.sh 3
----

==== Object Storage

The cluster uses an object storage to store files. The cluster uses https://github.com/chrislusf/seaweedfs[SeaweedFS] (S3 compatible) to store files. The PDS instance(s) use the object storage to upload files to. Reading, extracting and analysing the files is done in the PMD+PDS container.

The cluster consists of a PostgreSQL database, a Nginx loadbalancer, a SeaweedFS object storage and one or more PDS server.

image::../shared/media/cluster_object_storage.svg[Components of cluster with object storage]

===== Start Script

Starting several PMD+PDS instances

----
./51-start-multiple-object-storage-docker-compose.sh <replicas>
----

Example of starting 3 PMD+PDS instances

----
./51-start-multiple-object-storage-docker-compose.sh 3
----

=== Change the Configuration

There are several configuration options available for the PMD+PDS `docker-compose` files. Have a look at `env-example` for more details.

=== Troubleshooting

This section contains information about how to troubleshoot PMD+PDS if something goes wrong.

==== Access the container

----
docker exec -it pds-pmd bash
----

==== Java Application Remote Debugging of PDS

. Set `JAVA_ENABLE_DEBUG=true` in the `.env` file

. Connect via remote debugging to the `pds`
+
connect via CLI
(see: )
+
----
jdb -attach localhost:15024
----
+
TIP: https://www.baeldung.com/java-application-remote-debugging[Java Application Remote Debugging] and https://www.tutorialspoint.com/jdb/jdb_basic_commands.htm[JDB - Basic Commands]
+
or connect via IDE (e. g. Eclipse IDE, VSCodium, Eclipse Theia, IntelliJ etc.).
+
TIP: https://www.eclipse.org/community/eclipse_newsletter/2017/june/article1.php[Debugging the Eclipse IDE for Java Developers]

== Build Image and Push to Registry

Build container images and push them to registry to run PMD+PDS on virtual machines, Kubernetes or any other distributed system.

=== Build Image

Build the container image.

==== Build

. Using the default image:
+
----
./10-create-image.sh my.registry.example.org/sechub/pds_pmd v0.1
----

. Using your own base image:
+
----
./10-create-image.sh my.registry.example.org/sechub/pds_pmd v0.1 "my.registry.example.org/debian:12-slim"
----

=== Push Image to Registry

Push the container image to a registry.

* Push the version tag only
+
----
./20-push-image.sh my.registry.example.org/sechub/pds_pmd v0.1
----

* Push the version and `latest` tags
+
----
./20-push-image.sh my.registry.example.org/sechub/pds_pmd v0.1 yes
----

== Kubernetes

https://kubernetes.io/[Kubernetes] is an open-source container-orchestration system. This sections explains how to deploy and run PMD+PDS in Kubernetes.

=== Helm

https://helm.sh/[Helm] is a package manager for Kubernetes.

==== Requierments

* https://helm.sh/docs/intro/install/[Helm] installed
* `pds_pmd` image pushed to registry

==== Installation

. Create a `myvalues.yaml` configuration file
+
A minimal example configuration file with one instance:
+
[source,yaml]
----
replicaCount: 1

image:
   registry: my.registry.example.org/sechub/pds_pmd
   tag: latest

pds:
   startMode: localserver

users:
   admin:
      id: "admin"
      apiToken: "{noop}<my-admin-password>"
   technical:
      id: "techuser"
      apiToken: "{noop}<my-technical-password>"

storage:
    local:
        enabled: true

networkPolicy:
    enabled: true
    ingress:
    - from:
        - podSelector:
            matchLabels:
                name: sechub-server
        - podSelector:
            matchLabels:
                name: sechub-adminserver
----
+
An example configuration file with 3 replicas, postgresql and object storage:
+
[source,yaml]
----
replicaCount: 3

image:
   registry: my.registry.example.org/sechub/pds_pmd
   tag: latest

pds:
   startMode: localserver
   keepContainerAliveAfterPDSCrashed: true

users:
   admin:
      id: "admin"
      apiToken: "{noop}<my-admin-password>"
   technical:
      id: "techuser"
      apiToken: "{noop}<my-technical-password>"


database:
    postgres:
        enabled: true
        connection: "jdbc:postgresql://<my-database-host>:<port>/<my-database>"
        username: "<username-for-my-database>"
        password: "<password-for-my-database>"

storage:
    local:
        enabled: false
    s3:
        enabled: true
        endpoint: "https://<my-s3-object-storage>:443"
        bucketname: "<my-bucket>"
        accesskey: "<my-accesskey>"
        secretkey: "<my-secretkey>"

networkPolicy:
    enabled: true
    ingress:
    - from:
        - podSelector:
            matchLabels:
                name: sechub-server
        - podSelector:
            matchLabels:
                name: sechub-adminserver
----
+
[TIP]
To generate passwords use `tr -dc A-Za-z0-9 </dev/urandom | head -c 18 ; echo ''`, `openssl rand -base64 15`, `apg -MSNCL -m 15 -x 20` or `shuf -zer -n20  {A..Z} {a..z} {0..9}`.

. Install helm package from file system
+
----
helm install --values myvalues.yaml pds-pmd helm/pds-pmd/
----
+
[TIP]
Use `helm --namespace <my-namespace> install…` to install the helm chart into another namespace in the Kubernetes cluster.

. List pods
+
----
kubectl get pods
NAME                             READY   STATUS    RESTARTS   AGE
pds-pmd-545f5bc8-7s6rh         1/1     Running   0          1m43s
pds-pmd-545f5bc8-px9cs         1/1     Running   0          1m43s
pds-pmd-545f5bc8-t52p6         1/1     Running   0          3m

----

. Forward port of one of the pods to own machine
+
----
kubectl port-forward pds-pmd-545f5bc8-7s6rh  8444:8444
----

. Scan as explained in <<_scan>>.

==== Upgrade

In case, `my-values.yaml` was changed. Simply, use `helm upgrade` to update the deployment. `helm` will handle scaling up and down as well as changing the configuration.

----
helm upgrade --values my-values.yaml pds-pmd helm/pds-pmd/
----

==== Uninstall

. Helm list
+
----
helm list
NAME     	NAMESPACE 	REVISION	UPDATED                                 	STATUS  	CHART                          	APP VERSION
pds-pmd	my-namespace	1       	2021-06-24 21:54:37.668489822 +0200 CEST	deployed	pds-pmd-0.1.0                	0.21.0
----

. Helm uninstall
+
----
helm uninstall pds-pmd
----

=== Troubleshooting

* Access deployment events.
+
----
kubectl describe pod pds-pmd-545f5bc8-7s6rh
…
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  1m    default-scheduler  Successfully assigned sechub-dev/pds-pmd-749fcb8d7f-jjqwn to kube-node01
  Normal  Pulling    54s   kubelet            Pulling image "my.registry.example.org/sechub/pds_pmd:v0.1"
  Normal  Pulled     40s   kubelet            Successfully pulled image "my.registry.example.org/sechub/pds_pmd:v0.1" in 13.815348799s
  Normal  Created    15s   kubelet            Created container pds-pmd
  Normal  Started    10s   kubelet            Started container pds-pmd
----

* Access container logs.
+
----
kubectl logs pds-pmd-545f5bc8-7s6rh
----
