# SPDX-License-Identifier: MIT
# Number of SecHub web-ui instances to spin up
replicaCount: 1

image: "{{ .WEBUI_IMAGE }}"
imagePullPolicy: "Always"

service:
  loadbalancer:
    ip: none
    port:
      name: web-ui-https
      number: {{ .WEBUI_LB_PORT }}
