# SPDX-License-Identifier: MIT

version: "1"
services:
    pds-phan:
        build:
            args:
                - BASE_IMAGE=${BASE_IMAGE}
            context: docker/
            dockerfile: Phan-Debian.dockerfile
        container_name: pds-phan
        env_file:
            - .env
            - .env-single
        ports:
            - "127.0.0.1:8444:8444"
        networks:
            - "internal"
        volumes:
          - ./docker/scripts:/pds/scripts
networks:
    internal:
