# SPDX-License-Identifier: MIT
name: Build and publish all PDS solutions

on:
  workflow_dispatch:
    inputs:
      pds-version:
        description: pds-base version to use (e.g. 1.0.0)
        required: true
  workflow_call:
    inputs:
      pds-version:
        required: true
        type: string

jobs:
  build-pds-solutions:
    name: Build and publish all PDS solutions
    runs-on: ubuntu-latest
    steps:
      - name: "Show Inputs"
        run: |
          echo "pds-version '${{ github.event.inputs.checkmarx-wrapper-version }}'"

      - name: Checkout branch master
        uses: actions/checkout@v3
        with:
          ref: master
