# SPDX-License-Identifier: MIT
name: Release WebUI

on:
  workflow_dispatch:
    inputs:
      actor-email:
        description: Insert your email address here. It will be used in the generated pull requests
        required: true
      webui-version:
        description: WebUI Version (e.g. 0.1.0)
        required: true
      webui-milestone-number:
        description: WebUI Milestone number (e.g. 70)
        required: true

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write

env:
  ACTIONS_BASE_IMAGE_ALPINE: alpine:3.17
  ACTIONS_BASE_IMAGE_DEBIAN: debian:12-slim
  ACTIONS_SECHUB_REGISTRY: ghcr.io/mercedes-benz/sechub
  ACTIONS_HELM_REGISTRY: "oci://ghcr.io/mercedes-benz/sechub/helm-charts"

jobs:
  release-version:
    name: Create WebUI release
    runs-on: ubuntu-latest
    steps:

      - name: "Show Inputs"
        run: |
          echo "actor-email: '${{ inputs.actor-email }}'"
          echo "WebUI '${{ inputs.webui-version }}' - Milestone '${{ inputs.webui-milestone-number }}'"

      # Check inputs:
      - name: "Verify Input for WebUI release"
        if: (inputs.webui-version == '') || (inputs.webui-milestone-number == '')
        run: |
          echo "For WebUI release, webui-version and webui-milestone-number must be provided!"
          exit 1

      - name: Checkout master
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
        with:
          ref: master

      # Create temporary local tag, so we build for this tag...
      # The final tag on git server side will be done automatically by the release when the draft is saved as "real" release
      - name: "Temporary tag server version: v${{ inputs.webui-version }}-webui"
        run: git tag v${{ inputs.webui-version }}-webui

      # ----------------------
      # Setup + Caching
      # ----------------------
      - name: Set up JDK 17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@af6e5767241073b8ab20cc8cf7e95ec63fadc160
        with:
          cache-read-only: false

      - name: Docker login to ghcr.io
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ----------------------
      # Create pull request if license headers are missing
      # ----------------------
      - name: run apply-headers.sh
        id: apply-headers
        run: |
          git config user.name "$GITHUB_TRIGGERING_ACTOR (via github-actions)"
          git config user.email "${{ inputs.actor-email }}"
          ./apply-headers.sh
          git commit -am "SPDX headers added by SecHub release job @github-actions" || true
          COMMITS=`git log --oneline --branches --not --remotes`
          echo "commits=$COMMITS" >> $GITHUB_OUTPUT

      - name: Create pull request for SPDX license headers
        id: pr_spdx_headers
        if: steps.apply-headers.outputs.commits != ''
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e
        with:
          branch: release-spdx-headers
          branch-suffix: short-commit-hash
          delete-branch: true
          title: '0 - Before webui release: Add missing SPDX license headers [auto-generated]'
          body: |
            Auto-generated by Github Actions webui release job.

            -> Please review and merge **before** publishing the webui release.

      - name: Print PR infos
        if: steps.apply-headers.outputs.commits != ''
        run: |
          echo "Pull Request Number - ${{ steps.pr_spdx_headers.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.pr_spdx_headers.outputs.pull-request-url }}"

      # ----------------------
      # Build SecHub WebUI
      # ----------------------
      - name: Build WebUI jar files
        run: ./gradlew ensureLocalhostCertificate :sechub-api-java:build :sechub-webui:build -Dsechub.build.stage=api-necessary --console=plain

      # To identifiy parts not in git history
      - name: Collect GIT status
        if: always()
        run: |
          # restore reduced-openapi3.json
          git restore sechub-api-java/src/main/resources/reduced-openapi3.json
          mkdir -p build/reports
          git status > build/reports/git-status.txt
          echo "--- git tags:" >> build/reports/git-status.txt
          git tag --points-at HEAD >> build/reports/git-status.txt

      - name: Archive GIT status
        if: always()
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        with:
          name: git-status.txt
          path: build/reports/git-status.txt
          retention-days: 14

      - name: Archive WebUI artifacts
        if: always()
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        with:
          name: sechub-webui
          path: sechub-webui/build/libs
          retention-days: 14

      # -----------------------------------------
      # Assert releaseable: Check for uncommitted changes
      # -----------------------------------------
      - name: Assert releasable
        run: |
          git status
          ./gradlew assertReleaseable

      - name: Create WebUI release
        id: create_webui_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ inputs.webui-version }}-webui
          commitish: master
          release_name: WebUI Version ${{ inputs.webui-version }}
          body: |
            Changes in this Release
            - Some minor changes on WebUI implementation

            For more details please look at [Milestone ${{inputs.webui-milestone-number}}]( https://github.com/mercedes-benz/sechub/milestone/${{inputs.webui-milestone-number}}?closed=1)
          draft: true
          prerelease: false

      - name: Create sha256 checksum file for WebUI jar
        run: |
          cd sechub-webui/build/libs
          sha256sum sechub-webui-${{ inputs.webui-version }}.jar > sechub-webui-${{ inputs.webui-version }}.jar.sha256sum

      - name: Upload WebUI release asset sechub-webui-${{ inputs.webui-version }}.jar
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_webui_release.outputs.upload_url }}
          asset_path: sechub-webui/build/libs/sechub-webui-${{ inputs.webui-version }}.jar
          asset_name: sechub-webui-${{ inputs.webui-version }}.jar
          asset_content_type: application/zip

      - name: Upload WebUI release asset sechub-webui-${{ inputs.webui-version }}.jar.sha256sum
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_webui_release.outputs.upload_url }}
          asset_path: sechub-webui/build/libs/sechub-webui-${{ inputs.webui-version }}.jar.sha256sum
          asset_name: sechub-webui-${{ inputs.webui-version }}.jar.sha256sum
          asset_content_type: text/plain

      # -----------------------------------------
      # Create release issue
      # -----------------------------------------
      - name: Create SecHub WebUI ${{ inputs.webui-version }} release issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Release SecHub WebUI ${{ inputs.webui-version }}
          body: |
            See [Milestone ${{inputs.webui-milestone-number}}]( https://github.com/mercedes-benz/sechub/milestone/${{inputs.webui-milestone-number}}?closed=1) for details.

            Please close this issue after the release.
          milestone: ${{ inputs.webui-milestone-number }}

      # Build SecHub WebUI container image + push to ghcr
      - name: Build sechub-webui ${{ inputs.webui-version }} container image + push to ghcr
        run: |
          WEBUI_VERSION="${{ inputs.webui-version }}"
          DOCKER_REGISTRY="$ACTIONS_SECHUB_REGISTRY/sechub-webui"
          VERSION_TAG="${WEBUI_VERSION}"
          cp sechub-webui/build/libs/sechub-webui-${WEBUI_VERSION}.jar sechub-webui-solution/docker/copy/
          cd sechub-webui-solution
          echo "# Building image $DOCKER_REGISTRY:$VERSION_TAG"
          echo "  from $ACTIONS_BASE_IMAGE_DEBIAN"
          ./10-create-image.sh "$DOCKER_REGISTRY" "$VERSION_TAG" "$WEBUI_VERSION" "$ACTIONS_BASE_IMAGE_DEBIAN" copy
          echo "# Pushing image $DOCKER_REGISTRY:$VERSION_TAG (latest)"
          ./20-push-image.sh "$DOCKER_REGISTRY" "$VERSION_TAG" yes

      - name: Build sechub-webui Helm chart + push to ghcr
        shell: bash
        run: |
          cd sechub-webui-solution/helm
          echo "# Building Helm chart for SecHub WebUI"
          helm package sechub-webui
          helm push sechub-webui-*.tgz $ACTIONS_HELM_REGISTRY

      # -----------------------------------------
      # Create a pull request for merging back `master` into `develop`
      # -----------------------------------------
      - name: pull-request master to develop
        id: pr_master_to_develop
        continue-on-error: true
        uses: repo-sync/pull-request@7e79a9f5dc3ad0ce53138f01df2fad14a04831c5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: "master"
          destination_branch: "develop"
          pr_allow_empty: true  # should allow an empty PR, but seems not to work
          pr_title: '2 - After webui release: Merge master back into develop [auto-generated]'
          pr_body: |
            After SecHub WebUI release
            - WebUI '${{ inputs.webui-version }}'

            Merge master branch back into develop

            -> Please merge **after** the release has been published.

      - name: Print PR infos if PR was created
        if: steps.pr_master_to_develop.outcome == 'success'
        run: |
          echo "Pull Request Number - ${{ steps.pr_master_to_develop.outputs.pr_number }}"
          echo "Pull Request URL - ${{ steps.pr_master_to_develop.outputs.pr_url }}"

      - name: Print info if no PR was created
        if: steps.pr_master_to_develop.outcome != 'success'
        run: |
          echo "Nothing to merge - no pull request necessary."
