# SPDX-License-Identifier: MIT
name: SecHub Jetbrains plugin Java build

on:
  push:
    branches:
      - 'develop'
      - 'hotfix'
      - 'main'
      - 'master'
    paths:
      - '.github/workflows/sechub-plugin-jetbrains-gradle.yml'
      - 'ide-plugins/jetbrains/**'
  pull_request:
    paths:
      - '.github/workflows/sechub-plugin-jetbrains-gradle.yml'
      - 'ide-plugins/jetbrains/**'
  # enable manual triggering of workflow
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ide-plugins/jetbrains
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK 17
      uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b
      with:
        distribution: temurin
        java-version: 17

    - name: "Build plugin"
      run: ./gradlew test buildPlugin

    - name: "Archive test results"
      if: always()
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
          name: test-results
          path: |
            ide-plugins/jetbrains/build/reports
            retention-days: 14
    - name: "Documentations"
      run: ./gradlew asciidoc

    - name: "Archive documentation"
      if: always()
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
          name: documentation
          path: |
            ide-plugins/jetbrains/build/docs/asciidoc
            retention-days: 14