# SPDX-License-Identifier: MIT
name: SecHub eclipse plugin Java build

on:
  push:
    branches:
      - 'develop'
      - 'hotfix'
      - 'main'
      - 'master'
    paths:
      - '.github/workflows/sechub-plugin-eclipse-gradle.yml'
      - 'ide-plugins/eclipse/**'
  pull_request:
    paths:
      - '.github/workflows/sechub-plugin-eclipse-gradle.yml'
      - 'ide-plugins/eclipse/**'
  # enable manual triggering of workflow
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ide-plugins/eclipse
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 17
    - name: Gradle clean build
      run: ./gradlew clean build
    - name: "Archive test results"
      if: always()
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
          name: test-results
          path: |
            ide-plugins/eclipse/sechub-eclipse-plugin/build/reports
            retention-days: 14