# SPDX-License-Identifier: MIT
name: SecHub Jetbrains plugin Java build

on:
  push:
    branches:
      - 'develop'
      - 'hotfix'
      - 'main'
      - 'master'
    paths:
      - '.github/workflows/sechub-plugin-jetbrains-gradle.yml'
      - 'ide-plugins/jetbrains/**'
  pull_request:
    paths:
      - '.github/workflows/sechub-plugin-jetbrains-gradle.yml'
      - 'ide-plugins/jetbrains/**'
  # enable manual triggering of workflow
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ide-plugins/jetbrains
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up JDK 17
      uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0
      with:
        distribution: temurin
        java-version: 17

    - name: "Build plugin"
      run: ./gradlew test buildPlugin

    - name: "Archive test results"
      if: always()
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
      with:
          name: test-results
          path: |
            build/reports
            retention-days: 14
    - name: "Documentations"
      run: ./gradlew asciidoc

    - name: "Archive documentation"
      if: always()
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
      with:
          name: documentation
          path: |
            build/docs/asciidoc
            retention-days: 14