# SPDX-License-Identifier: MIT
name: SecHub plugin vscode CI
on: 
  push:
    branches:
      - 'develop'
      - 'hotfix'
      - 'main'
      - 'master'
    paths:
      - '.github/workflows/sechub-plugin-vscode-ci.yml'
      - 'ide-plugins/vscode/**'
  pull_request:
    paths:
      - '.github/workflows/sechub-plugin-vscode-ci.yml'
      - 'ide-plugins/vscode/**'
  # enable manual triggering of workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 18 ]

    defaults:
      run:
        working-directory: ide-plugins/vscode
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-node@v3
      with:
        # Matrix test using LTS (Long Term Support) versions
        node-version: ${{ matrix.node }}
    - run: npm ci
    # https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions

    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'
